window.POEMS = window.POEMS || {};

window.POEMS["le-lethe"] = {
  title: "Le Léthé",
  titles: { fr: "Le Léthé" },
  sources: {
    fr: "Les Épaves (1866) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/%C3%89paves_%28Baudelaire%2C_1866%29/Le_L%C3%A9th%C3%A9",
  },
  segments: [
    { id: 0, fr: "Viens sur mon cœur, âme cruelle et sourde," },
    { id: 1, fr: "Tigre adoré, monstre aux airs indolents ;" },
    { id: 2, fr: "Je veux longtemps plonger mes doigts tremblants" },
    { id: 3, fr: "Dans l’épaisseur de ta crinière lourde ;" },
    { id: 4, fr: "Dans tes jupons remplis de ton parfum" },
    { id: 5, fr: "Ensevelir ma tête endolorie," },
    { id: 6, fr: "Et respirer, comme une fleur flétrie," },
    { id: 7, fr: "Le doux relent de mon amour défunt." },
    { id: 8, fr: "Je veux dormir ! dormir plutôt que vivre !" },
    { id: 9, fr: "Dans un sommeil aussi doux que la mort," },
    { id: 10, fr: "J’étalerai mes baisers sans remord" },
    { id: 11, fr: "Sur ton beau corps poli comme le cuivre." },
    { id: 12, fr: "Pour engloutir mes sanglots apaisés" },
    { id: 13, fr: "Rien ne me vaut l’abîme de ta couche ;" },
    { id: 14, fr: "L’oubli puissant habite sur ta bouche," },
    { id: 15, fr: "Et le Léthé coule dans tes baisers." },
    { id: 16, fr: "À mon destin, désormais mon délice," },
    { id: 17, fr: "J’obéirai comme un prédestiné ;" },
    { id: 18, fr: "Martyr docile, innocent condamné," },
    { id: 19, fr: "Dont la ferveur attise le supplice," },
    { id: 20, fr: "Je sucerai, pour noyer ma rancœur," },
    { id: 21, fr: "Le népenthès et la bonne ciguë" },
    { id: 22, fr: "Aux bouts charmants de cette gorge aiguë," },
    { id: 23, fr: "Qui n’a jamais emprisonné de cœur." },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
