window.POEMS = window.POEMS || {};

window.POEMS["les-bijoux"] = {
  title: "Les Bijoux",
  titles: { fr: "Les Bijoux" },
  sources: {
    fr: "Les Épaves (1866) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/%C3%89paves_%28Baudelaire%2C_1866%29/Les_Bijoux",
  },
  segments: [
    { id: 0, fr: "La très-chère était nue, et, connaissant mon cœur," },
    { id: 1, fr: "Elle n’avait gardé que ses bijoux sonores," },
    { id: 2, fr: "Dont le riche attirail lui donnait l’air vainqueur" },
    { id: 3, fr: "Qu’ont dans leurs jours heureux les esclaves des Mores." },
    { id: 4, fr: "Quand il jette en dansant son bruit vif et moqueur," },
    { id: 5, fr: "Ce monde rayonnant de métal et de pierre" },
    { id: 6, fr: "Me ravit en extase, et j’aime à la fureur" },
    { id: 7, fr: "Les choses où le son se mêle à la lumière." },
    { id: 8, fr: "Elle était donc couchée et se laissait aimer," },
    { id: 9, fr: "Et du haut du divan elle souriait d’aise" },
    { id: 10, fr: "À mon amour profond et doux comme la mer," },
    { id: 11, fr: "Qui vers elle montait comme vers sa falaise." },
    { id: 12, fr: "Les yeux fixés sur moi, comme un tigre dompté," },
    { id: 13, fr: "D’un air vague et rêveur elle essayait des poses," },
    { id: 14, fr: "Et la candeur unie à la lubricité" },
    { id: 15, fr: "Donnait un charme neuf à ses métamorphoses ;" },
    { id: 16, fr: "Et son bras et sa jambe, et sa cuisse et ses reins," },
    { id: 17, fr: "Polis comme de l’huile, onduleux comme un cygne," },
    { id: 18, fr: "Passaient devant mes yeux clairvoyants et sereins ;" },
    { id: 19, fr: "Et son ventre et ses seins, ces grappes de ma vigne," },
    { id: 20, fr: "S’avançaient, plus câlins que les Anges du mal," },
    { id: 21, fr: "Pour troubler le repos où mon âme était mise," },
    { id: 22, fr: "Et pour la déranger du rocher de cristal" },
    { id: 23, fr: "Où, calme et solitaire, elle s’était assise." },
    { id: 24, fr: "Je croyais voir unis par un nouveau dessin" },
    { id: 25, fr: "Les hanches de l’Antiope au buste d’un imberbe," },
    { id: 26, fr: "Tant sa taille faisait ressortir son bassin." },
    { id: 27, fr: "Sur ce teint fauve et brun le fard était superbe !" },
    { id: 28, fr: "— Et la lampe s’étant résignée à mourir," },
    { id: 29, fr: "Comme le foyer seul illuminait la chambre," },
    { id: 30, fr: "Chaque fois qu’il poussait un flamboyant soupir," },
    { id: 31, fr: "Il inondait de sang cette peau couleur d’ambre !" },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
