window.POEMS = window.POEMS || {};

window.POEMS["lesbos"] = {
  title: "Lesbos",
  titles: { fr: "Lesbos" },
  sources: {
    fr: "Les Épaves (1866) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/%C3%89paves_%28Baudelaire%2C_1866%29/Lesbos",
  },
  segments: [
    { id: 0, fr: "Mère des jeux latins et des voluptés grecques," },
    { id: 1, fr: "Lesbos, où les baisers, languissants ou joyeux," },
    { id: 2, fr: "Chauds comme les soleils, frais comme les pastèques," },
    { id: 3, fr: "Font l’ornement des nuits et des jours glorieux ;" },
    { id: 4, fr: "Mère des jeux latins et des voluptés grecques," },
    { id: 5, fr: "Lesbos, où les baisers sont comme les cascades" },
    { id: 6, fr: "Qui se jettent sans peur dans les gouffres sans fonds," },
    { id: 7, fr: "Et courent, sanglotant et gloussant par saccades," },
    { id: 8, fr: "Orageux et secrets, fourmillants et profonds ;" },
    { id: 9, fr: "Lesbos, où les baisers sont comme les cascades !" },
    { id: 10, fr: "Lesbos, où les Phrynés l’une l’autre s’attirent," },
    { id: 11, fr: "Où jamais un soupir ne resta sans écho," },
    { id: 12, fr: "À l’égal de Paphos les étoiles t’admirent," },
    { id: 13, fr: "Et Vénus à bon droit peut jalouser Sapho !" },
    { id: 14, fr: "Lesbos, où les Phrynés l’une l’autre s’attirent," },
    { id: 15, fr: "Lesbos, terre des nuits chaudes et langoureuses," },
    { id: 16, fr: "Qui font qu’à leurs miroirs, stérile volupté !" },
    { id: 17, fr: "Les filles aux yeux creux, de leur corps amoureuses," },
    { id: 18, fr: "Caressent les fruits mûrs de leur nubilité ;" },
    { id: 19, fr: "Lesbos, terre des nuits chaudes et langoureuses," },
    { id: 20, fr: "Laisse du vieux Platon se froncer l’œil austère ;" },
    { id: 21, fr: "Tu tires ton pardon de l’excès des baisers," },
    { id: 22, fr: "Reine du doux empire, aimable et noble terre," },
    { id: 23, fr: "Et des raffinements toujours inépuisés." },
    { id: 24, fr: "Laisse du vieux Platon se froncer l’œil austère." },
    { id: 25, fr: "Tu tires ton pardon de l’éternel martyre," },
    { id: 26, fr: "Infligé sans relâche aux cœurs ambitieux," },
    { id: 27, fr: "Qu’attire loin de nous le radieux sourire" },
    { id: 28, fr: "Entrevu vaguement au bord des autres cieux !" },
    { id: 29, fr: "Tu tires ton pardon de l’éternel martyre !" },
    { id: 30, fr: "Qui des Dieux osera, Lesbos, être ton juge" },
    { id: 31, fr: "Et condamner ton front pâli dans les travaux," },
    { id: 32, fr: "Si ses balances d’or n’ont pesé le déluge" },
    { id: 33, fr: "De larmes qu’à la mer ont versé tes ruisseaux ?" },
    { id: 34, fr: "Qui des Dieux osera, Lesbos, être ton juge ?" },
    { id: 35, fr: "Que nous veulent les lois du juste et de l’injuste ?" },
    { id: 36, fr: "Vierges au cœur sublime, honneur de l’archipel," },
    { id: 37, fr: "Votre religion comme une autre est auguste," },
    { id: 38, fr: "Et l’amour se rira de l’Enfer et du Ciel !" },
    { id: 39, fr: "Que nous veulent les lois du juste et de l’injuste ?" },
    { id: 40, fr: "Car Lesbos entre tous m’a choisi sur la terre" },
    { id: 41, fr: "Pour chanter le secret de ses vierges en fleurs," },
    { id: 42, fr: "Et je fus dès l’enfance admis au noir mystère" },
    { id: 43, fr: "Des rires effrénés mêlés aux sombres pleurs ;" },
    { id: 44, fr: "Car Lesbos entre tous m’a choisi sur la terre." },
    { id: 45, fr: "Et depuis lors je veille au sommet de Leucate," },
    { id: 46, fr: "Comme une sentinelle à l’œil perçant et sûr," },
    { id: 47, fr: "Qui guette nuit et jour brick, tartane ou frégate," },
    { id: 48, fr: "Dont les formes au loin frissonnent dans l’azur ;" },
    { id: 49, fr: "Et depuis lors je veille au sommet de Leucate" },
    { id: 50, fr: "Pour savoir si la mer est indulgente et bonne," },
    { id: 51, fr: "Et parmi les sanglots dont le roc retentit" },
    { id: 52, fr: "Un soir ramènera vers Lesbos, qui pardonne," },
    { id: 53, fr: "Le cadavre adoré de Sapho, qui partit" },
    { id: 54, fr: "Pour savoir si la mer est indulgente et bonne !" },
    { id: 55, fr: "De la mâle Sapho, l’amante et le poëte," },
    { id: 56, fr: "Plus belle que Vénus par ses mornes pâleurs !" },
    { id: 57, fr: "— L’œil d’azur est vaincu par l’œil noir que tachète" },
    { id: 58, fr: "Le cercle ténébreux tracé par les douleurs" },
    { id: 59, fr: "De la mâle Sapho, l’amante et le poëte !" },
    { id: 60, fr: "— Plus belle que Vénus se dressant sur le monde" },
    { id: 61, fr: "Et versant les trésors de sa sérénité" },
    { id: 62, fr: "Et le rayonnement de sa jeunesse blonde" },
    { id: 63, fr: "Sur le vieil Océan de sa fille enchanté ;" },
    { id: 64, fr: "Plus belle que Vénus se dressant sur le monde !" },
    { id: 65, fr: "— De Sapho qui mourut le jour de son blasphème," },
    { id: 66, fr: "Quand, insultant le rite et le culte inventé," },
    { id: 67, fr: "Elle fit son beau corps la pâture suprême" },
    { id: 68, fr: "D’un brutal dont l’orgueil punit l’impiété" },
    { id: 69, fr: "De celle qui mourut le jour de son blasphème." },
    { id: 70, fr: "Et c’est depuis ce temps que Lesbos se lamente," },
    { id: 71, fr: "Et, malgré les honneurs que lui rend l’univers," },
    { id: 72, fr: "S’enivre chaque nuit du cri de la tourmente" },
    { id: 73, fr: "Que poussent vers les cieux ses rivages déserts !" },
    { id: 74, fr: "Et c’est depuis ce temps que Lesbos se lamente !" },
  ],
  blocks: [
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
  ],
};
