window.POEMS = window.POEMS || {};

window.POEMS["au-lecteur"] = {
  title: "Au lecteur",
  titles: { fr: "Au lecteur" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Au_lecteur",
  },
  segments: [
    { id: 0, fr: "La sottise, l’erreur, le péché, la lésine," },
    { id: 1, fr: "Occupent nos esprits et travaillent nos corps," },
    { id: 2, fr: "Et nous alimentons nos aimables remords," },
    { id: 3, fr: "Comme les mendiants nourrissent leur vermine." },
    { id: 4, fr: "Nos péchés sont têtus, nos repentirs sont lâches ;" },
    { id: 5, fr: "Nous nous faisons payer grassement nos aveux," },
    { id: 6, fr: "Et nous rentrons gaiement dans le chemin bourbeux," },
    { id: 7, fr: "Croyant par de vils pleurs laver toutes nos taches." },
    { id: 8, fr: "Sur l’oreiller du mal c’est Satan Trismégiste" },
    { id: 9, fr: "Qui berce longuement notre esprit enchanté," },
    { id: 10, fr: "Et le riche métal de notre volonté" },
    { id: 11, fr: "Est tout vaporisé par ce savant chimiste." },
    { id: 12, fr: "C’est le Diable qui tient les fils qui nous remuent !" },
    { id: 13, fr: "Aux objets répugnants nous trouvons des appas ;" },
    { id: 14, fr: "Chaque jour vers l’Enfer nous descendons d’un pas," },
    { id: 15, fr: "Sans horreur, à travers des ténèbres qui puent." },
    { id: 16, fr: "Ainsi qu’un débauché pauvre qui baise et mange" },
    { id: 17, fr: "Le sein martyrisé d’une antique catin," },
    { id: 18, fr: "Nous volons au passage un plaisir clandestin" },
    { id: 19, fr: "Que nous pressons bien fort comme une vieille orange." },
    { id: 20, fr: "Serré, fourmillant, comme un million d’helminthes," },
    { id: 21, fr: "Dans nos cerveaux ribote un peuple de Démons," },
    { id: 22, fr: "Et, quand nous respirons, la Mort dans nos poumons" },
    { id: 23, fr: "Descend, fleuve invisible, avec de sourdes plaintes." },
    { id: 24, fr: "Si le viol, le poison, le poignard, l’incendie," },
    { id: 25, fr: "N’ont pas encor brodé de leurs plaisants dessins" },
    { id: 26, fr: "Le canevas banal de nos piteux destins," },
    { id: 27, fr: "C’est que notre âme, hélas ! n’est pas assez hardie." },
    { id: 28, fr: "Mais parmi les chacals, les panthères, les lices," },
    { id: 29, fr: "Les singes, les scorpions, les vautours, les serpents," },
    { id: 30, fr: "Les monstres glapissants, hurlants, grognants, rampants," },
    { id: 31, fr: "Dans la ménagerie infâme de nos vices," },
    { id: 32, fr: "Il en est un plus laid, plus méchant, plus immonde !" },
    { id: 33, fr: "Quoiqu’il ne pousse ni grands gestes ni grands cris," },
    { id: 34, fr: "Il ferait volontiers de la terre un débris" },
    { id: 35, fr: "Et dans un bâillement avalerait le monde ;" },
    { id: 36, fr: "C’est l’Ennui ! — l’œil chargé d’un pleur involontaire," },
    { id: 37, fr: "Il rêve d’échafauds en fumant son houka." },
    { id: 38, fr: "Tu le connais, lecteur, ce monstre délicat," },
    { id: 39, fr: "— Hypocrite lecteur, — mon semblable, — mon frère !" },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};

/* --- Translations by Bravo ---------------------------------------------
   Machine-managed by localhost edit mode (tools/dev-server.mjs). Everything
   from this marker to the end of the file is rewritten wholesale on save.
   Do not hand-edit below this line, and do not append anything after it. */
window.POEMS["au-lecteur"].bravo = {
  "es-bravo": {
    status: "draft",
    title: "",
    lines: [
      "La necedad, el error, el pecado, la avaricia,",
      "Ocupan nuestros espíritus y trabajan nuestros cuerpos,",
      "Y nosotros alimentamos nuestros amables remordimientos,",
      "Como los mendigos alimentas sus alimañas.",
      "Nuestros pecados son persistentes, nuestros arrepentimientos son cobardes;",
      "Hacemos pagar generosamente nuestras confesiones",
      "Y volvemos felizmente en el camino fangoso",
      "Creyente por medio de llantos viles lavar todos nuestros pecados.",
      "Sobre la almohada del mal yace Satán Trismegisto",
      "Que mece largamente nuestro espíritu encantado,",
      "Y el rico metal de nuestra voluntad",
      "Es vaporizado por este sabio químico.",
      "¡Es el Diablo que tienta los hijo que nos agitan",
      "En objetos repugnantes encontramos encantos;",
      "Cada día hacia el infierno descendemos un paso",
      "Sin horror, a través de oscuridades apestosas.",
      "Así que un libertino pobre que folla y come",
      "El seno martirizado de una antigua puta,",
      "Robemos el paso a un placer clandestino",
      "Que nos instan fuertemente como una naranja.",
      "Apretado, bullicioso, como un millón de helmintos,",
      "En nuestros cerebros se ríe un pueblo de Demonios,",
      "Y, cuando respiramos, la Muerte en nuestros pulmones",
      "Desciende, río invisible, con denuncias sordas.",
      "Si la violación, el veneno, la daga, el incendio,",
      "Todavía no han bordado sus agradables diseños",
      "El lienzo banal de nuestros lamentables destinos,",
      "Es que nuestra alma, ¡ay!, no es lo bastante osada.",
      "Pero entre los chacales, las panteras, los piojos,",
      "Los monos, los escorpiones, los buitres, las serpientes,",
      "Los monstruos chillones, aulladores, resoplantes, rastreros,",
      "En la casa de fieras infame de nuestros vicios,",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  },
};
