window.POEMS = window.POEMS || {};

window.POEMS["le-voyage"] = {
  title: "Le Voyage",
  titles: { fr: "Le Voyage", es: "El viaje" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Le_Voyage",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/El_viaje_%28Baudelaire%29",
  },
  segments: [
    { id: 0, fr: "Pour l’enfant, amoureux de cartes et d’estampes,", es: "Para el niño, enamorado de mapas y estampas," },
    { id: 1, fr: "L’univers est égal à son vaste appétit.", es: "El universo es igual a su vasto apetito.",
      wordGroups: [
        { wid: "1-0", fr: "L’univers", es: "universo" },
        { wid: "1-1", fr: "vaste", es: "vasto" },
      ] },
    { id: 2, fr: "Ah ! que le monde est grand à la clarté des lampes !", es: "¡Ah! ¡Cuan grande es el mundo a la claridad de las lámparas!",
      wordGroups: [
        { wid: "2-0", fr: "monde", es: "mundo" },
        { wid: "2-1", fr: "grand", es: "grande" },
        { wid: "2-2", fr: "clarté", es: "claridad" },
      ] },
    { id: 3, fr: "Aux yeux du souvenir que le monde est petit !", es: "¡Para las miradas del recuerdo, el mundo qué pequeño!",
      wordGroups: [
        { wid: "3-0", fr: "souvenir", es: "recuerdo" },
        { wid: "3-1", fr: "monde", es: "mundo" },
        { wid: "3-2", fr: "petit", es: "pequeño" },
      ] },
    { id: 4, fr: "Un matin nous partons, le cerveau plein de flamme,", es: "Una mañana zarpamos, la mente inflamada,",
      wordGroups: [
        { wid: "4-0", fr: "matin", es: "mañana" },
      ] },
    { id: 5, fr: "Le cœur gros de rancune et de désirs amers,", es: "El corazón desbordante de rencor y de amargos deseos,",
      wordGroups: [
        { wid: "5-0", fr: "cœur", es: "corazón" },
        { wid: "5-1", fr: "désirs", es: "deseos" },
        { wid: "5-2", fr: "amers", es: "amargos" },
      ] },
    { id: 6, fr: "Et nous allons, suivant le rhythme de la lame,", es: "Y nos marchamos, siguiendo el ritmo de la onda",
      wordGroups: [
        { wid: "6-0", fr: "suivant", es: "siguiendo" },
        { wid: "6-1", fr: "rhythme", es: "ritmo" },
      ] },
    { id: 7, fr: "Berçant notre infini sur le fini des mers :", es: "Meciendo nuestro infinito sobre el confín de los mares.",
      wordGroups: [
        { wid: "7-0", fr: "infini", es: "infinito" },
        { wid: "7-1", fr: "mers", es: "mares" },
      ] },
    { id: 8, fr: "Les uns, joyeux de fuir une patrie infâme ;", es: "Algunos, dichosos al huir de una patria infame;",
      wordGroups: [
        { wid: "8-0", fr: "fuir", es: "huir" },
        { wid: "8-1", fr: "patrie", es: "patria" },
        { wid: "8-2", fr: "infâme", es: "infame" },
      ] },
    { id: 9, fr: "D’autres, l’horreur de leurs berceaux, et quelques-uns,", es: "Otros, del horror de sus orígenes, y unos contados,",
      wordGroups: [
        { wid: "9-0", fr: "D’autres", es: "Otros" },
      ] },
    { id: 10, fr: "Astrologues noyés dans les yeux d’une femme,", es: "Astrólogos sumergidos en los ojos de una mujer,",
      wordGroups: [
        { wid: "10-0", fr: "Astrologues", es: "Astrólogos" },
        { wid: "10-1", fr: "yeux", es: "ojos" },
        { wid: "10-2", fr: "femme", es: "mujer" },
      ] },
    { id: 11, fr: "La Circé tyrannique aux dangereux parfums.", es: "La Circe tiránica de los peligrosos perfumes.",
      wordGroups: [
        { wid: "11-0", fr: "Circé", es: "Circe" },
        { wid: "11-1", fr: "parfums", es: "perfumes" },
      ] },
    { id: 12, fr: "Pour n’être pas changés en bêtes, ils s’enivrent", es: "Para no convertirse en bestias, se embriagan" },
    { id: 13, fr: "D’espace et de lumière et de cieux embrasés ;", es: "De espacio y de luz, y de cielos incendiados;",
      wordGroups: [
        { wid: "13-0", fr: "lumière", es: "luz" },
        { wid: "13-1", fr: "cieux", es: "cielos" },
      ] },
    { id: 14, fr: "La glace qui les mord, les soleils qui les cuivrent,", es: "El hielo que los muerde, los soles que los broncean,",
      wordGroups: [
        { wid: "14-0", fr: "glace", es: "hielo" },
        { wid: "14-1", fr: "mord", es: "muerde" },
        { wid: "14-2", fr: "soleils", es: "soles" },
      ] },
    { id: 15, fr: "Effacent lentement la marque des baisers.", es: "Borran lentamente la huella de los besos.",
      wordGroups: [
        { wid: "15-0", fr: "lentement", es: "lentamente" },
        { wid: "15-1", fr: "baisers", es: "besos" },
      ] },
    { id: 16, fr: "Mais les vrais voyageurs sont ceux-là seuls qui partent", es: "Pero los verdaderos viajeros son los únicos que parten",
      wordGroups: [
        { wid: "16-0", fr: "vrais", es: "verdaderos" },
        { wid: "16-1", fr: "voyageurs", es: "viajeros" },
        { wid: "16-2", fr: "partent", es: "parten" },
      ] },
    { id: 17, fr: "Pour partir ; cœurs légers, semblables aux ballons,", es: "Por partir; corazones ligeros, semejantes a los globos,",
      wordGroups: [
        { wid: "17-0", fr: "partir", es: "partir" },
        { wid: "17-1", fr: "cœurs", es: "corazones" },
        { wid: "17-2", fr: "semblables", es: "semejantes" },
      ] },
    { id: 18, fr: "De leur fatalité jamais ils ne s’écartent,", es: "De su fatalidad jamás ellos se apartan,",
      wordGroups: [
        { wid: "18-0", fr: "fatalité", es: "fatalidad" },
        { wid: "18-1", fr: "jamais", es: "jamás" },
      ] },
    { id: 19, fr: "Et, sans savoir pourquoi, disent toujours : Allons !", es: "Y, sin saber por qué, dicen siempre: ¡Vamos!",
      wordGroups: [
        { wid: "19-0", fr: "savoir", es: "saber" },
        { wid: "19-1", fr: "disent", es: "dicen" },
        { wid: "19-2", fr: "toujours", es: "siempre" },
        { wid: "19-3", fr: "Allons", es: "Vamos" },
      ] },
    { id: 20, fr: "Ceux-là dont les désirs ont la forme des nues,", es: "¡Son aquellos cuyos deseos tienen forma de nubes,",
      wordGroups: [
        { wid: "20-0", fr: "Ceux", es: "aquellos" },
        { wid: "20-1", fr: "désirs", es: "deseos" },
        { wid: "20-2", fr: "forme", es: "forma" },
        { wid: "20-3", fr: "nues", es: "nubes" },
      ] },
    { id: 21, fr: "Et qui rêvent, ainsi qu’un conscrit le canon,", es: "Y que como el conscripto, sueñan con el cañón,",
      wordGroups: [
        { wid: "21-0", fr: "conscrit", es: "conscripto" },
        { wid: "21-1", fr: "canon", es: "cañón" },
      ] },
    { id: 22, fr: "De vastes voluptés, changeantes, inconnues,", es: "En intensas voluptuosidades, mutables, desconocidas,",
      wordGroups: [
        { wid: "22-0", fr: "voluptés", es: "voluptuosidades" },
        { wid: "22-1", fr: "inconnues", es: "desconocidas" },
      ] },
    { id: 23, fr: "Et dont l’esprit humain n’a jamais su le nom !", es: "Y de las que el espíritu humano jamás ha conocido el nombre!",
      wordGroups: [
        { wid: "23-0", fr: "humain", es: "humano" },
        { wid: "23-1", fr: "jamais", es: "jamás" },
        { wid: "23-2", fr: "nom", es: "nombre" },
      ] },
    { id: 24, fr: "Nous imitons, horreur ! la toupie et la boule", es: "Imitamos ¡horror! al trompo y la pelota",
      wordGroups: [
        { wid: "24-0", fr: "horreur", es: "horror" },
      ] },
    { id: 25, fr: "Dans leur valse et leurs bonds ; même dans nos sommeils", es: "En su danza y sus saltos; hasta en nuestros sueños",
      wordGroups: [
        { wid: "25-0", fr: "bonds", es: "saltos" },
      ] },
    { id: 26, fr: "La Curiosité nous tourmente et nous roule,", es: "La Curiosidad nos atormenta y nos envuelve,",
      wordGroups: [
        { wid: "26-0", fr: "Curiosité", es: "Curiosidad" },
      ] },
    { id: 27, fr: "Comme un Ange cruel qui fouette des soleils.", es: "Como un Ángel cruel que fustigará soles.",
      wordGroups: [
        { wid: "27-0", fr: "Ange", es: "Ángel" },
        { wid: "27-1", fr: "cruel", es: "cruel" },
        { wid: "27-2", fr: "soleils", es: "soles" },
      ] },
    { id: 28, fr: "Singulière fortune où le but se déplace,", es: "¡Singular fortuna en la que el final se desplaza,",
      wordGroups: [
        { wid: "28-0", fr: "fortune", es: "fortuna" },
        { wid: "28-1", fr: "déplace", es: "desplaza" },
      ] },
    { id: 29, fr: "Et, n’étant nulle part, peut être n’importe où !", es: "Y no estando en parte alguna, puede hallarse por doquier!",
      wordGroups: [
        { wid: "29-0", fr: "part", es: "parte" },
        { wid: "29-1", fr: "peut", es: "puede" },
      ] },
    { id: 30, fr: "Où l’Homme, dont jamais l’espérance n’est lasse,", es: "¡Donde el Hombre, que jamás la esperanza abandona,",
      wordGroups: [
        { wid: "30-0", fr: "jamais", es: "jamás" },
      ] },
    { id: 31, fr: "Pour trouver le repos court toujours comme un fou !", es: "Para lograr el reposo corre siempre como un loco!",
      wordGroups: [
        { wid: "31-0", fr: "repos", es: "reposo" },
        { wid: "31-1", fr: "toujours", es: "siempre" },
        { wid: "31-2", fr: "fou", es: "loco" },
      ] },
    { id: 32, fr: "Notre âme est un trois-mâts cherchant son Icarie ;", es: "Nuestra alma es nave de tres palos buscando su Icaria;",
      wordGroups: [
        { wid: "32-0", fr: "âme", es: "alma" },
        { wid: "32-1", fr: "trois", es: "tres" },
        { wid: "32-2", fr: "cherchant", es: "buscando" },
        { wid: "32-3", fr: "Icarie", es: "Icaria" },
      ] },
    { id: 33, fr: "Une voix retentit sur le pont : « Ouvre l’œil ! »", es: "Una voz resuena en el puente: \"¡Atención!\"",
      wordGroups: [
        { wid: "33-0", fr: "voix", es: "voz" },
        { wid: "33-1", fr: "pont", es: "puente" },
      ] },
    { id: 34, fr: "Une voix de la hune, ardente et folle, crie :", es: "Una voz desde la cofa, ardiente y loca, clama:",
      wordGroups: [
        { wid: "34-0", fr: "voix", es: "voz" },
        { wid: "34-1", fr: "ardente", es: "ardiente" },
        { wid: "34-2", fr: "folle", es: "loca" },
      ] },
    { id: 35, fr: "« Amour… gloire… bonheur ! » Enfer ! c’est un écueil !", es: "\"¡Amor...  gloria... felicidad!\" ¡Infierno! ¡Es un escollo!",
      wordGroups: [
        { wid: "35-0", fr: "Amour", es: "Amor" },
        { wid: "35-1", fr: "gloire", es: "gloria" },
        { wid: "35-2", fr: "bonheur", es: "felicidad" },
        { wid: "35-3", fr: "Enfer", es: "Infierno" },
      ] },
    { id: 36, fr: "Chaque îlot signalé par l’homme de vigie", es: "Cada islote señalado por el vigía",
      wordGroups: [
        { wid: "36-0", fr: "Chaque", es: "Cada" },
        { wid: "36-1", fr: "vigie", es: "vigía" },
      ] },
    { id: 37, fr: "Est un Eldorado promis par le Destin ;", es: "Es un El dorado prometido por el Destino;",
      wordGroups: [
        { wid: "37-0", fr: "Eldorado", es: "dorado" },
        { wid: "37-1", fr: "promis", es: "prometido" },
        { wid: "37-2", fr: "Destin", es: "Destino" },
      ] },
    { id: 38, fr: "L’Imagination qui dresse son orgie", es: "La imaginación, que acucia su orgía",
      wordGroups: [
        { wid: "38-0", fr: "L’Imagination", es: "imaginación" },
        { wid: "38-1", fr: "orgie", es: "orgía" },
      ] },
    { id: 39, fr: "Ne trouve qu’un récif aux clartés du matin.", es: "No halla más que un arrecife al amanecer.",
      wordGroups: [
        { wid: "39-0", fr: "trouve", es: "halla" },
      ] },
    { id: 40, fr: "Ô le pauvre amoureux des pays chimériques !", es: "¡Oh, el infeliz enamorado de tierras quiméricas!" },
    { id: 41, fr: "Faut-il le mettre aux fers, le jeter à la mer,", es: "¿Habrá que engrillar y arrojar al mar,",
      wordGroups: [
        { wid: "41-0", fr: "jeter", es: "arrojar" },
        { wid: "41-1", fr: "mer", es: "mar" },
      ] },
    { id: 42, fr: "Ce matelot ivrogne, inventeur d’Amériques", es: "A este marinero borracho, inventor de Américas",
      wordGroups: [
        { wid: "42-0", fr: "ivrogne", es: "borracho" },
        { wid: "42-1", fr: "inventeur", es: "inventor" },
      ] },
    { id: 43, fr: "Dont le mirage rend le gouffre plus amer", es: "Para el cual el espejismo toma el remolino más amargo?",
      wordGroups: [
        { wid: "43-0", fr: "amer", es: "amargo" },
      ] },
    { id: 44, fr: "Tel le vieux vagabond, piétinant dans la boue,", es: "Como el viejo vagabundo, chapaleando en el lodo",
      wordGroups: [
        { wid: "44-0", fr: "vieux", es: "viejo" },
        { wid: "44-1", fr: "vagabond", es: "vagabundo" },
        { wid: "44-2", fr: "boue", es: "lodo" },
      ] },
    { id: 45, fr: "Rêve, le nez en l’air, de brillants paradis ;", es: "Sueña, husmeando en el aire, brillantes paraísos;",
      wordGroups: [
        { wid: "45-0", fr: "Rêve", es: "Sueña" },
        { wid: "45-1", fr: "brillants", es: "brillantes" },
        { wid: "45-2", fr: "paradis", es: "paraísos" },
      ] },
    { id: 46, fr: "Son œil ensorcelé découvre une Capoue", es: "Su mirada hechizada descubre una Capúa",
      wordGroups: [
        { wid: "46-0", fr: "découvre", es: "descubre" },
      ] },
    { id: 47, fr: "Partout où la chandelle illumine un taudis.", es: "En cuanto lugar la candela alumbra un tugurio.",
      wordGroups: [
        { wid: "47-0", fr: "chandelle", es: "candela" },
        { wid: "47-1", fr: "taudis", es: "tugurio" },
      ] },
    { id: 48, fr: "Étonnants voyageurs ! quelles nobles histoires", es: "¡Asombrosos viajeros! ¡Qué nobles relatos",
      wordGroups: [
        { wid: "48-0", fr: "voyageurs", es: "viajeros" },
        { wid: "48-1", fr: "nobles", es: "nobles" },
      ] },
    { id: 49, fr: "Nous lisons dans vos yeux profonds comme les mers !", es: "Leemos en vuestros ojos profundos como los mares!",
      wordGroups: [
        { wid: "49-0", fr: "yeux", es: "ojos" },
        { wid: "49-1", fr: "profonds", es: "profundos" },
        { wid: "49-2", fr: "mers", es: "mares" },
      ] },
    { id: 50, fr: "Montrez-nous les écrins de vos riches mémoires,", es: "Mostradnos los joyeros de vuestras ricas memorias," },
    { id: 51, fr: "Ces bijoux merveilleux, faits d’astres et d’éthers.", es: "Esas alhajas maravillosas, hechas de astros y de éter." },
    { id: 52, fr: "Nous voulons voyager sans vapeur et sans voile !", es: "¡Deseamos viajar sin vapor y sin velas!",
      wordGroups: [
        { wid: "52-0", fr: "vapeur", es: "vapor" },
      ] },
    { id: 53, fr: "Faites, pour égayer l’ennui de nos prisons,", es: "Para ahuyentar el tedio de nuestras prisiones,",
      wordGroups: [
        { wid: "53-0", fr: "prisons", es: "prisiones" },
      ] },
    { id: 54, fr: "Passer sur nos esprits, tendus comme une toile,", es: "Haced desfilar nuestros espíritus, tensos como un lienzo,",
      wordGroups: [
        { wid: "54-0", fr: "esprits", es: "espíritus" },
      ] },
    { id: 55, fr: "Vos souvenirs avec leurs cadres d’horizons.", es: "Vuestros recuerdos enmarcados por horizontes.",
      wordGroups: [
        { wid: "55-0", fr: "souvenirs", es: "recuerdos" },
      ] },
    { id: 56, fr: "Dites, qu’avez-vous vu ?", es: "Decid, ¿qué habéis visto?" },
    { id: 57, fr: "Dites, qu’avez-vous vu ? « Nous avons vu des astres", es: "\"Hemos visto astros",
      wordGroups: [
        { wid: "57-0", fr: "astres", es: "astros" },
      ] },
    { id: 58, fr: "Et des flots ; nous avons vu des sables aussi ;", es: "Y olas; hemos visto playas además;",
      wordGroups: [
        { wid: "58-0", fr: "flots", es: "olas" },
      ] },
    { id: 59, fr: "Et, malgré bien des chocs et d’imprévus désastres,", es: "Y, malgrado muchos choques e imprevistos desastres,",
      wordGroups: [
        { wid: "59-0", fr: "malgré", es: "malgrado" },
        { wid: "59-1", fr: "chocs", es: "choques" },
        { wid: "59-2", fr: "désastres", es: "desastres" },
      ] },
    { id: 60, fr: "Nous nous sommes souvent ennuyés, comme ici.", es: "Nos hemos hastiado, a menudo, como aquí.",
      wordGroups: [
        { wid: "60-0", fr: "ici", es: "aquí" },
      ] },
    { id: 61, fr: "La gloire du soleil sur la mer violette,", es: "El esplendor del sol sobre el mar violáceo,",
      wordGroups: [
        { wid: "61-0", fr: "soleil", es: "sol" },
        { wid: "61-1", fr: "mer", es: "mar" },
      ] },
    { id: 62, fr: "La gloire des cités dans le soleil couchant,", es: "El esplendor de las ciudades en el sol poniente,",
      wordGroups: [
        { wid: "62-0", fr: "cités", es: "ciudades" },
        { wid: "62-1", fr: "soleil", es: "sol" },
      ] },
    { id: 63, fr: "Allumaient dans nos cœurs une ardeur inquiète", es: "Encendían en nuestros corazones el impulso inquietante",
      wordGroups: [
        { wid: "63-0", fr: "cœurs", es: "corazones" },
      ] },
    { id: 64, fr: "De plonger dans un ciel au reflet alléchant.", es: "De sumergirnos en el cielo con su reflejo fascinante.",
      wordGroups: [
        { wid: "64-0", fr: "ciel", es: "cielo" },
      ] },
    { id: 65, fr: "Les plus riches cités, les plus grands paysages,", es: "Las más ricas ciudades, los más amplios paisajes,",
      wordGroups: [
        { wid: "65-0", fr: "cités", es: "ciudades" },
        { wid: "65-1", fr: "paysages", es: "paisajes" },
      ] },
    { id: 66, fr: "Jamais ne contenaient l’attrait mystérieux", es: "Jamás contenían el atractivo misterioso",
      wordGroups: [
        { wid: "66-0", fr: "Jamais", es: "Jamás" },
        { wid: "66-1", fr: "mystérieux", es: "misterioso" },
      ] },
    { id: 67, fr: "De ceux que le hasard fait avec les nuages,", es: "De aquellos que el azar forma con las nubes.",
      wordGroups: [
        { wid: "67-0", fr: "ceux", es: "aquellos" },
        { wid: "67-1", fr: "hasard", es: "azar" },
        { wid: "67-2", fr: "nuages", es: "nubes" },
      ] },
    { id: 68, fr: "Et toujours le désir nous rendait soucieux !", es: "¡Y siempre el deseo nos tornaba inquietos!",
      wordGroups: [
        { wid: "68-0", fr: "toujours", es: "siempre" },
        { wid: "68-1", fr: "désir", es: "deseo" },
      ] },
    { id: 69, fr: "— La jouissance ajoute au désir de la force.", es: "—El gozo acrecienta del deseo la fuerza.",
      wordGroups: [
        { wid: "69-0", fr: "désir", es: "deseo" },
        { wid: "69-1", fr: "force", es: "fuerza" },
      ] },
    { id: 70, fr: "Désir, vieil arbre à qui le plaisir sert d’engrais,", es: "¡Deseo, viejo árbol, al cual el placer sirviéndole de abono,",
      wordGroups: [
        { wid: "70-0", fr: "Désir", es: "Deseo" },
        { wid: "70-1", fr: "arbre", es: "árbol" },
        { wid: "70-2", fr: "plaisir", es: "placer" },
      ] },
    { id: 71, fr: "Cependant que grossit et durcit ton écorce,", es: "Entretanto acrecienta y endurece tu corteza," },
    { id: 72, fr: "Tes branches veulent voir le soleil de plus près !", es: "Tus ramas quieren ver el sol de más cerca!",
      wordGroups: [
        { wid: "72-0", fr: "branches", es: "ramas" },
        { wid: "72-1", fr: "voir", es: "ver" },
        { wid: "72-2", fr: "soleil", es: "sol" },
      ] },
    { id: 73, fr: "Grandiras-tu toujours, grand arbre plus vivace", es: "¿Crecerás siempre, gran árbol, más vivaz",
      wordGroups: [
        { wid: "73-0", fr: "toujours", es: "siempre" },
        { wid: "73-1", fr: "grand", es: "gran" },
        { wid: "73-2", fr: "arbre", es: "árbol" },
      ] },
    { id: 74, fr: "Que le cyprès ? — Pourtant nous avons, avec soin,", es: "Que el ciprés? —Sin embargo, nosotros, con cuidado,",
      wordGroups: [
        { wid: "74-0", fr: "cyprès", es: "ciprés" },
      ] },
    { id: 75, fr: "Cueilli quelques croquis pour votre album vorace,", es: "Recogimos algunos croquis para vuestro álbum voraz,",
      wordGroups: [
        { wid: "75-0", fr: "croquis", es: "croquis" },
        { wid: "75-1", fr: "album", es: "álbum" },
      ] },
    { id: 76, fr: "Frères qui trouvez beau tout ce qui vient de loin !", es: "¡Hermanos que encontráis bello todo cuanto viene de lejos!",
      wordGroups: [
        { wid: "76-0", fr: "Frères", es: "Hermanos" },
        { wid: "76-1", fr: "beau", es: "bello" },
        { wid: "76-2", fr: "vient", es: "viene" },
        { wid: "76-3", fr: "loin", es: "lejos" },
      ] },
    { id: 77, fr: "Nous avons salué des idoles à trompe ;", es: "Hemos saludado ídolos engañosos;",
      wordGroups: [
        { wid: "77-0", fr: "idoles", es: "ídolos" },
      ] },
    { id: 78, fr: "Des trônes constellés de joyaux lumineux ;", es: "Tronos constelados de joyas luminosas;",
      wordGroups: [
        { wid: "78-0", fr: "trônes", es: "Tronos" },
        { wid: "78-1", fr: "joyaux", es: "joyas" },
        { wid: "78-2", fr: "lumineux", es: "luminosas" },
      ] },
    { id: 79, fr: "Des palais ouvragés dont la féerique pompe", es: "Palacios adornados cuya feérica pompa",
      wordGroups: [
        { wid: "79-0", fr: "palais", es: "Palacios" },
        { wid: "79-1", fr: "pompe", es: "pompa" },
      ] },
    { id: 80, fr: "Serait pour vos banquiers un rêve ruineux ;", es: "Sería para vuestros banqueros un sueño ruinoso;",
      wordGroups: [
        { wid: "80-0", fr: "banquiers", es: "banqueros" },
        { wid: "80-1", fr: "rêve", es: "sueño" },
        { wid: "80-2", fr: "ruineux", es: "ruinoso" },
      ] },
    { id: 81, fr: "Des costumes qui sont pour les yeux une ivresse ;", es: "Vestimentas que son para la vista una embriaguez;",
      wordGroups: [
        { wid: "81-0", fr: "ivresse", es: "embriaguez" },
      ] },
    { id: 82, fr: "Des femmes dont les dents et les ongles sont teints,", es: "Mujeres cuyos dientes y las uñas están pintados,",
      wordGroups: [
        { wid: "82-0", fr: "femmes", es: "Mujeres" },
        { wid: "82-1", fr: "dents", es: "dientes" },
      ] },
    { id: 83, fr: "Et des jongleurs savants que le serpent caresse. »", es: "Y juglares sabios que la serpiente acaricia.\"",
      wordGroups: [
        { wid: "83-0", fr: "savants", es: "sabios" },
        { wid: "83-1", fr: "serpent", es: "serpiente" },
        { wid: "83-2", fr: "caresse", es: "acaricia" },
      ] },
    { id: 84, fr: "Et puis, et puis encore ?", es: "Y después, y después. ¿Todavía, qué más?",
      wordGroups: [
        { wid: "84-0", fr: "encore", es: "Todavía" },
      ] },
    { id: 85, fr: "Et puis, et puis encore ? « Ô cerveaux enfantins !", es: "\"¡Oh, cerebros infantiles!\"",
      wordGroups: [
        { wid: "85-0", fr: "cerveaux", es: "cerebros" },
      ] },
    { id: 86, fr: "Pour ne pas oublier la chose capitale,", es: "Para no olvidar el tema capital,",
      wordGroups: [
        { wid: "86-0", fr: "oublier", es: "olvidar" },
        { wid: "86-1", fr: "capitale", es: "capital" },
      ] },
    { id: 87, fr: "Nous avons vu partout, et sans l’avoir cherché,", es: "Hemos visto en todas partes, y sin haberlo buscado,",
      wordGroups: [
        { wid: "87-0", fr: "partout", es: "partes" },
      ] },
    { id: 88, fr: "Du haut jusques en bas de l’échelle fatale,", es: "Desde arriba hasta abajo la escala fatal,",
      wordGroups: [
        { wid: "88-0", fr: "fatale", es: "fatal" },
      ] },
    { id: 89, fr: "Le spectacle ennuyeux de l’immortel péché :", es: "El espectáculo enojoso del inmortal pecado:",
      wordGroups: [
        { wid: "89-0", fr: "spectacle", es: "espectáculo" },
        { wid: "89-1", fr: "péché", es: "pecado" },
      ] },
    { id: 90, fr: "La femme, esclave vile, orgueilleuse et stupide,", es: "La mujer, esclava vil, orgullosa y estúpida,",
      wordGroups: [
        { wid: "90-0", fr: "femme", es: "mujer" },
        { wid: "90-1", fr: "esclave", es: "esclava" },
        { wid: "90-2", fr: "vile", es: "vil" },
        { wid: "90-3", fr: "stupide", es: "estúpida" },
      ] },
    { id: 91, fr: "Sans rire s’adorant et s’aimant sans dégoût ;", es: "Sin reír extasiándose y adorándose sin repugnancia;",
      wordGroups: [
        { wid: "91-0", fr: "rire", es: "reír" },
      ] },
    { id: 92, fr: "L’homme, tyran goulu, paillard, dur et cupide,", es: "El hombre, tirano goloso, lascivo, duro y ávido,",
      wordGroups: [
        { wid: "92-0", fr: "tyran", es: "tirano" },
        { wid: "92-1", fr: "dur", es: "duro" },
      ] },
    { id: 93, fr: "Esclave de l’esclave et ruisseau dans l’égout ;", es: "Esclavo de la esclava y arroyo en la cloaca;",
      wordGroups: [
        { wid: "93-0", fr: "Esclave", es: "Esclavo" },
        { wid: "93-1", fr: "ruisseau", es: "arroyo" },
      ] },
    { id: 94, fr: "Le bourreau qui jouit, le martyr qui sanglote ;", es: "El verdugo que goza, el mártir que solloza;",
      wordGroups: [
        { wid: "94-0", fr: "bourreau", es: "verdugo" },
        { wid: "94-1", fr: "jouit", es: "goza" },
        { wid: "94-2", fr: "martyr", es: "mártir" },
      ] },
    { id: 95, fr: "La fête qu’assaisonne et parfume le sang ;", es: "La fiesta que sazona y perfuma la sangre;",
      wordGroups: [
        { wid: "95-0", fr: "fête", es: "fiesta" },
        { wid: "95-1", fr: "sang", es: "sangre" },
      ] },
    { id: 96, fr: "Le poison du pouvoir énervant le despote,", es: "El veneno del poder enervando al déspota,",
      wordGroups: [
        { wid: "96-0", fr: "poison", es: "veneno" },
        { wid: "96-1", fr: "pouvoir", es: "poder" },
        { wid: "96-2", fr: "énervant", es: "enervando" },
        { wid: "96-3", fr: "despote", es: "déspota" },
      ] },
    { id: 97, fr: "Et le peuple amoureux du fouet abrutissant ;", es: "Y el pueblo amoroso del látigo embrutecedor;",
      wordGroups: [
        { wid: "97-0", fr: "peuple", es: "pueblo" },
        { wid: "97-1", fr: "amoureux", es: "amoroso" },
      ] },
    { id: 98, fr: "Plusieurs religions semblables à la nôtre,", es: "Muchas religiones semejantes a la nuestra,",
      wordGroups: [
        { wid: "98-0", fr: "religions", es: "religiones" },
        { wid: "98-1", fr: "semblables", es: "semejantes" },
      ] },
    { id: 99, fr: "Toutes escaladant le ciel ; la Sainteté,", es: "Todas escalando el cielo; la Santidad,",
      wordGroups: [
        { wid: "99-0", fr: "ciel", es: "cielo" },
        { wid: "99-1", fr: "Sainteté", es: "Santidad" },
      ] },
    { id: 100, fr: "Comme en un lit de plume un délicat se vautre,", es: "Cual un lecho de plumas donde un refinado se revuelca,",
      wordGroups: [
        { wid: "100-0", fr: "lit", es: "lecho" },
      ] },
    { id: 101, fr: "Dans les clous et le crin cherchant la volupté ;", es: "En los clavos y la cerda, buscando la voluptuosidad;",
      wordGroups: [
        { wid: "101-0", fr: "clous", es: "clavos" },
        { wid: "101-1", fr: "cherchant", es: "buscando" },
        { wid: "101-2", fr: "volupté", es: "voluptuosidad" },
      ] },
    { id: 102, fr: "L’Humanité bavarde, ivre de son génie,", es: "La Humanidad habladora, ebria de su genialidad,",
      wordGroups: [
        { wid: "102-0", fr: "L’Humanité", es: "Humanidad" },
      ] },
    { id: 103, fr: "Et, folle maintenant comme elle était jadis,", es: "Y enloquecida, hoy como lo estaba ayer,",
      wordGroups: [
        { wid: "103-0", fr: "était", es: "estaba" },
      ] },
    { id: 104, fr: "Criant à Dieu, dans sa furibonde agonie :", es: "Clamando a Dios, en su furibunda agonía:",
      wordGroups: [
        { wid: "104-0", fr: "Criant", es: "Clamando" },
        { wid: "104-1", fr: "Dieu", es: "Dios" },
        { wid: "104-2", fr: "furibonde", es: "furibunda" },
        { wid: "104-3", fr: "agonie", es: "agonía" },
      ] },
    { id: 105, fr: "« Ô mon semblable, ô mon maître, je te maudis ! »", es: "\"¡Oh, mi semejante, oh mi señor, yo te maldigo!\"",
      wordGroups: [
        { wid: "105-0", fr: "semblable", es: "semejante" },
      ] },
    { id: 106, fr: "Et les moins sots, hardis amants de la Démence,", es: "Y los menos necios, atrevidos amantes de la Demencia,",
      wordGroups: [
        { wid: "106-0", fr: "amants", es: "amantes" },
        { wid: "106-1", fr: "Démence", es: "Demencia" },
      ] },
    { id: 107, fr: "Fuyant le grand troupeau parqué par le Destin,", es: "Huyendo del gran rebaño acorralado por el Destino,",
      wordGroups: [
        { wid: "107-0", fr: "grand", es: "gran" },
        { wid: "107-1", fr: "troupeau", es: "rebaño" },
        { wid: "107-2", fr: "Destin", es: "Destino" },
      ] },
    { id: 108, fr: "Et se réfugiant dans l’opium immense !", es: "Refugiándose en el opio inconmensurable!" },
    { id: 109, fr: "— Tel est du globe entier l’éternel bulletin. »", es: "—Tal es del globo entero el eterno boletín.\"",
      wordGroups: [
        { wid: "109-0", fr: "Tel", es: "Tal" },
        { wid: "109-1", fr: "globe", es: "globo" },
        { wid: "109-2", fr: "entier", es: "entero" },
        { wid: "109-3", fr: "bulletin", es: "boletín" },
      ] },
    { id: 110, fr: "Amer savoir, celui qu’on tire du voyage !", es: "¡Amargo sabor, aquel que se extrae del viaje!",
      wordGroups: [
        { wid: "110-0", fr: "Amer", es: "Amargo" },
        { wid: "110-1", fr: "voyage", es: "viaje" },
      ] },
    { id: 111, fr: "Le monde, monotone et petit, aujourd’hui,", es: "El mundo, monótono y pequeño, en el presente,",
      wordGroups: [
        { wid: "111-0", fr: "monde", es: "mundo" },
        { wid: "111-1", fr: "monotone", es: "monótono" },
        { wid: "111-2", fr: "petit", es: "pequeño" },
      ] },
    { id: 112, fr: "Hier, demain, toujours, nous fait voir notre image :", es: "Ayer, mañana, siempre, nos hace ver nuestra imagen;",
      wordGroups: [
        { wid: "112-0", fr: "Hier", es: "Ayer" },
        { wid: "112-1", fr: "toujours", es: "siempre" },
        { wid: "112-2", fr: "fait", es: "hace" },
        { wid: "112-3", fr: "voir", es: "ver" },
        { wid: "112-4", fr: "image", es: "imagen" },
      ] },
    { id: 113, fr: "Une oasis d’horreur dans un désert d’ennui !", es: "Un oasis de horror en un desierto de tedio!",
      wordGroups: [
        { wid: "113-0", fr: "oasis", es: "oasis" },
        { wid: "113-1", fr: "désert", es: "desierto" },
      ] },
    { id: 114, fr: "Faut-il partir ? rester ? Si tu peux rester, reste ;", es: "¿Es menester partir? ¿Quedarse? Si te puedes quedar, quédate;",
      wordGroups: [
        { wid: "114-0", fr: "Faut", es: "menester" },
        { wid: "114-1", fr: "partir", es: "partir" },
      ] },
    { id: 115, fr: "Pars, s’il le faut. L’un court, et l’autre se tapit", es: "Parte, si es menester. Uno corre, el otro se oculta",
      wordGroups: [
        { wid: "115-0", fr: "faut", es: "menester" },
      ] },
    { id: 116, fr: "Pour tromper l’ennemi vigilant et funeste,", es: "Para engañar ese enemigo vigilante y funesto,",
      wordGroups: [
        { wid: "116-0", fr: "vigilant", es: "vigilante" },
        { wid: "116-1", fr: "funeste", es: "funesto" },
      ] },
    { id: 117, fr: "Le Temps ! Il est, hélas ! des coureurs sans répit,", es: "¡El Tiempo! El pertenece, a los corredores sin respiro,",
      wordGroups: [
        { wid: "117-0", fr: "Temps", es: "Tiempo" },
      ] },
    { id: 118, fr: "Comme le Juif errant et comme les apôtres,", es: "Como el Judío Errante y como los apóstoles,",
      wordGroups: [
        { wid: "118-0", fr: "Juif", es: "Judío" },
        { wid: "118-1", fr: "errant", es: "Errante" },
      ] },
    { id: 119, fr: "À qui rien ne suffit, ni wagon ni vaisseau,", es: "A quien nada basta, ni vagón ni navío,",
      wordGroups: [
        { wid: "119-0", fr: "suffit", es: "basta" },
        { wid: "119-1", fr: "wagon", es: "vagón" },
        { wid: "119-2", fr: "vaisseau", es: "navío" },
      ] },
    { id: 120, fr: "Pour fuir ce rétiaire infâme ; il en est d’autres", es: "Para huir de este retiro infame; y aun hay otros",
      wordGroups: [
        { wid: "120-0", fr: "fuir", es: "huir" },
        { wid: "120-1", fr: "rétiaire", es: "retiro" },
        { wid: "120-2", fr: "infâme", es: "infame" },
        { wid: "120-3", fr: "d’autres", es: "otros" },
      ] },
    { id: 121, fr: "Qui savent le tuer sans quitter leur berceau.", es: "Que saben matarlo sin abandonar su cuna.",
      wordGroups: [
        { wid: "121-0", fr: "savent", es: "saben" },
        { wid: "121-1", fr: "berceau", es: "cuna" },
      ] },
    { id: 122, fr: "Lorsque enfin il mettra le pied sur notre échine,", es: "Cuando, finalmente, él ponga su planta sobre nuestro espinazo,",
      wordGroups: [
        { wid: "122-0", fr: "échine", es: "espinazo" },
      ] },
    { id: 123, fr: "Nous pourrons espérer et crier : En avant !", es: "Podremos esperar y clamar: ¡Adelante!",
      wordGroups: [
        { wid: "123-0", fr: "espérer", es: "esperar" },
      ] },
    { id: 124, fr: "De même qu’autrefois nous partions pour la Chine,", es: "Lo mismo que otras veces, cuando zarpamos para la China,",
      wordGroups: [
        { wid: "124-0", fr: "même", es: "mismo" },
        { wid: "124-1", fr: "Chine", es: "China" },
      ] },
    { id: 125, fr: "Les yeux fixés au large et les cheveux au vent,", es: "Con la mirada hacia lo lejos y los cabellos al viento,",
      wordGroups: [
        { wid: "125-0", fr: "cheveux", es: "cabellos" },
        { wid: "125-1", fr: "vent", es: "viento" },
      ] },
    { id: 126, fr: "Nous nous embarquerons sur la mer des Ténèbres", es: "Nos embarcaremos sobre el mar de las Tinieblas",
      wordGroups: [
        { wid: "126-0", fr: "mer", es: "mar" },
        { wid: "126-1", fr: "Ténèbres", es: "Tinieblas" },
      ] },
    { id: 127, fr: "Avec le cœur joyeux d’un jeune passager.", es: "Con el corazón gozoso del joven pasajero.",
      wordGroups: [
        { wid: "127-0", fr: "cœur", es: "corazón" },
        { wid: "127-1", fr: "joyeux", es: "gozoso" },
        { wid: "127-2", fr: "jeune", es: "joven" },
      ] },
    { id: 128, fr: "Entendez-vous ces voix, charmantes et funèbres,", es: "Escucháis esas voces, embelesadoras y fúnebres,",
      wordGroups: [
        { wid: "128-0", fr: "funèbres", es: "fúnebres" },
      ] },
    { id: 129, fr: "Qui chantent : « Par ici ! vous qui voulez manger", es: "Que cantan: \"¡Por aquí! vosotros que queréis saborear",
      wordGroups: [
        { wid: "129-0", fr: "chantent", es: "cantan" },
        { wid: "129-1", fr: "ici", es: "aquí" },
        { wid: "129-2", fr: "voulez", es: "queréis" },
      ] },
    { id: 130, fr: "Le Lotus parfumé ! c’est ici qu’on vendange", es: "¡El Loto perfumado! Es aquí donde se cosechan",
      wordGroups: [
        { wid: "130-0", fr: "parfumé", es: "perfumado" },
        { wid: "130-1", fr: "ici", es: "aquí" },
      ] },
    { id: 131, fr: "Les fruits miraculeux dont votre cœur a faim ;", es: "Los frutos milagrosos que vuestro corazón apetece;",
      wordGroups: [
        { wid: "131-0", fr: "fruits", es: "frutos" },
        { wid: "131-1", fr: "cœur", es: "corazón" },
      ] },
    { id: 132, fr: "Venez vous enivrer de la douceur étrange", es: "Acudid a embriagaros con la dulzura extraña",
      wordGroups: [
        { wid: "132-0", fr: "douceur", es: "dulzura" },
        { wid: "132-1", fr: "étrange", es: "extraña" },
      ] },
    { id: 133, fr: "De cette après-midi qui n’a jamais de fin ? »", es: "De esta siesta que jamás tiene fin!\"",
      wordGroups: [
        { wid: "133-0", fr: "jamais", es: "jamás" },
        { wid: "133-1", fr: "fin", es: "fin" },
      ] },
    { id: 134, fr: "À l’accent familier nous devinons le spectre ;", es: "Por el acento familiar barruntamos al espectro;",
      wordGroups: [
        { wid: "134-0", fr: "familier", es: "familiar" },
        { wid: "134-1", fr: "spectre", es: "espectro" },
      ] },
    { id: 135, fr: "Nos Pylades là-bas tendent leurs bras vers nous.", es: "Nuestros Pilades, allá, nos tienden sus brazos.",
      wordGroups: [
        { wid: "135-0", fr: "Pylades", es: "Pilades" },
        { wid: "135-1", fr: "bas", es: "allá" },
        { wid: "135-2", fr: "bras", es: "brazos" },
      ] },
    { id: 136, fr: "« Pour rafraîchir ton cœur nage vers ton Électre ! »", es: "\"¡Para refrescar tu corazón boga hacia tu Electra!\"",
      wordGroups: [
        { wid: "136-0", fr: "rafraîchir", es: "refrescar" },
        { wid: "136-1", fr: "cœur", es: "corazón" },
        { wid: "136-2", fr: "Électre", es: "Electra" },
      ] },
    { id: 137, fr: "Dit celle dont jadis nous baisions les genoux.", es: "Dice aquella a la que en otros días besábamos las rodillas.",
      wordGroups: [
        { wid: "137-0", fr: "Dit", es: "Dice" },
        { wid: "137-1", fr: "genoux", es: "rodillas" },
      ] },
    { id: 138, fr: "Ô Mort, vieux capitaine, il est temps ! levons l’ancre !", es: "¡Oh, Muerte, venerable capitana, ya es tiempo! ¡Levemos el ancla!",
      wordGroups: [
        { wid: "138-0", fr: "Mort", es: "Muerte" },
        { wid: "138-1", fr: "capitaine", es: "capitana" },
        { wid: "138-2", fr: "temps", es: "tiempo" },
      ] },
    { id: 139, fr: "Ce pays nous ennuie, ô Mort ! Appareillons !", es: "Esta tierra nos hastía, ¡oh, Muerte! ¡Aparejemos!",
      wordGroups: [
        { wid: "139-0", fr: "Mort", es: "Muerte" },
      ] },
    { id: 140, fr: "Si le ciel et la mer sont noirs comme de l’encre,", es: "¡Si el cielo y la mar están negros como la tinta,",
      wordGroups: [
        { wid: "140-0", fr: "ciel", es: "cielo" },
        { wid: "140-1", fr: "mer", es: "mar" },
        { wid: "140-2", fr: "noirs", es: "negros" },
      ] },
    { id: 141, fr: "Nos cœurs que tu connais sont remplis de rayons !", es: "Nuestros corazones, a los que tú conoces, están radiantes!",
      wordGroups: [
        { wid: "141-0", fr: "cœurs", es: "corazones" },
      ] },
    { id: 142, fr: "Verse-nous ton poison pour qu’il nous réconforte !", es: "¡Viértenos tu veneno para que nos reconforte!",
      wordGroups: [
        { wid: "142-0", fr: "poison", es: "veneno" },
        { wid: "142-1", fr: "réconforte", es: "reconforte" },
      ] },
    { id: 143, fr: "Nous voulons, tant ce feu nous brûle le cerveau,", es: "Este fuego tanto nos abraza el cerebro, que queremos",
      wordGroups: [
        { wid: "143-0", fr: "tant", es: "tanto" },
        { wid: "143-1", fr: "feu", es: "fuego" },
        { wid: "143-2", fr: "cerveau", es: "cerebro" },
      ] },
    { id: 144, fr: "Plonger au fond du gouffre, Enfer ou Ciel, qu’importe ?", es: "Sumergirnos en el fondo del abismo, Infierno o Cielo, ¿qué importa?",
      wordGroups: [
        { wid: "144-0", fr: "fond", es: "fondo" },
        { wid: "144-1", fr: "gouffre", es: "abismo" },
        { wid: "144-2", fr: "Enfer", es: "Infierno" },
        { wid: "144-3", fr: "Ciel", es: "Cielo" },
        { wid: "144-4", fr: "qu’importe", es: "importa" },
      ] },
    { id: 145, fr: "Au fond de l’Inconnu pour trouver du nouveau !", es: "¡Hasta el fondo de lo Desconocido, para encontrar lo nuevo!",
      wordGroups: [
        { wid: "145-0", fr: "fond", es: "fondo" },
        { wid: "145-1", fr: "trouver", es: "encontrar" },
        { wid: "145-2", fr: "nouveau", es: "nuevo" },
      ] },
  ],
  blocks: [
    { type: 'part', label: "I" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'part', label: "II" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'part', label: "III" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 1 },
    { type: 'part', label: "IV" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 1 },
    { type: 'part', label: "V" },
    { type: 'part', label: "VI" },
    { type: 'stanza', lines: 1 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'part', label: "VII" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'part', label: "VIII" },
    { type: 'stanza', lines: 4 },
  ],
};
