window.POEMS = window.POEMS || {};

window.POEMS["danse-macabre"] = {
  title: "Danse macabre",
  titles: { fr: "Danse macabre", es: "Danza macabra" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Danse_macabre",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Danza_macabra",
  },
  segments: [
    { id: 0, fr: "Fière, autant qu’un vivant, de sa noble stature,", es: "Como un viviente, arrogante de su noble estatura,",
      wordGroups: [
        { wid: "0-0", fr: "vivant", es: "viviente" },
        { wid: "0-1", fr: "noble", es: "noble" },
        { wid: "0-2", fr: "stature", es: "estatura" },
      ] },
    { id: 1, fr: "Avec son gros bouquet, son mouchoir et ses gants,", es: "Con su gran ramillete, su pañuelo y sus guantes,",
      wordGroups: [
        { wid: "1-0", fr: "mouchoir", es: "pañuelo" },
      ] },
    { id: 2, fr: "Elle a la nonchalance et la désinvolture", es: "Ella tiene la indolencia y la desenvoltura",
      wordGroups: [
        { wid: "2-0", fr: "désinvolture", es: "desenvoltura" },
      ] },
    { id: 3, fr: "D’une coquette maigre aux airs extravagants.", es: "De una coqueta flaca de porte extravagante.",
      wordGroups: [
        { wid: "3-0", fr: "coquette", es: "coqueta" },
        { wid: "3-1", fr: "maigre", es: "flaca" },
        { wid: "3-2", fr: "extravagants", es: "extravagante" },
      ] },
    { id: 4, fr: "Vit-on jamais au bal une taille plus mince ?", es: "¿Se vio alguna vez en el baile un talle más delgado?",
      wordGroups: [
        { wid: "4-0", fr: "taille", es: "talle" },
        { wid: "4-1", fr: "mince", es: "delgado" },
      ] },
    { id: 5, fr: "Sa robe exagérée, en sa royale ampleur,", es: "Su vestido exagerado, en su real amplitud,",
      wordGroups: [
        { wid: "5-0", fr: "robe", es: "vestido" },
        { wid: "5-1", fr: "exagérée", es: "exagerado" },
        { wid: "5-2", fr: "royale", es: "real" },
      ] },
    { id: 6, fr: "S’écroule abondamment sur un pied sec que pince", es: "Se vuelca abundantemente sobre un pie seco que oprime",
      wordGroups: [
        { wid: "6-0", fr: "pied", es: "pie" },
        { wid: "6-1", fr: "sec", es: "seco" },
      ] },
    { id: 7, fr: "Un soulier pomponné, joli comme une fleur.", es: "Un zapato adornado, bello cual una flor.",
      wordGroups: [
        { wid: "7-0", fr: "soulier", es: "zapato" },
        { wid: "7-1", fr: "fleur", es: "flor" },
      ] },
    { id: 8, fr: "La ruche qui se joue au bord des clavicules,", es: "El frunce que juega al borde de las clavículas,",
      wordGroups: [
        { wid: "8-0", fr: "bord", es: "borde" },
        { wid: "8-1", fr: "clavicules", es: "clavículas" },
      ] },
    { id: 9, fr: "Comme un ruisseau lascif qui se frotte au rocher,", es: "Cual arroyo lascivo frotándose en el peñasco,",
      wordGroups: [
        { wid: "9-0", fr: "ruisseau", es: "arroyo" },
      ] },
    { id: 10, fr: "Défend pudiquement des lazzi ridicules", es: "Defiende púdicamente de las chanzas ridículas",
      wordGroups: [
        { wid: "10-0", fr: "Défend", es: "Defiende" },
        { wid: "10-1", fr: "ridicules", es: "ridículas" },
      ] },
    { id: 11, fr: "Les funèbres appas qu’elle tient à cacher.", es: "Los fúnebres encantos que ella sabe ocultar,",
      wordGroups: [
        { wid: "11-0", fr: "funèbres", es: "fúnebres" },
        { wid: "11-1", fr: "cacher", es: "ocultar" },
      ] },
    { id: 12, fr: "Ses yeux profonds sont faits de vide et de ténèbres,", es: "Sus ojos profundos están hechos de vacío y de tinieblas,",
      wordGroups: [
        { wid: "12-0", fr: "yeux", es: "ojos" },
        { wid: "12-1", fr: "profonds", es: "profundos" },
        { wid: "12-2", fr: "faits", es: "hechos" },
        { wid: "12-3", fr: "vide", es: "vacío" },
        { wid: "12-4", fr: "ténèbres", es: "tinieblas" },
      ] },
    { id: 13, fr: "Et son crâne, de fleurs artistement coiffé,", es: "Y su cráneo, con flores artísticamente peinado,",
      wordGroups: [
        { wid: "13-0", fr: "crâne", es: "cráneo" },
        { wid: "13-1", fr: "fleurs", es: "flores" },
      ] },
    { id: 14, fr: "Oscille mollement sur ses frêles vertèbres.", es: "Oscila lánguidamente sobre sus frágiles vértebras,",
      wordGroups: [
        { wid: "14-0", fr: "frêles", es: "frágiles" },
        { wid: "14-1", fr: "vertèbres", es: "vértebras" },
      ] },
    { id: 15, fr: "Ô charme d’un néant follement attifé !", es: "¡Oh, encanto de un fantasma locamente emperifollado!",
      wordGroups: [
        { wid: "15-0", fr: "charme", es: "encanto" },
      ] },
    { id: 16, fr: "Aucuns t’appelleront une caricature,", es: "Algunos te tomarán por una caricatura,",
      wordGroups: [
        { wid: "16-0", fr: "caricature", es: "caricatura" },
      ] },
    { id: 17, fr: "Qui ne comprennent pas, amants ivres de chair,", es: "Sin comprender, amantes ebrios de carne,",
      wordGroups: [
        { wid: "17-0", fr: "amants", es: "amantes" },
        { wid: "17-1", fr: "chair", es: "carne" },
      ] },
    { id: 18, fr: "L’élégance sans nom de l’humaine armature.", es: "La elegancia sin nombre de tu humana armadura.",
      wordGroups: [
        { wid: "18-0", fr: "nom", es: "nombre" },
        { wid: "18-1", fr: "armature", es: "armadura" },
      ] },
    { id: 19, fr: "Tu réponds, grand squelette, à mon goût le plus cher !", es: "¡Tú respondes, gran esqueleto, a mi gusto más caro!",
      wordGroups: [
        { wid: "19-0", fr: "réponds", es: "respondes" },
        { wid: "19-1", fr: "grand", es: "gran" },
        { wid: "19-2", fr: "squelette", es: "esqueleto" },
        { wid: "19-3", fr: "goût", es: "gusto" },
      ] },
    { id: 20, fr: "Viens-tu troubler, avec ta puissante grimace,", es: "¿Vienes a turbar, con tu imponente mueca,",
      wordGroups: [
        { wid: "20-0", fr: "Viens", es: "Vienes" },
        { wid: "20-1", fr: "troubler", es: "turbar" },
        { wid: "20-2", fr: "grimace", es: "mueca" },
      ] },
    { id: 21, fr: "La fête de la Vie ? ou quelque vieux désir,", es: "La fiesta de la Vida? o ¿algún viejo deseo,",
      wordGroups: [
        { wid: "21-0", fr: "fête", es: "fiesta" },
        { wid: "21-1", fr: "Vie", es: "Vida" },
        { wid: "21-2", fr: "vieux", es: "viejo" },
        { wid: "21-3", fr: "désir", es: "deseo" },
      ] },
    { id: 22, fr: "Éperonnant encor ta vivante carcasse,", es: "Acicateando aún tu viviente esqueleto,",
      wordGroups: [
        { wid: "22-0", fr: "vivante", es: "viviente" },
      ] },
    { id: 23, fr: "Te pousse-t-il, crédule, au sabbat du Plaisir ?", es: "Te impulsa, crédula, al aquelarre del Placer?",
      wordGroups: [
        { wid: "23-0", fr: "crédule", es: "crédula" },
        { wid: "23-1", fr: "Plaisir", es: "Placer" },
      ] },
    { id: 24, fr: "Au chant des violons, aux flammes des bougies,", es: "¿Con el cantar de los violines, y las llamas de las bujías,",
      wordGroups: [
        { wid: "24-0", fr: "chant", es: "cantar" },
        { wid: "24-1", fr: "violons", es: "violines" },
        { wid: "24-2", fr: "flammes", es: "llamas" },
        { wid: "24-3", fr: "bougies", es: "bujías" },
      ] },
    { id: 25, fr: "Espères-tu chasser ton cauchemar moqueur,", es: "Esperas expulsar tu pesadilla burlona,",
      wordGroups: [
        { wid: "25-0", fr: "Espères", es: "Esperas" },
        { wid: "25-1", fr: "chasser", es: "expulsar" },
        { wid: "25-2", fr: "cauchemar", es: "pesadilla" },
        { wid: "25-3", fr: "moqueur", es: "burlona" },
      ] },
    { id: 26, fr: "Et viens-tu demander au torrent des orgies", es: "Y vienes a implorar al torrente de las orgías",
      wordGroups: [
        { wid: "26-0", fr: "viens", es: "vienes" },
        { wid: "26-1", fr: "torrent", es: "torrente" },
        { wid: "26-2", fr: "orgies", es: "orgías" },
      ] },
    { id: 27, fr: "De rafraîchir l’enfer allumé dans ton cœur ?", es: "Que refresque el infierno encendido en tu corazón?",
      wordGroups: [
        { wid: "27-0", fr: "cœur", es: "corazón" },
      ] },
    { id: 28, fr: "Inépuisable puits de sottise et de fautes !", es: "¡Inagotable pozo de necedad y de errores!",
      wordGroups: [
        { wid: "28-0", fr: "puits", es: "pozo" },
      ] },
    { id: 29, fr: "De l’antique douleur éternel alambic !", es: "¡Del antiguo dolor eterno alambique!",
      wordGroups: [
        { wid: "29-0", fr: "douleur", es: "dolor" },
        { wid: "29-1", fr: "éternel", es: "eterno" },
      ] },
    { id: 30, fr: "À travers le treillis recourbé de tes côtes", es: "A través del retorcido enrejado de tus costillas",
      wordGroups: [
        { wid: "30-0", fr: "travers", es: "través" },
        { wid: "30-1", fr: "côtes", es: "costillas" },
      ] },
    { id: 31, fr: "Je vois, errant encor, l’insatiable aspic.", es: "Yo veo, todavía errante, el insaciable áspid.",
      wordGroups: [
        { wid: "31-0", fr: "vois", es: "veo" },
        { wid: "31-1", fr: "errant", es: "errante" },
        { wid: "31-2", fr: "encor", es: "todavía" },
        { wid: "31-3", fr: "l’insatiable", es: "insaciable" },
        { wid: "31-4", fr: "aspic", es: "áspid" },
      ] },
    { id: 32, fr: "Pour dire vrai, je crains que ta coquetterie", es: "A la verdad, temo que tu coquetería",
      wordGroups: [
        { wid: "32-0", fr: "coquetterie", es: "coquetería" },
      ] },
    { id: 33, fr: "Ne trouve pas un prix digne de ses efforts ;", es: "No alcance un precio digno de sus esfuerzos;",
      wordGroups: [
        { wid: "33-0", fr: "digne", es: "digno" },
      ] },
    { id: 34, fr: "Qui, de ces cœurs mortels, entend la raillerie ?", es: "¿Quién, entre esos corazones mortales, alcanza la burla?",
      wordGroups: [
        { wid: "34-0", fr: "cœurs", es: "corazones" },
        { wid: "34-1", fr: "mortels", es: "mortales" },
      ] },
    { id: 35, fr: "Les charmes de l’horreur n’enivrent que les forts !", es: "¡Los sortilegios del horror sólo embriagan a los fuertes!" },
    { id: 36, fr: "Le gouffre de tes yeux, plein d’horribles pensées,", es: "El abismo de tus ojos, pleno de horribles pensamientos,",
      wordGroups: [
        { wid: "36-0", fr: "gouffre", es: "abismo" },
        { wid: "36-1", fr: "yeux", es: "ojos" },
        { wid: "36-2", fr: "d’horribles", es: "horribles" },
        { wid: "36-3", fr: "pensées", es: "pensamientos" },
      ] },
    { id: 37, fr: "Exhale le vertige, et les danseurs prudents", es: "Exhala el vértigo, y los bailarines prudentes",
      wordGroups: [
        { wid: "37-0", fr: "Exhale", es: "Exhala" },
        { wid: "37-1", fr: "vertige", es: "vértigo" },
        { wid: "37-2", fr: "danseurs", es: "bailarines" },
        { wid: "37-3", fr: "prudents", es: "prudentes" },
      ] },
    { id: 38, fr: "Ne contempleront pas sans d’amères nausées", es: "No contemplarán sin amargas náuseas",
      wordGroups: [
        { wid: "38-0", fr: "contempleront", es: "contemplarán" },
        { wid: "38-1", fr: "nausées", es: "náuseas" },
      ] },
    { id: 39, fr: "Le sourire éternel de tes trente-deux dents.", es: "La sonrisa eterna de tus treinta y dos dientes.",
      wordGroups: [
        { wid: "39-0", fr: "sourire", es: "sonrisa" },
        { wid: "39-1", fr: "éternel", es: "eterna" },
        { wid: "39-2", fr: "deux", es: "dos" },
        { wid: "39-3", fr: "dents", es: "dientes" },
      ] },
    { id: 40, fr: "Pourtant, qui n’a serré dans ses bras un squelette,", es: "Empero, ¿quién no ha estrechado entre sus brazos un esqueleto,",
      wordGroups: [
        { wid: "40-0", fr: "bras", es: "brazos" },
        { wid: "40-1", fr: "squelette", es: "esqueleto" },
      ] },
    { id: 41, fr: "Et qui ne s’est nourri des choses du tombeau ?", es: "Y quién no se ha nutrido de cosas sepulcrales?",
      wordGroups: [
        { wid: "41-0", fr: "choses", es: "cosas" },
      ] },
    { id: 42, fr: "Qu’importe le parfum, l’habit ou la toilette ?", es: "¿Qué importa el perfume, el vestido o el tocado?",
      wordGroups: [
        { wid: "42-0", fr: "Qu’importe", es: "importa" },
        { wid: "42-1", fr: "parfum", es: "perfume" },
      ] },
    { id: 43, fr: "Qui fait le dégoûté montre qu’il se croit beau.", es: "El que hace ascos demuestra que se cree bello.",
      wordGroups: [
        { wid: "43-0", fr: "fait", es: "hace" },
        { wid: "43-1", fr: "croit", es: "cree" },
        { wid: "43-2", fr: "beau", es: "bello" },
      ] },
    { id: 44, fr: "Bayadère sans nez, irrésistible gouge,", es: "Bayadera sin nariz, irresistible trotona,",
      wordGroups: [
        { wid: "44-0", fr: "Bayadère", es: "Bayadera" },
        { wid: "44-1", fr: "nez", es: "nariz" },
        { wid: "44-2", fr: "irrésistible", es: "irresistible" },
      ] },
    { id: 45, fr: "Dis donc à ces danseurs qui font les offusqués :", es: "Diles, pues, a estos bailarines que se hacen los ofuscados:",
      wordGroups: [
        { wid: "45-0", fr: "danseurs", es: "bailarines" },
      ] },
    { id: 46, fr: "« Fiers mignons, malgré l’art des poudres et du rouge,", es: "\"Arrogantes galanes, pese al arte de los polvos y del colorete,",
      wordGroups: [
        { wid: "46-0", fr: "l’art", es: "arte" },
      ] },
    { id: 47, fr: "Vous sentez tous la mort ! Ô squelettes musqués,", es: "¡Exhaláis todos la muerte! ¡Oh, esqueletos almizclados!",
      wordGroups: [
        { wid: "47-0", fr: "mort", es: "muerte" },
        { wid: "47-1", fr: "squelettes", es: "esqueletos" },
      ] },
    { id: 48, fr: "Antinoüs flétris, dandys à face glabre,", es: "¡Antinos marchitos, dandis de rostro glabre,",
      wordGroups: [
        { wid: "48-0", fr: "Antinoüs", es: "Antinos" },
        { wid: "48-1", fr: "dandys", es: "dandis" },
        { wid: "48-2", fr: "face", es: "rostro" },
        { wid: "48-3", fr: "glabre", es: "glabre" },
      ] },
    { id: 49, fr: "Cadavres vernissés, lovelaces chenus,", es: "Cadáveres barnizados, lovelaces canosos,",
      wordGroups: [
        { wid: "49-0", fr: "Cadavres", es: "Cadáveres" },
        { wid: "49-1", fr: "lovelaces", es: "lovelaces" },
      ] },
    { id: 50, fr: "Le branle universel de la danse macabre", es: "El alboroto universal de la danza macabra",
      wordGroups: [
        { wid: "50-0", fr: "universel", es: "universal" },
        { wid: "50-1", fr: "danse", es: "danza" },
        { wid: "50-2", fr: "macabre", es: "macabra" },
      ] },
    { id: 51, fr: "Vous entraîne en des lieux qui ne sont pas connus !", es: "Os arrastra hacia lugares desconocidos!",
      wordGroups: [
        { wid: "51-0", fr: "lieux", es: "lugares" },
      ] },
    { id: 52, fr: "Des quais froids de la Seine aux bords brûlants du Gange,", es: "Desde los muelles fríos del Sena a los bordes ardientes del Ganges,",
      wordGroups: [
        { wid: "52-0", fr: "quais", es: "muelles" },
        { wid: "52-1", fr: "froids", es: "fríos" },
        { wid: "52-2", fr: "Seine", es: "Sena" },
        { wid: "52-3", fr: "bords", es: "bordes" },
        { wid: "52-4", fr: "Gange", es: "Ganges" },
      ] },
    { id: 53, fr: "Le troupeau mortel saute et se pâme, sans voir", es: "El tropel mortal salta y se pasma, sin ver",
      wordGroups: [
        { wid: "53-0", fr: "troupeau", es: "tropel" },
        { wid: "53-1", fr: "mortel", es: "mortal" },
        { wid: "53-2", fr: "voir", es: "ver" },
      ] },
    { id: 54, fr: "Dans un trou du plafond la trompette de l’Ange", es: "La trompeta del Ángel en un agujero del techo" },
    { id: 55, fr: "Sinistrement béante ainsi qu’un tromblon noir.", es: "Siniestramente boquiabierto cual un negro trabuco.",
      wordGroups: [
        { wid: "55-0", fr: "Sinistrement", es: "Siniestramente" },
        { wid: "55-1", fr: "noir", es: "negro" },
      ] },
    { id: 56, fr: "En tout climat, sous tout soleil, la Mort t’admire", es: "En todo clima, bajo todo sol, la Muerte te admira",
      wordGroups: [
        { wid: "56-0", fr: "climat", es: "clima" },
        { wid: "56-1", fr: "soleil", es: "sol" },
        { wid: "56-2", fr: "Mort", es: "Muerte" },
      ] },
    { id: 57, fr: "En tes contorsions, risible Humanité,", es: "En tus contorsiones, risible Humanidad,",
      wordGroups: [
        { wid: "57-0", fr: "contorsions", es: "contorsiones" },
        { wid: "57-1", fr: "risible", es: "risible" },
        { wid: "57-2", fr: "Humanité", es: "Humanidad" },
      ] },
    { id: 58, fr: "Et souvent, comme toi, se parfumant de myrrhe,", es: "Y a menudo, como tú, perfumándose de mirra,",
      wordGroups: [
        { wid: "58-0", fr: "myrrhe", es: "mirra" },
      ] },
    { id: 59, fr: "Mêle son ironie à ton insanité ! »", es: "Mezcla su ironía a tu insensatez!\"",
      wordGroups: [
        { wid: "59-0", fr: "ironie", es: "ironía" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
