window.POEMS = window.POEMS || {};

window.POEMS["le-cygne"] = {
  title: "Le Cygne",
  titles: { fr: "Le Cygne", es: "El cisne" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Le_Cygne",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/El_cisne",
  },
  segments: [
    { id: 0, fr: "Andromaque, je pense à vous ! Ce petit fleuve,", es: "¡Andrómaca, pienso en ti! Este riacho,",
      wordGroups: [
        { wid: "0-0", fr: "Andromaque", es: "Andrómaca" },
        { wid: "0-1", fr: "pense", es: "pienso" },
      ] },
    { id: 1, fr: "Pauvre et triste miroir où jadis resplendit", es: "Pobre y triste espejo donde antaño resplandeció",
      wordGroups: [
        { wid: "1-0", fr: "Pauvre", es: "Pobre" },
        { wid: "1-1", fr: "triste", es: "triste" },
        { wid: "1-2", fr: "miroir", es: "espejo" },
        { wid: "1-3", fr: "jadis", es: "antaño" },
      ] },
    { id: 2, fr: "L’immense majesté de vos douleurs de veuve,", es: "La inmensa majestad de vuestros dolores de viuda,",
      wordGroups: [
        { wid: "2-0", fr: "majesté", es: "majestad" },
        { wid: "2-1", fr: "douleurs", es: "dolores" },
        { wid: "2-2", fr: "veuve", es: "viuda" },
      ] },
    { id: 3, fr: "Ce Simoïs menteur qui par vos pleurs grandit,", es: "Este Simoïs mentiroso que con vuestras lágrimas crece,",
      wordGroups: [
        { wid: "3-0", fr: "Simoïs", es: "Simoïs" },
        { wid: "3-1", fr: "pleurs", es: "lágrimas" },
      ] },
    { id: 4, fr: "A fécondé soudain ma mémoire fertile,", es: "Ha fecundado de pronto mi memoria fértil,",
      wordGroups: [
        { wid: "4-0", fr: "mémoire", es: "memoria" },
        { wid: "4-1", fr: "fertile", es: "fértil" },
      ] },
    { id: 5, fr: "Comme je traversais le nouveau Carrousel.", es: "Cuando yo atravesaba el nuevo Carrousel.",
      wordGroups: [
        { wid: "5-0", fr: "nouveau", es: "nuevo" },
        { wid: "5-1", fr: "Carrousel", es: "Carrousel" },
      ] },
    { id: 6, fr: "Le vieux Paris n’est plus (la forme d’une ville", es: "El viejo París terminó (la forma de una ciudad",
      wordGroups: [
        { wid: "6-0", fr: "vieux", es: "viejo" },
        { wid: "6-1", fr: "Paris", es: "París" },
        { wid: "6-2", fr: "forme", es: "forma" },
        { wid: "6-3", fr: "ville", es: "ciudad" },
      ] },
    { id: 7, fr: "Change plus vite, hélas ! que le cœur d’un mortel) ;", es: "Cambia más rápido, ¡ah!, que el corazón de un mortal);",
      wordGroups: [
        { wid: "7-0", fr: "Change", es: "Cambia" },
        { wid: "7-1", fr: "cœur", es: "corazón" },
        { wid: "7-2", fr: "mortel", es: "mortal" },
      ] },
    { id: 8, fr: "Je ne vois qu’en esprit tout ce camp de baraques,", es: "Yo no veo sino con el espíritu todo este caserío,",
      wordGroups: [
        { wid: "8-0", fr: "vois", es: "veo" },
        { wid: "8-1", fr: "esprit", es: "espíritu" },
      ] },
    { id: 9, fr: "Ces tas de chapiteaux ébauchés et de fûts,", es: "Este montón de capiteles esbozados y los fustes,",
      wordGroups: [
        { wid: "9-0", fr: "tas", es: "montón" },
      ] },
    { id: 10, fr: "Les herbes, les gros blocs verdis par l’eau des flaques,", es: "Las hierbas, los grandes bloques verdecidos por el agua de las charcas,",
      wordGroups: [
        { wid: "10-0", fr: "herbes", es: "hierbas" },
        { wid: "10-1", fr: "blocs", es: "bloques" },
      ] },
    { id: 11, fr: "Et, brillant aux carreaux, le bric-à-brac confus.", es: "Y brillando en las ventanas, el bric-a-bras confuso.",
      wordGroups: [
        { wid: "11-0", fr: "brillant", es: "brillando" },
        { wid: "11-1", fr: "bric", es: "bric" },
        { wid: "11-2", fr: "brac", es: "bras" },
        { wid: "11-3", fr: "confus", es: "confuso" },
      ] },
    { id: 12, fr: "Là s’étalait jadis une ménagerie ;", es: "Allí se mostraba antaño una casa de fieras;",
      wordGroups: [
        { wid: "12-0", fr: "jadis", es: "antaño" },
      ] },
    { id: 13, fr: "Là je vis, un matin, à l’heure où sous les cieux", es: "Allá yo vi, una mañana, en la hora en que bajo los cielos",
      wordGroups: [
        { wid: "13-0", fr: "matin", es: "mañana" },
        { wid: "13-1", fr: "l’heure", es: "hora" },
        { wid: "13-2", fr: "cieux", es: "cielos" },
      ] },
    { id: 14, fr: "Froids et clairs le Travail s’éveille, où la voirie", es: "Fríos y claros el Trabajo se despierta, en que la basura",
      wordGroups: [
        { wid: "14-0", fr: "Froids", es: "Fríos" },
        { wid: "14-1", fr: "clairs", es: "claros" },
        { wid: "14-2", fr: "Travail", es: "Trabajo" },
      ] },
    { id: 15, fr: "Pousse un sombre ouragan dans l’air silencieux,", es: "Empuja un sombrío huracán en el aire silencioso,",
      wordGroups: [
        { wid: "15-0", fr: "sombre", es: "sombrío" },
        { wid: "15-1", fr: "silencieux", es: "silencioso" },
      ] },
    { id: 16, fr: "Un cygne qui s’était évadé de sa cage,", es: "Un cisne que se había evadido de su jaula,",
      wordGroups: [
        { wid: "16-0", fr: "cygne", es: "cisne" },
      ] },
    { id: 17, fr: "Et, de ses pieds palmés frottant le pavé sec,", es: "Y, con sus patas palmípedas frotando el empedrado seco,",
      wordGroups: [
        { wid: "17-0", fr: "frottant", es: "frotando" },
        { wid: "17-1", fr: "sec", es: "seco" },
      ] },
    { id: 18, fr: "Sur le sol raboteux traînait son blanc plumage.", es: "Sobre el suelo' áspero arrastraba su blanco plumaje.",
      wordGroups: [
        { wid: "18-0", fr: "sol", es: "suelo" },
        { wid: "18-1", fr: "blanc", es: "blanco" },
        { wid: "18-2", fr: "plumage", es: "plumaje" },
      ] },
    { id: 19, fr: "Près d’un ruisseau sans eau la bête ouvrant le bec", es: "Cerca de un arroyo sin agua la bestia abriendo el pico",
      wordGroups: [
        { wid: "19-0", fr: "ruisseau", es: "arroyo" },
        { wid: "19-1", fr: "eau", es: "agua" },
        { wid: "19-2", fr: "bête", es: "bestia" },
        { wid: "19-3", fr: "ouvrant", es: "abriendo" },
        { wid: "19-4", fr: "bec", es: "pico" },
      ] },
    { id: 20, fr: "Baignait nerveusement ses ailes dans la poudre,", es: "Bañaba nerviosamente sus alas en el polvo,",
      wordGroups: [
        { wid: "20-0", fr: "Baignait", es: "Bañaba" },
        { wid: "20-1", fr: "ailes", es: "alas" },
      ] },
    { id: 21, fr: "Et disait, le cœur plein de son beau lac natal :", es: "Y decía, el corazón lleno de su bello lago natal:",
      wordGroups: [
        { wid: "21-0", fr: "cœur", es: "corazón" },
        { wid: "21-1", fr: "plein", es: "lleno" },
        { wid: "21-2", fr: "beau", es: "bello" },
        { wid: "21-3", fr: "lac", es: "lago" },
        { wid: "21-4", fr: "natal", es: "natal" },
      ] },
    { id: 22, fr: "« Eau, quand donc pleuvras-tu ? quand tonneras-tu, foudre ? »", es: "\"Agua, ¿Cuándo lloverás? ¿Cuándo tronarás, rayo?\"",
      wordGroups: [
        { wid: "22-0", fr: "Eau", es: "Agua" },
      ] },
    { id: 23, fr: "Je vois ce malheureux, mythe étrange et fatal,", es: "Yo veo este desdichado, mito extraño y fatal,",
      wordGroups: [
        { wid: "23-0", fr: "vois", es: "veo" },
        { wid: "23-1", fr: "malheureux", es: "desdichado" },
        { wid: "23-2", fr: "étrange", es: "extraño" },
        { wid: "23-3", fr: "fatal", es: "fatal" },
      ] },
    { id: 24, fr: "Vers le ciel quelquefois, comme l’homme d’Ovide,", es: "Hacia el cielo algunas veces, como el hombre de Ovidio,",
      wordGroups: [
        { wid: "24-0", fr: "ciel", es: "cielo" },
      ] },
    { id: 25, fr: "Vers le ciel ironique et cruellement bleu,", es: "Hacia el cielo irónico y cruelmente azul,",
      wordGroups: [
        { wid: "25-0", fr: "ciel", es: "cielo" },
        { wid: "25-1", fr: "ironique", es: "irónico" },
        { wid: "25-2", fr: "bleu", es: "azul" },
      ] },
    { id: 26, fr: "Sur son cou convulsif tendant sa tête avide,", es: "Sobre su cuello convulsivo tender su cabeza ávida,",
      wordGroups: [
        { wid: "26-0", fr: "cou", es: "cuello" },
        { wid: "26-1", fr: "convulsif", es: "convulsivo" },
        { wid: "26-2", fr: "tête", es: "cabeza" },
        { wid: "26-3", fr: "avide", es: "ávida" },
      ] },
    { id: 27, fr: "Comme s’il adressait des reproches à Dieu !", es: "¡Como si dirigiera reproches a Dios!",
      wordGroups: [
        { wid: "27-0", fr: "reproches", es: "reproches" },
        { wid: "27-1", fr: "Dieu", es: "Dios" },
      ] },
    { id: 28, fr: "Paris change ! mais rien dans ma mélancolie", es: "¡París cambia! ¡pero, nada en mi melancolía",
      wordGroups: [
        { wid: "28-0", fr: "Paris", es: "París" },
        { wid: "28-1", fr: "change", es: "cambia" },
        { wid: "28-2", fr: "mélancolie", es: "melancolía" },
      ] },
    { id: 29, fr: "N’a bougé ! palais neufs, échafaudages, blocs,", es: "Se ha movido! palacios nuevos, andamiajes, bloques,",
      wordGroups: [
        { wid: "29-0", fr: "palais", es: "palacios" },
        { wid: "29-1", fr: "blocs", es: "bloques" },
      ] },
    { id: 30, fr: "Vieux faubourgs, tout pour moi devient allégorie,", es: "Viejos arrabales, todo para mí vuélvese alegoría,",
      wordGroups: [
        { wid: "30-0", fr: "Vieux", es: "Viejos" },
        { wid: "30-1", fr: "faubourgs", es: "arrabales" },
        { wid: "30-2", fr: "allégorie", es: "alegoría" },
      ] },
    { id: 31, fr: "Et mes chers souvenirs sont plus lourds que des rocs.", es: "Y mis caros recuerdos son más pesados que rocas.",
      wordGroups: [
        { wid: "31-0", fr: "souvenirs", es: "recuerdos" },
        { wid: "31-1", fr: "lourds", es: "pesados" },
        { wid: "31-2", fr: "rocs", es: "rocas" },
      ] },
    { id: 32, fr: "Aussi devant ce Louvre une image m’opprime :", es: "También ante este Louvre una imagen me oprime:",
      wordGroups: [
        { wid: "32-0", fr: "devant", es: "ante" },
        { wid: "32-1", fr: "Louvre", es: "Louvre" },
        { wid: "32-2", fr: "image", es: "imagen" },
      ] },
    { id: 33, fr: "Je pense à mon grand cygne, avec ses gestes fous,", es: "Y pienso en mi gran cisne, con sus gestos locos,",
      wordGroups: [
        { wid: "33-0", fr: "pense", es: "pienso" },
        { wid: "33-1", fr: "grand", es: "gran" },
        { wid: "33-2", fr: "cygne", es: "cisne" },
        { wid: "33-3", fr: "gestes", es: "gestos" },
        { wid: "33-4", fr: "fous", es: "locos" },
      ] },
    { id: 34, fr: "Comme les exilés, ridicule et sublime,", es: "Como los exiliados, ridículo y sublime,",
      wordGroups: [
        { wid: "34-0", fr: "exilés", es: "exiliados" },
        { wid: "34-1", fr: "ridicule", es: "ridículo" },
        { wid: "34-2", fr: "sublime", es: "sublime" },
      ] },
    { id: 35, fr: "Et rongé d’un désir sans trêve ! et puis à vous,", es: "¡Y roído por un deseo sin tregua! y luego en vos,",
      wordGroups: [
        { wid: "35-0", fr: "désir", es: "deseo" },
        { wid: "35-1", fr: "trêve", es: "tregua" },
      ] },
    { id: 36, fr: "Andromaque, des bras d’un grand époux tombée,", es: "Andrómaca, de los brazos de un gran esposo caída,",
      wordGroups: [
        { wid: "36-0", fr: "Andromaque", es: "Andrómaca" },
        { wid: "36-1", fr: "bras", es: "brazos" },
        { wid: "36-2", fr: "grand", es: "gran" },
        { wid: "36-3", fr: "époux", es: "esposo" },
      ] },
    { id: 37, fr: "Vil bétail, sous la main du superbe Pyrrhus,", es: "Vil rebaño, bajo la mano del soberbio Pirro,",
      wordGroups: [
        { wid: "37-0", fr: "Vil", es: "Vil" },
        { wid: "37-1", fr: "main", es: "mano" },
      ] },
    { id: 38, fr: "Auprès d’un tombeau vide en extase courbée ;", es: "Cabe una tumba vacía en éxtasis doblegado;",
      wordGroups: [
        { wid: "38-0", fr: "tombeau", es: "tumba" },
        { wid: "38-1", fr: "vide", es: "vacía" },
        { wid: "38-2", fr: "extase", es: "éxtasis" },
      ] },
    { id: 39, fr: "Veuve d’Hector, hélas ! et femme d’Hélénus !", es: "Viuda de Héctor, ¡ah! ¡y mujer de Heleno!",
      wordGroups: [
        { wid: "39-0", fr: "Veuve", es: "Viuda" },
        { wid: "39-1", fr: "d’Hector", es: "Héctor" },
        { wid: "39-2", fr: "femme", es: "mujer" },
      ] },
    { id: 40, fr: "Je pense à la négresse, amaigrie et phthisique,", es: "Yo pienso en la negra, enflaquecida y tísica,",
      wordGroups: [
        { wid: "40-0", fr: "pense", es: "pienso" },
      ] },
    { id: 41, fr: "Piétinant dans la boue, et cherchant, l’œil hagard,", es: "Chapaleando en el lodo, y buscando, la mirada huraña,",
      wordGroups: [
        { wid: "41-0", fr: "boue", es: "lodo" },
        { wid: "41-1", fr: "cherchant", es: "buscando" },
      ] },
    { id: 42, fr: "Les cocotiers absents de la superbe Afrique", es: "Los cocoteros ausentes del África soberbia",
      wordGroups: [
        { wid: "42-0", fr: "cocotiers", es: "cocoteros" },
        { wid: "42-1", fr: "absents", es: "ausentes" },
        { wid: "42-2", fr: "superbe", es: "soberbia" },
        { wid: "42-3", fr: "Afrique", es: "África" },
      ] },
    { id: 43, fr: "Derrière la muraille immense du brouillard ;", es: "Detrás de la muralla inmensa de neblina;",
      wordGroups: [
        { wid: "43-0", fr: "Derrière", es: "Detrás" },
        { wid: "43-1", fr: "muraille", es: "muralla" },
        { wid: "43-2", fr: "immense", es: "inmensa" },
      ] },
    { id: 44, fr: "À quiconque a perdu ce qui ne se retrouve", es: "En cualquiera que ha perdido lo que no se encuentra",
      wordGroups: [
        { wid: "44-0", fr: "perdu", es: "perdido" },
      ] },
    { id: 45, fr: "Jamais, jamais ! à ceux qui s’abreuvent de pleurs", es: "¡Jamás, jamás! ¡en los que beben lágrimas!",
      wordGroups: [
        { wid: "45-0", fr: "Jamais", es: "Jamás" },
        { wid: "45-1", fr: "jamais", es: "jamás" },
        { wid: "45-2", fr: "pleurs", es: "lágrimas" },
      ] },
    { id: 46, fr: "Et tettent la Douleur comme une bonne louve !", es: "¡Y maman del Dolor cual de una buena loba!",
      wordGroups: [
        { wid: "46-0", fr: "Douleur", es: "Dolor" },
        { wid: "46-1", fr: "louve", es: "loba" },
      ] },
    { id: 47, fr: "Aux maigres orphelins séchant comme des fleurs !", es: "¡En los flacos huérfanos secándose cual flores!",
      wordGroups: [
        { wid: "47-0", fr: "maigres", es: "flacos" },
        { wid: "47-1", fr: "fleurs", es: "flores" },
      ] },
    { id: 48, fr: "Ainsi dans la forêt où mon esprit s’exile", es: "También en la selva donde mi espíritu se exilia",
      wordGroups: [
        { wid: "48-0", fr: "forêt", es: "selva" },
        { wid: "48-1", fr: "esprit", es: "espíritu" },
      ] },
    { id: 49, fr: "Un vieux Souvenir sonne à plein souffle du cor !", es: "¡Un viejo Recuerdo resuena con la plenitud del cuerno!",
      wordGroups: [
        { wid: "49-0", fr: "vieux", es: "viejo" },
        { wid: "49-1", fr: "Souvenir", es: "Recuerdo" },
      ] },
    { id: 50, fr: "Je pense aux matelots oubliés dans une île,", es: "Pienso en los marineros olvidados en una isla,",
      wordGroups: [
        { wid: "50-0", fr: "pense", es: "Pienso" },
        { wid: "50-1", fr: "île", es: "isla" },
      ] },
    { id: 51, fr: "Aux captifs, aux vaincus !… à bien d’autres encor !", es: "¡En los cautivos, en los vencidos!...  ¡y en muchos otros todavía!",
      wordGroups: [
        { wid: "51-0", fr: "d’autres", es: "otros" },
        { wid: "51-1", fr: "encor", es: "todavía" },
      ] },
  ],
  blocks: [
    { type: 'part', label: "I" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'part', label: "II" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
