window.POEMS = window.POEMS || {};

window.POEMS["abel-et-cain"] = {
  title: "Abel et Caïn",
  titles: { fr: "Abel et Caïn", es: "Abel y Caín" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Abel_et_Ca%C3%AFn",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Abel_y_Ca%C3%ADn",
  },
  segments: [
    { id: 0, fr: "Race d’Abel, dors, bois et mange ;", es: "Raza de Abel, duerme, bebe y come;",
      wordGroups: [
        { wid: "0-0", fr: "Race", es: "Raza" },
        { wid: "0-1", fr: "dors", es: "duerme" },
        { wid: "0-2", fr: "mange", es: "come" },
      ] },
    { id: 1, fr: "Dieu te sourit complaisamment.", es: "Dios te sonríe complaciente.",
      wordGroups: [
        { wid: "1-0", fr: "Dieu", es: "Dios" },
      ] },
    { id: 2, fr: "Race de Caïn, dans la fange", es: "Raza de Caín, en el fango",
      wordGroups: [
        { wid: "2-0", fr: "Race", es: "Raza" },
        { wid: "2-1", fr: "Caïn", es: "Caín" },
        { wid: "2-2", fr: "fange", es: "fango" },
      ] },
    { id: 3, fr: "Rampe et meurs misérablement.", es: "Arrástrate y muere miserablemente.",
      wordGroups: [
        { wid: "3-0", fr: "misérablement", es: "miserablemente" },
      ] },
    { id: 4, fr: "Race d’Abel, ton sacrifice", es: "¡Raza de Abel, tu sacrificio",
      wordGroups: [
        { wid: "4-0", fr: "Race", es: "Raza" },
        { wid: "4-1", fr: "sacrifice", es: "sacrificio" },
      ] },
    { id: 5, fr: "Flatte le nez du Séraphin !", es: "Halaga la nariz de Serafín!",
      wordGroups: [
        { wid: "5-0", fr: "nez", es: "nariz" },
        { wid: "5-1", fr: "Séraphin", es: "Serafín" },
      ] },
    { id: 6, fr: "Race de Caïn, ton supplice", es: "Raza de Caín, tu suplicio,",
      wordGroups: [
        { wid: "6-0", fr: "Race", es: "Raza" },
        { wid: "6-1", fr: "Caïn", es: "Caín" },
        { wid: "6-2", fr: "supplice", es: "suplicio" },
      ] },
    { id: 7, fr: "Aura-t-il jamais une fin ?", es: "¿Tendrá alguna vez fin?",
      wordGroups: [
        { wid: "7-0", fr: "fin", es: "fin" },
      ] },
    { id: 8, fr: "Race d’Abel, vois tes semailles", es: "Raza de Abel, ve tus sembrados",
      wordGroups: [
        { wid: "8-0", fr: "Race", es: "Raza" },
      ] },
    { id: 9, fr: "Et ton bétail venir à bien ;", es: "Y tus ganados crecer;" },
    { id: 10, fr: "Race de Caïn, tes entrailles", es: "Raza de Caín, tus entrañas",
      wordGroups: [
        { wid: "10-0", fr: "Race", es: "Raza" },
        { wid: "10-1", fr: "Caïn", es: "Caín" },
      ] },
    { id: 11, fr: "Hurlent la faim comme un vieux chien.", es: "Aúllan hambrientas como un viejo can.",
      wordGroups: [
        { wid: "11-0", fr: "vieux", es: "viejo" },
      ] },
    { id: 12, fr: "Race d’Abel, chauffe ton ventre", es: "Raza de Abel, calienta tu vientre",
      wordGroups: [
        { wid: "12-0", fr: "Race", es: "Raza" },
        { wid: "12-1", fr: "ventre", es: "vientre" },
      ] },
    { id: 13, fr: "À ton foyer patriarcal ;", es: "En el hogar patriarcal;",
      wordGroups: [
        { wid: "13-0", fr: "foyer", es: "hogar" },
        { wid: "13-1", fr: "patriarcal", es: "patriarcal" },
      ] },
    { id: 14, fr: "Race de Caïn, dans ton antre", es: "Raza de Caín, en tu antro",
      wordGroups: [
        { wid: "14-0", fr: "Race", es: "Raza" },
        { wid: "14-1", fr: "Caïn", es: "Caín" },
        { wid: "14-2", fr: "antre", es: "antro" },
      ] },
    { id: 15, fr: "Tremble de froid, pauvre chacal !", es: "Tiembla de frío, ¡pobre chacal!",
      wordGroups: [
        { wid: "15-0", fr: "Tremble", es: "Tiembla" },
        { wid: "15-1", fr: "froid", es: "frío" },
        { wid: "15-2", fr: "pauvre", es: "pobre" },
        { wid: "15-3", fr: "chacal", es: "chacal" },
      ] },
    { id: 16, fr: "Race d’Abel, aime et pullule !", es: "¡Raza de Abel, ama y pulula!",
      wordGroups: [
        { wid: "16-0", fr: "Race", es: "Raza" },
        { wid: "16-1", fr: "aime", es: "ama" },
      ] },
    { id: 17, fr: "Ton or fait aussi des petits.", es: "Tu oro también procrea." },
    { id: 18, fr: "Race de Caïn, cœur qui brûle,", es: "Raza de Caín, corazón ardiente,",
      wordGroups: [
        { wid: "18-0", fr: "Race", es: "Raza" },
        { wid: "18-1", fr: "Caïn", es: "Caín" },
        { wid: "18-2", fr: "cœur", es: "corazón" },
      ] },
    { id: 19, fr: "Prends garde à ces grands appétits.", es: "Guárdate de esos grandes apetitos.",
      wordGroups: [
        { wid: "19-0", fr: "grands", es: "grandes" },
        { wid: "19-1", fr: "appétits", es: "apetitos" },
      ] },
    { id: 20, fr: "Race d’Abel, tu croîs et broutes", es: "¡Raza de Abel, tú creces y paces",
      wordGroups: [
        { wid: "20-0", fr: "Race", es: "Raza" },
      ] },
    { id: 21, fr: "Comme les punaises des bois !", es: "Como las mariquitas de los bosques!",
      wordGroups: [
        { wid: "21-0", fr: "bois", es: "bosques" },
      ] },
    { id: 22, fr: "Race de Caïn, sur les routes", es: "Raza de Caín, sobre los caminos",
      wordGroups: [
        { wid: "22-0", fr: "Race", es: "Raza" },
        { wid: "22-1", fr: "Caïn", es: "Caín" },
      ] },
    { id: 23, fr: "Traîne ta famille aux abois.", es: "Arrastra tu prole hasta acorralarla.",
      wordGroups: [
        { wid: "23-0", fr: "Traîne", es: "Arrastra" },
      ] },
    { id: 24, fr: "Ah ! race d’Abel, ta charogne", es: "¡Ah, raza de Abel, tu carroña",
      wordGroups: [
        { wid: "24-0", fr: "race", es: "raza" },
        { wid: "24-1", fr: "charogne", es: "carroña" },
      ] },
    { id: 25, fr: "Engraissera le sol fumant !", es: "Abonará el suelo humeante!",
      wordGroups: [
        { wid: "25-0", fr: "sol", es: "suelo" },
      ] },
    { id: 26, fr: "Race de Caïn, ta besogne", es: "Raza de Caín, tu quehacer",
      wordGroups: [
        { wid: "26-0", fr: "Race", es: "Raza" },
        { wid: "26-1", fr: "Caïn", es: "Caín" },
      ] },
    { id: 27, fr: "N’est pas faite suffisamment ;", es: "No se cumple suficientemente;" },
    { id: 28, fr: "Race d’Abel, voici ta honte :", es: "Raza de Abel, he aquí tu vergüenza:",
      wordGroups: [
        { wid: "28-0", fr: "Race", es: "Raza" },
        { wid: "28-1", fr: "voici", es: "aquí" },
        { wid: "28-2", fr: "honte", es: "vergüenza" },
      ] },
    { id: 29, fr: "Le fer est vaincu par l’épieu !", es: "¡El hierro vencido por el venablo!",
      wordGroups: [
        { wid: "29-0", fr: "fer", es: "hierro" },
        { wid: "29-1", fr: "vaincu", es: "vencido" },
      ] },
    { id: 30, fr: "Race de Caïn, au ciel monte,", es: "¡Raza de Caín, al cielo trepa,",
      wordGroups: [
        { wid: "30-0", fr: "Race", es: "Raza" },
        { wid: "30-1", fr: "Caïn", es: "Caín" },
        { wid: "30-2", fr: "ciel", es: "cielo" },
      ] },
    { id: 31, fr: "Et sur la terre jette Dieu !", es: "Y sobre la tierra arroja a Dios!",
      wordGroups: [
        { wid: "31-0", fr: "terre", es: "tierra" },
        { wid: "31-1", fr: "jette", es: "arroja" },
        { wid: "31-2", fr: "Dieu", es: "Dios" },
      ] },
  ],
  blocks: [
    { type: 'part', label: "I" },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'part', label: "II" },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
    { type: 'blank' },
    { type: 'stanza', lines: 2 },
  ],
};
