window.POEMS = window.POEMS || {};

window.POEMS["femmes-damnees"] = {
  title: "Femmes damnées",
  titles: { fr: "Femmes damnées", en: "Condemned Women", es: "Mujeres condenadas" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Comme un bétail pensif sur le sable couchées,", en: "Like thoughtful cattle on the yellow sands reclined,", es: "Como bestias meditabundas sobre la arena tumbadas,",
      wordGroups: [
        { wid: "0-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "0-1", fr: "bétail", en: "cattle", es: "bestias" },
        { wid: "0-2", fr: "pensif", en: "thoughtful", es: "meditabundas" },
        { wid: "0-3", fr: "le sable", en: "sands", es: "la arena" },
        { wid: "0-4", fr: "couchées", en: "reclined", es: "tumbadas" },
      ] },
    { id: 1, fr: "Elles tournent leurs yeux vers l’horizon des mers,", en: "They turn their eyes towards the horizon of the sea,", es: "Ellas vuelven sus miradas hacia el horizonte del mar,",
      wordGroups: [
        { wid: "1-0", fr: "tournent", en: "turn", es: "vuelven" },
        { wid: "1-1", fr: "leurs yeux", en: "their eyes", es: "sus miradas" },
        { wid: "1-2", fr: "vers", en: "towards", es: "hacia" },
        { wid: "1-3", fr: "l’horizon", en: "the horizon", es: "el horizonte" },
        { wid: "1-4", fr: "mers", en: "sea", es: "mar" },
      ] },
    { id: 2, fr: "Et leurs pieds se cherchant et leurs mains rapprochées", en: "Their feet towards each other stretched, their hands entwined,", es: "Y sus pies se buscan y sus manos entrelazadas",
      wordGroups: [
        { wid: "2-0", fr: "leurs pieds", en: "Their feet", es: "sus pies" },
        { wid: "2-1", fr: "se cherchant", en: "towards each other stretched", es: "se buscan" },
        { wid: "2-2", fr: "leurs mains", en: "their hands", es: "sus manos" },
        { wid: "2-3", fr: "rapprochées", en: "entwined", es: "entrelazadas" },
      ] },
    { id: 3, fr: "Ont de douces langueurs et des frissons amers.", en: "They tell of gentle yearning, frigid misery.", es: "Tienen suaves languideces y escalofríos amargos.",
      wordGroups: [
        { wid: "3-0", fr: "douces", en: "gentle", es: "suaves" },
        { wid: "3-1", fr: "langueurs", en: "yearning", es: "languideces" },
        { wid: "3-2", fr: "des frissons amers", en: "frigid misery", es: "escalofríos amargos" },
      ] },
    { id: 4, fr: "Les unes, cœurs épris des longues confidences,", en: "A few, with heart-confiding faith of old, imbued", es: "Las unas, corazones gustosos de las largas confidencias,",
      wordGroups: [
        { wid: "4-0", fr: "Les unes", en: "A few", es: "Las unas" },
        { wid: "4-1", fr: "cœurs épris", en: "heart-confiding", es: "corazones gustosos" },
        { wid: "4-2", fr: "longues", en: "of old", es: "largas" },
      ] },
    { id: 5, fr: "Dans le fond des bosquets où jasent les ruisseaux,", en: "Amid the darkling grove, where silver streamlets flow,", es: "En el fondo de bosquecillos donde brotan los arroyos,",
      wordGroups: [
        { wid: "5-0", fr: "Dans le fond", en: "Amid", es: "En el fondo" },
        { wid: "5-1", fr: "des bosquets", en: "the darkling grove", es: "de bosquecillos" },
        { wid: "5-2", fr: "où", en: "where", es: "donde" },
        { wid: "5-3", fr: "jasent", en: "flow", es: "brotan" },
        { wid: "5-4", fr: "les ruisseaux", en: "silver streamlets", es: "los arroyos" },
      ] },
    { id: 6, fr: "Vont épelant l’amour des craintives enfances", en: "Unfold to each their loves of tender infanthood,", es: "Van deletreando el amor de tímidas infancias",
      wordGroups: [
        { wid: "6-0", fr: "épelant", en: "Unfold", es: "deletreando" },
        { wid: "6-1", fr: "l’amour", en: "their loves", es: "el amor" },
        { wid: "6-2", fr: "craintives", en: "tender", es: "tímidas" },
        { wid: "6-3", fr: "enfances", en: "infanthood", es: "infancias" },
      ] },
    { id: 7, fr: "Et creusent le bois vert des jeunes arbrisseaux ;", en: "And carve the verdant stems of the vine-kissed portico.", es: "Y cincelan la corteza verde de los tiernos arbustos;",
      wordGroups: [
        { wid: "7-0", fr: "Et", en: "And", es: "Y" },
        { wid: "7-1", fr: "creusent", en: "carve", es: "cincelan" },
        { wid: "7-2", fr: "le bois vert", en: "the verdant stems", es: "la corteza verde" },
      ] },
    { id: 8, fr: "D’autres, comme des sœurs, marchent lentes et graves", en: "And others like unto nuns with footsteps slow and grave,", es: "Otras, cual religiosas, caminan lentas y graves,",
      wordGroups: [
        { wid: "8-0", fr: "D’autres", en: "others", es: "Otras" },
        { wid: "8-1", fr: "comme", en: "like", es: "cual" },
        { wid: "8-2", fr: "des sœurs", en: "nuns", es: "religiosas" },
        { wid: "8-3", fr: "marchent", en: "footsteps", es: "caminan" },
        { wid: "8-4", fr: "lentes et graves", en: "slow and grave", es: "lentas y graves" },
      ] },
    { id: 9, fr: "À travers les rochers pleins d’apparitions,", en: "Ascend the hallowed rocks of ancient mystic lore,", es: "A través de las rocas llenas de apariciones,",
      wordGroups: [
        { wid: "9-0", fr: "les rochers", en: "the hallowed rocks", es: "las rocas" },
        { wid: "9-1", fr: "d’apparitions", en: "ancient mystic lore", es: "de apariciones" },
      ] },
    { id: 10, fr: "Où saint Antoine a vu surgir comme des laves", en: "Where long ago--St. Anthony, like a surging wave,", es: "Donde San Antonio ha visto surgir como de las lavas",
      wordGroups: [
        { wid: "10-0", fr: "Où", en: "Where", es: "Donde" },
        { wid: "10-1", fr: "saint Antoine", en: "St. Anthony", es: "San Antonio" },
        { wid: "10-2", fr: "surgir", en: "surging", es: "surgir" },
        { wid: "10-3", fr: "comme", en: "like", es: "como" },
        { wid: "10-4", fr: "des laves", en: "wave", es: "de las lavas" },
      ] },
    { id: 11, fr: "Les seins nus et pourprés de ses tentations ;", en: "The naked purpled breasts of his temptation saw.", es: "Los pechos desnudos y purpúreos de sus tentaciones;",
      wordGroups: [
        { wid: "11-0", fr: "seins", en: "breasts", es: "pechos" },
        { wid: "11-1", fr: "nus", en: "naked", es: "desnudos" },
        { wid: "11-2", fr: "pourprés", en: "purpled", es: "purpúreos" },
        { wid: "11-3", fr: "ses tentations", en: "his temptation", es: "sus tentaciones" },
      ] },
    { id: 12, fr: "Il en est, aux lueurs des résines croulantes,", en: "And still some more, that 'neath the shimmering masses stroll,", es: "Las hay, a la lumbre de resinas crepitantes,",
      wordGroups: [
        { wid: "12-0", fr: "Il en est", en: "some more", es: "Las hay" },
        { wid: "12-1", fr: "lueurs", en: "shimmering", es: "lumbre" },
      ] },
    { id: 13, fr: "Qui dans le creux muet des vieux antres païens", en: "Among the silent chasm of some pagan caves,", es: "Que en la cavidad muda de los viejos antros paganos",
      wordGroups: [
        { wid: "13-0", fr: "le creux", en: "chasm", es: "la cavidad" },
        { wid: "13-1", fr: "muet", en: "silent", es: "muda" },
        { wid: "13-2", fr: "antres", en: "caves", es: "antros" },
        { wid: "13-3", fr: "païens", en: "pagan", es: "paganos" },
      ] },
    { id: 14, fr: "T’appellent au secours de leurs fièvres hurlantes,", en: "To soothe their burning fevers unto thee they call", es: "Te apelan en auxilio de sus fiebres aullantes,",
      wordGroups: [
        { wid: "14-0", fr: "T’appellent", en: "they call", es: "Te apelan" },
        { wid: "14-1", fr: "au secours", en: "To soothe", es: "en auxilio" },
        { wid: "14-2", fr: "leurs fièvres hurlantes", en: "their burning fevers", es: "sus fiebres aullantes" },
      ] },
    { id: 15, fr: "Ô Bacchus, endormeur des remords anciens !", en: "O Bacchus! who all ancient wounds and sorrow laves.", es: "¡Oh, Baco, adormecedor de remordimientos pasados!",
      wordGroups: [
        { wid: "15-0", fr: "Ô Bacchus", en: "O Bacchus", es: "Oh, Baco" },
        { wid: "15-1", fr: "endormeur", en: "laves", es: "adormecedor" },
        { wid: "15-2", fr: "remords", en: "wounds", es: "remordimientos" },
        { wid: "15-3", fr: "anciens", en: "ancient", es: "pasados" },
      ] },
    { id: 16, fr: "Et d’autres, dont la gorge aime les scapulaires,", en: "And others again, whose necks in scapulars delight,", es: "Y otras hay, cuya garganta gusta de los escapularios,",
      wordGroups: [
        { wid: "16-0", fr: "Et d’autres", en: "And others", es: "Y otras" },
        { wid: "16-1", fr: "la gorge", en: "necks", es: "garganta" },
        { wid: "16-2", fr: "aime", en: "delight", es: "gusta" },
        { wid: "16-3", fr: "les scapulaires", en: "scapulars", es: "los escapularios" },
      ] },
    { id: 17, fr: "Qui, recélant un fouet sous leurs longs vêtements,", en: "Who hide a whip beneath their garments secretly,", es: "Que, barruntando una fusta bajo sus largas vestimentas,",
      wordGroups: [
        { wid: "17-0", fr: "Qui", en: "Who", es: "Que" },
        { wid: "17-1", fr: "recélant", en: "hide", es: "barruntando" },
        { wid: "17-2", fr: "un fouet", en: "a whip", es: "una fusta" },
        { wid: "17-3", fr: "sous", en: "beneath", es: "bajo" },
        { wid: "17-4", fr: "leurs longs vêtements", en: "their garments", es: "sus largas vestimentas" },
      ] },
    { id: 18, fr: "Mêlent, dans le bois sombre et les nuits solitaires,", en: "Commingling, in the sombre wood and lonesome night,", es: "Mezclan, en el bosque sombrío y las noches solitarias,",
      wordGroups: [
        { wid: "18-0", fr: "Mêlent", en: "Commingling", es: "Mezclan" },
        { wid: "18-1", fr: "le bois", en: "wood", es: "el bosque" },
        { wid: "18-2", fr: "sombre", en: "sombre", es: "sombrío" },
        { wid: "18-3", fr: "les nuits", en: "night", es: "las noches" },
        { wid: "18-4", fr: "solitaires", en: "lonesome", es: "solitarias" },
      ] },
    { id: 19, fr: "L’écume du plaisir aux larmes des tourments.", en: "The foam of torments and of tears with ecstasy.", es: "La espuma del placer con las lágrimas de los tormentos.",
      wordGroups: [
        { wid: "19-0", fr: "L’écume", en: "The foam", es: "La espuma" },
        { wid: "19-1", fr: "du plaisir", en: "with ecstasy", es: "del placer" },
        { wid: "19-2", fr: "larmes", en: "tears", es: "lágrimas" },
        { wid: "19-3", fr: "des tourments", en: "torments", es: "de los tormentos" },
      ] },
    { id: 20, fr: "Ô vierges, ô démons, ô monstres, ô martyres,", en: "O virgins, demons, monsters, and O martyred brood!", es: "¡Oh vírgenes, oh demonios, oh monstruos, oh mártires,",
      wordGroups: [
        { wid: "20-0", fr: "Ô vierges", en: "O virgins", es: "Oh vírgenes" },
        { wid: "20-1", fr: "démons", en: "demons", es: "demonios" },
        { wid: "20-2", fr: "monstres", en: "monsters", es: "monstruos" },
        { wid: "20-3", fr: "martyres", en: "martyred brood", es: "mártires" },
      ] },
    { id: 21, fr: "De la réalité grands esprits contempteurs,", en: "Great souls that mock Reality with remorseless sneers,", es: "De la realidad, grandes espíritus desdeñosos,",
      wordGroups: [
        { wid: "21-0", fr: "la réalité", en: "Reality", es: "la realidad" },
        { wid: "21-1", fr: "grands esprits", en: "Great souls", es: "grandes espíritus" },
        { wid: "21-2", fr: "contempteurs", en: "mock", es: "desdeñosos" },
      ] },
    { id: 22, fr: "Chercheuses d’infini, dévotes et satyres,", en: "O saints and satyrs, searchers for infinitude!", es: "Buscadoras del infinito, devotas y sátiras,",
      wordGroups: [
        { wid: "22-0", fr: "Chercheuses", en: "searchers", es: "Buscadoras" },
        { wid: "22-1", fr: "d’infini", en: "infinitude", es: "del infinito" },
        { wid: "22-2", fr: "dévotes", en: "saints", es: "devotas" },
        { wid: "22-3", fr: "satyres", en: "satyrs", es: "sátiras" },
      ] },
    { id: 23, fr: "Tantôt pleines de cris, tantôt pleines de pleurs,", en: "At times so full of shouts, at times so full of tears!", es: "Ora llenas de gritos, ora llenas de lágrimas,",
      wordGroups: [
        { wid: "23-0", fr: "Tantôt", en: "At times", es: "Ora" },
        { wid: "23-1", fr: "pleines de cris", en: "so full of shouts", es: "llenas de gritos" },
        { wid: "23-2", fr: "tantôt", en: "at times", es: "ora" },
        { wid: "23-3", fr: "pleines de pleurs", en: "so full of tears", es: "llenas de lágrimas" },
      ] },
    { id: 24, fr: "Vous que dans votre enfer mon âme a poursuivies,", en: "You, to whom within your hell my spirit flies,", es: "Vosotras que hasta vuestro infierno mi alma ha perseguido,",
      wordGroups: [
        { wid: "24-0", fr: "Vous", en: "You", es: "Vosotras" },
        { wid: "24-1", fr: "dans votre enfer", en: "within your hell", es: "hasta vuestro infierno" },
        { wid: "24-2", fr: "mon âme", en: "my spirit", es: "mi alma" },
        { wid: "24-3", fr: "poursuivies", en: "flies", es: "perseguido" },
      ] },
    { id: 25, fr: "Pauvres sœurs, je vous aime autant que je vous plains,", en: "Poor sisters--yea, I love you as I pity you,", es: "Pobres hermanas mías, yo os amo tanto como os compadezco,",
      wordGroups: [
        { wid: "25-0", fr: "Pauvres sœurs", en: "Poor sisters", es: "Pobres hermanas" },
        { wid: "25-1", fr: "je vous aime", en: "I love you", es: "yo os amo" },
        { wid: "25-2", fr: "autant que", en: "as", es: "tanto como" },
        { wid: "25-3", fr: "je vous plains", en: "I pity you", es: "os compadezco" },
      ] },
    { id: 26, fr: "Pour vos mornes douleurs, vos soifs inassouvies,", en: "For your unsatiated thirsts and anguished sighs,", es: "Por vuestros tristes dolores, vuestra sed insaciable,",
      wordGroups: [
        { wid: "26-0", fr: "Pour", en: "For", es: "Por" },
        { wid: "26-1", fr: "mornes douleurs", en: "anguished sighs", es: "tristes dolores" },
        { wid: "26-2", fr: "vos soifs", en: "thirsts", es: "vuestra sed" },
        { wid: "26-3", fr: "inassouvies", en: "unsatiated", es: "insaciable" },
      ] },
    { id: 27, fr: "Et les urnes d’amour dont vos grands cœurs sont pleins !", en: "And for the vials of love within your hearts so true.", es: "¡Y las urnas de amor del que vuestros corazones desbordan!",
      wordGroups: [
        { wid: "27-0", fr: "Et", en: "And", es: "Y" },
        { wid: "27-1", fr: "les urnes", en: "the vials", es: "las urnas" },
        { wid: "27-2", fr: "d’amour", en: "of love", es: "de amor" },
        { wid: "27-3", fr: "vos grands cœurs", en: "your hearts", es: "vuestros corazones" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
