window.POEMS = window.POEMS || {};

window.POEMS["une-martyre"] = {
  title: "Une Martyre",
  titles: { fr: "Une Martyre" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Une_martyre",
  },
  segments: [
    { id: 0, fr: "Au milieu des flacons, des étoffes lamées" },
    { id: 1, fr: "﻿Et des meubles voluptueux," },
    { id: 2, fr: "Des marbres, des tableaux, des robes parfumées" },
    { id: 3, fr: "﻿Qui traînent à plis somptueux," },
    { id: 4, fr: "Dans une chambre tiède où, comme en une serre," },
    { id: 5, fr: "﻿L’air est dangereux et fatal," },
    { id: 6, fr: "Où des bouquets mourants dans leurs cercueils de verre" },
    { id: 7, fr: "﻿Exhalent leur soupir final," },
    { id: 8, fr: "Un cadavre sans tête épanche, comme un fleuve," },
    { id: 9, fr: "﻿Sur l’oreiller désaltéré" },
    { id: 10, fr: "Un sang rouge et vivant, dont la toile s’abreuve" },
    { id: 11, fr: "﻿Avec l’avidité d’un pré." },
    { id: 12, fr: "Semblable aux visions pâles qu’enfante l’ombre" },
    { id: 13, fr: "﻿Et qui nous enchaînent les yeux," },
    { id: 14, fr: "La tête, avec l’amas de sa crinière sombre" },
    { id: 15, fr: "﻿Et de ses bijoux précieux," },
    { id: 16, fr: "Sur la table de nuit, comme une renoncule," },
    { id: 17, fr: "﻿Repose ; et, vide de pensers," },
    { id: 18, fr: "Un regard vague et blanc comme le crépuscule" },
    { id: 19, fr: "﻿S’échappe des yeux révulsés." },
    { id: 20, fr: "Sur le lit, le tronc nu sans scrupules étale" },
    { id: 21, fr: "﻿Dans le plus complet abandon" },
    { id: 22, fr: "La secrète splendeur et la beauté fatale" },
    { id: 23, fr: "﻿Dont la nature lui fit don ;" },
    { id: 24, fr: "Un bas rosâtre, orné de coins d’or, à la jambe," },
    { id: 25, fr: "﻿Comme un souvenir est resté ;" },
    { id: 26, fr: "La jarretière, ainsi qu’un œil secret qui flambe," },
    { id: 27, fr: "﻿Darde un regard diamanté." },
    { id: 28, fr: "Le singulier aspect de cette solitude" },
    { id: 29, fr: "﻿Et d’un grand portrait langoureux," },
    { id: 30, fr: "Aux yeux provocateurs comme son attitude," },
    { id: 31, fr: "﻿Révèle un amour ténébreux," },
    { id: 32, fr: "Une coupable joie et des fêtes étranges" },
    { id: 33, fr: "﻿Pleines de baisers infernaux," },
    { id: 34, fr: "Dont se réjouissait l’essaim des mauvais anges" },
    { id: 35, fr: "﻿Nageant dans les plis des rideaux ;" },
    { id: 36, fr: "Et cependant, à voir la maigreur élégante" },
    { id: 37, fr: "﻿De l’épaule au contour heurté," },
    { id: 38, fr: "La hanche un peu pointue et la taille fringante" },
    { id: 39, fr: "﻿Ainsi qu’un reptile irrité," },
    { id: 40, fr: "Elle est bien jeune encor ! — Son âme exaspérée" },
    { id: 41, fr: "﻿Et ses sens par l’ennui mordus" },
    { id: 42, fr: "S’étaient-ils entr’ouverts à la meute altérée" },
    { id: 43, fr: "﻿Des désirs errants et perdus ?" },
    { id: 44, fr: "L’homme vindicatif que tu n’as pu, vivante," },
    { id: 45, fr: "﻿Malgré tant d’amour, assouvir," },
    { id: 46, fr: "Combla-t-il sur ta chair inerte et complaisante" },
    { id: 47, fr: "﻿L’immensité de son désir ?" },
    { id: 48, fr: "Réponds, cadavre impur ! et par tes tresses roides" },
    { id: 49, fr: "﻿Te soulevant d’un bras fiévreux," },
    { id: 50, fr: "Dis-moi, tête effrayante, a-t-il sur tes dents froides" },
    { id: 51, fr: "﻿Collé les suprêmes adieux ?" },
    { id: 52, fr: "— Loin du monde railleur, loin de la foule impure," },
    { id: 53, fr: "﻿Loin des magistrats curieux," },
    { id: 54, fr: "Dors en paix, dors en paix, étrange créature," },
    { id: 55, fr: "﻿Dans ton tombeau mystérieux ;" },
    { id: 56, fr: "Ton époux court le monde, et ta forme immortelle" },
    { id: 57, fr: "﻿Veille près de lui quand il dort ;" },
    { id: 58, fr: "Autant que toi sans doute il te sera fidèle," },
    { id: 59, fr: "﻿Et constant jusques à la mort." },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
