window.POEMS = window.POEMS || {};

window.POEMS["benediction"] = {
  title: "Bénédiction",
  titles: { fr: "Bénédiction", en: "Benediction", es: "Bendición" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Lorsque, par un décret des puissances supremes,", en: "When by the changeless Power of a Supreme Decree", es: "Cuando, por un decreto de las potencias supremas,",
      wordGroups: [
        { wid: "0-0", fr: "Lorsque", en: "When", es: "Cuando" },
        { wid: "0-1", fr: "décret", en: "Decree", es: "decreto" },
        { wid: "0-2", fr: "puissances", en: "Power", es: "potencias" },
        { wid: "0-3", fr: "supremes", en: "Supreme", es: "supremas" },
      ] },
    { id: 1, fr: "Le Poëte apparaît en ce monde ennuyé,", en: "The poet issues forth upon this sorry sphere,", es: "El Poeta aparece en este mundo hastiado,",
      wordGroups: [
        { wid: "1-0", fr: "Le Poëte", en: "The poet", es: "El Poeta" },
        { wid: "1-1", fr: "apparaît", en: "issues forth", es: "aparece" },
        { wid: "1-2", fr: "monde", en: "sphere", es: "mundo" },
        { wid: "1-3", fr: "ennuyé", en: "sorry", es: "hastiado" },
      ] },
    { id: 2, fr: "Sa mère épouvantée et pleine de blasphèmes", en: "His mother, horrified, and full of blasphemy,", es: "Su madre espantada y llena de blasfemias",
      wordGroups: [
        { wid: "2-0", fr: "Sa mère", en: "His mother", es: "Su madre" },
        { wid: "2-1", fr: "épouvantée", en: "horrified", es: "espantada" },
        { wid: "2-2", fr: "pleine", en: "full", es: "llena" },
        { wid: "2-3", fr: "blasphèmes", en: "blasphemy", es: "blasfemias" },
      ] },
    { id: 3, fr: "Crispe ses poings vers Dieu, qui la prend en pitié :", en: "Uplifts her voice to God, who takes compassion on her.", es: "Crispa sus puños hacia Dios, que de ella se apiada:",
      wordGroups: [
        { wid: "3-0", fr: "Crispe ses poings", en: "Uplifts her voice", es: "Crispa sus puños" },
        { wid: "3-1", fr: "vers Dieu", en: "to God", es: "hacia Dios" },
        { wid: "3-2", fr: "prend en pitié", en: "takes compassion", es: "se apiada" },
      ] },
    { id: 4, fr: "— « Ah ! que n’ai-je mis bas tout un nœud de vipères,", en: "\"Ah, why did I not bear a serpent's nest entire,", es: "—\"¡Ah! ¡no haber parido todo un nudo de víboras,",
      wordGroups: [
        { wid: "4-0", fr: "Ah", en: "Ah", es: "Ah" },
        { wid: "4-1", fr: "mis bas", en: "bear", es: "parido" },
        { wid: "4-2", fr: "tout", en: "entire", es: "todo" },
        { wid: "4-3", fr: "nœud", en: "nest", es: "nudo" },
        { wid: "4-4", fr: "vipères", en: "serpent's", es: "víboras" },
      ] },
    { id: 5, fr: "Plutôt que de nourrir cette dérision !", en: "Instead of bringing forth this hideous Child of Doom!", es: "Antes que amamantar esta irrisión!",
      wordGroups: [
        { wid: "5-0", fr: "Plutôt que de", en: "Instead of", es: "Antes que" },
        { wid: "5-1", fr: "nourrir", en: "bringing forth", es: "amamantar" },
        { wid: "5-2", fr: "cette dérision", en: "this hideous Child of Doom", es: "esta irrisión" },
      ] },
    { id: 6, fr: "Maudite soit la nuit aux plaisirs éphémères", en: "Oh cursèd be that transient night of vain desire", es: "¡Maldita sea la noche de placeres efímeros",
      wordGroups: [
        { wid: "6-0", fr: "Maudite soit", en: "cursèd be", es: "Maldita sea" },
        { wid: "6-1", fr: "nuit", en: "night", es: "noche" },
        { wid: "6-2", fr: "plaisirs", en: "desire", es: "placeres" },
        { wid: "6-3", fr: "éphémères", en: "transient", es: "efímeros" },
      ] },
    { id: 7, fr: "Où mon ventre a conçu mon expiation !", en: "When I conceived my expiation in my womb!\"", es: "En que mi vientre concibió mi expiación!",
      wordGroups: [
        { wid: "7-0", fr: "Où", en: "When", es: "En que" },
        { wid: "7-1", fr: "mon ventre", en: "my womb", es: "mi vientre" },
        { wid: "7-2", fr: "a conçu", en: "conceived", es: "concibió" },
        { wid: "7-3", fr: "mon expiation", en: "my expiation", es: "mi expiación" },
      ] },
    { id: 8, fr: "Puisque tu m’as choisie entre toutes les femmes", en: "\"Yet since among all women thou hast chosen me", es: "Puesto que tú me has escogido entre todas las mujeres",
      wordGroups: [
        { wid: "8-0", fr: "Puisque", en: "since", es: "Puesto que" },
        { wid: "8-1", fr: "m’as choisie", en: "hast chosen me", es: "me has escogido" },
        { wid: "8-2", fr: "entre", en: "among", es: "entre" },
        { wid: "8-3", fr: "toutes les femmes", en: "all women", es: "todas las mujeres" },
      ] },
    { id: 9, fr: "Pour être le dégoût de mon triste mari,", en: "To be the degradation of my jaded mate,", es: "Para ser el asco de mí triste marido,",
      wordGroups: [
        { wid: "9-0", fr: "Pour être", en: "To be", es: "Para ser" },
        { wid: "9-1", fr: "le dégoût", en: "the degradation", es: "el asco" },
        { wid: "9-2", fr: "triste", en: "jaded", es: "triste" },
        { wid: "9-3", fr: "mari", en: "mate", es: "marido" },
      ] },
    { id: 10, fr: "Et que je ne puis pas rejeter dans les flammes,", en: "And since I cannot like a love-leaf wantonly", es: "Y como yo no puedo arrojar a las llamas,",
      wordGroups: [
        { wid: "10-0", fr: "Et", en: "And", es: "Y" },
        { wid: "10-1", fr: "que", en: "since", es: "como" },
        { wid: "10-2", fr: "je ne puis pas", en: "I cannot", es: "yo no puedo" },
      ] },
    { id: 11, fr: "Comme un billet d’amour, ce monstre rabougri,", en: "Consign this stunted monster to the glowing grate,\"", es: "Como una esquela de amor, este monstruo esmirriado,",
      wordGroups: [
        { wid: "11-0", fr: "ce", en: "this", es: "este" },
        { wid: "11-1", fr: "monstre", en: "monster", es: "monstruo" },
        { wid: "11-2", fr: "rabougri", en: "stunted", es: "esmirriado" },
      ] },
    { id: 12, fr: "Je ferai rejaillir ta haine qui m’accable", en: "\"I'll cause thine overwhelming hatred to rebound", es: "¡Yo haré rebotar tu odio que me agobia",
      wordGroups: [
        { wid: "12-0", fr: "Je ferai", en: "I'll cause", es: "Yo haré" },
        { wid: "12-1", fr: "rejaillir", en: "rebound", es: "rebotar" },
        { wid: "12-2", fr: "haine", en: "hatred", es: "odio" },
        { wid: "12-3", fr: "m’accable", en: "overwhelming", es: "me agobia" },
      ] },
    { id: 13, fr: "Sur l’instrument maudit de tes méchancetés,", en: "Upon the cursèd tool of thy most wicked spite.", es: "Sobre el instrumento maldito de tus perversidades,",
      wordGroups: [
        { wid: "13-0", fr: "Sur", en: "Upon", es: "Sobre" },
        { wid: "13-1", fr: "l’instrument", en: "tool", es: "el instrumento" },
        { wid: "13-2", fr: "maudit", en: "cursèd", es: "maldito" },
        { wid: "13-3", fr: "méchancetés", en: "wicked spite", es: "perversidades" },
      ] },
    { id: 14, fr: "Et je tordrai si bien cet arbre misérable,", en: "Forsooth, the branches of this wretched tree I'll wound", es: "Y he de retorcer tan bien este árbol miserable,",
      wordGroups: [
        { wid: "14-0", fr: "je tordrai", en: "I'll wound", es: "he de retorcer" },
        { wid: "14-1", fr: "arbre", en: "tree", es: "árbol" },
        { wid: "14-2", fr: "misérable", en: "wretched", es: "miserable" },
      ] },
    { id: 15, fr: "Qu’il ne pourra pousser ses boutons empestés ! »", en: "And rob its pestilential blossoms of their might!\"", es: "Que no podrán retoñar sus brotes apestados!\"",
      wordGroups: [
        { wid: "15-0", fr: "ses", en: "its", es: "sus" },
        { wid: "15-1", fr: "boutons", en: "blossoms", es: "brotes" },
        { wid: "15-2", fr: "empestés", en: "pestilential", es: "apestados" },
      ] },
    { id: 16, fr: "Elle ravale ainsi l’écume de sa haine,", en: "So thus, she giveth vent unto her foaming ire,", es: "Ella vuelve a tragar la espuma de su odio,",
      wordGroups: [
        { wid: "16-0", fr: "Elle", en: "she", es: "Ella" },
        { wid: "16-1", fr: "ainsi", en: "So thus" },
        { wid: "16-2", fr: "l’écume", en: "foaming", es: "la espuma" },
        { wid: "16-3", fr: "haine", en: "ire", es: "odio" },
      ] },
    { id: 17, fr: "Et, ne comprenant pas les desseins éternels,", en: "And knowing not the changeless statutes of all times,", es: "Y, no comprendiendo los designios eternos,",
      wordGroups: [
        { wid: "17-0", fr: "Et", en: "And", es: "Y" },
        { wid: "17-1", fr: "ne comprenant pas", en: "knowing not", es: "no comprendiendo" },
        { wid: "17-2", fr: "desseins", en: "statutes", es: "designios" },
        { wid: "17-3", fr: "éternels", en: "of all times", es: "eternos" },
      ] },
    { id: 18, fr: "Elle-même prépare au fond de la Géhenne", en: "Herself, amid the flames of hell, prepares the pyre;", es: "Ella misma prepara en el fondo de la Gehena",
      wordGroups: [
        { wid: "18-0", fr: "Elle-même", en: "Herself", es: "Ella misma" },
        { wid: "18-1", fr: "prépare", en: "prepares", es: "prepara" },
        { wid: "18-2", fr: "au fond de", en: "amid", es: "en el fondo de" },
        { wid: "18-3", fr: "la Géhenne", en: "hell", es: "la Gehena" },
      ] },
    { id: 19, fr: "Les bûchers consacrés aux crimes maternels.", en: "The consecrated penance of maternal crimes.", es: "Las hogueras consagradas a los crímenes maternos.",
      wordGroups: [
        { wid: "19-0", fr: "consacrés", en: "consecrated", es: "consagradas" },
        { wid: "19-1", fr: "crimes", en: "crimes", es: "crímenes" },
        { wid: "19-2", fr: "maternels", en: "maternal", es: "maternos" },
      ] },
    { id: 20, fr: "Pourtant, sous la tutelle invisible d’un Ange,", en: "Yet 'neath th' invisible shelter of an Angel's wing", es: "Sin embargo, bajo la tutela invisible de un Ángel,",
      wordGroups: [
        { wid: "20-0", fr: "Pourtant", en: "Yet", es: "Sin embargo" },
        { wid: "20-1", fr: "sous", en: "'neath", es: "bajo" },
        { wid: "20-2", fr: "tutelle", en: "shelter", es: "tutela" },
        { wid: "20-3", fr: "invisible", en: "invisible", es: "invisible" },
        { wid: "20-4", fr: "Ange", en: "Angel's", es: "Ángel" },
      ] },
    { id: 21, fr: "L’Enfant déshérité s’enivre de soleil,", en: "This sunlight-loving infant disinherited,", es: "El Niño desheredado se embriaga de sol,",
      wordGroups: [
        { wid: "21-0", fr: "L’Enfant", en: "infant", es: "El Niño" },
        { wid: "21-1", fr: "déshérité", en: "disinherited", es: "desheredado" },
        { wid: "21-2", fr: "s’enivre de soleil", en: "sunlight-loving", es: "se embriaga de sol" },
      ] },
    { id: 22, fr: "Et dans tout ce qu’il boit et dans tout ce qu’il mange", en: "Exhales from all he eats and drinks, and everything", es: "Y en todo cuanto bebe y en todo cuanto come,",
      wordGroups: [
        { wid: "22-0", fr: "boit", en: "drinks", es: "bebe" },
        { wid: "22-1", fr: "mange", en: "eats", es: "come" },
      ] },
    { id: 23, fr: "Retrouve l’ambroisie et le nectar vermeil.", en: "The ever sweet ambrosia and the nectar red.", es: "Encuentra la ambrosia y el néctar bermejo.",
      wordGroups: [
        { wid: "23-0", fr: "l’ambroisie", en: "ambrosia", es: "la ambrosia" },
        { wid: "23-1", fr: "le nectar", en: "the nectar", es: "el néctar" },
        { wid: "23-2", fr: "vermeil", en: "red", es: "bermejo" },
      ] },
    { id: 24, fr: "Il joue avec le vent, cause avec le nuage,", en: "He trifles with the winds and with the clouds that glide,", es: "Él juega con el viento, conversa con la nube,",
      wordGroups: [
        { wid: "24-0", fr: "Il joue", en: "He trifles", es: "Él juega" },
        { wid: "24-1", fr: "le vent", en: "the winds", es: "el viento" },
        { wid: "24-2", fr: "le nuage", en: "the clouds", es: "la nube" },
      ] },
    { id: 25, fr: "Et s’enivre en chantant du chemin de la croix ;", en: "About the way unto the Cross, he loves to sing,", es: "Y se embriaga cantando el camino de la cruz;",
      wordGroups: [
        { wid: "25-0", fr: "en chantant", en: "to sing", es: "cantando" },
        { wid: "25-1", fr: "du chemin", en: "the way", es: "el camino" },
        { wid: "25-2", fr: "de la croix", en: "the Cross", es: "de la cruz" },
      ] },
    { id: 26, fr: "Et l’Esprit qui le suit dans son pèlerinage", en: "The spirit on his pilgrimage; that faithful guide,", es: "Y el Espíritu que le sigue en su peregrinaje",
      wordGroups: [
        { wid: "26-0", fr: "l’Esprit", en: "The spirit", es: "el Espíritu" },
        { wid: "26-1", fr: "qui le suit", en: "that faithful guide", es: "que le sigue" },
        { wid: "26-2", fr: "son pèlerinage", en: "his pilgrimage", es: "su peregrinaje" },
      ] },
    { id: 27, fr: "Pleure de le voir gai comme un oiseau des bois.", en: "Oft weeps to see him joyful like a bird of Spring.", es: "Llora al verle alegre cual pájaro de los bosques.",
      wordGroups: [
        { wid: "27-0", fr: "Pleure", en: "Oft weeps", es: "Llora" },
        { wid: "27-1", fr: "de le voir", en: "to see him", es: "al verle" },
        { wid: "27-2", fr: "gai", en: "joyful", es: "alegre" },
        { wid: "27-3", fr: "comme", en: "like", es: "cual" },
        { wid: "27-4", fr: "un oiseau des bois", en: "a bird of Spring", es: "pájaro de los bosques" },
      ] },
    { id: 28, fr: "Tous ceux qu’il veut aimer l’observent avec crainte,", en: "All those that he would cherish shrink from him with fear,", es: "Todos aquellos que él quiere lo observan con temor,",
      wordGroups: [
        { wid: "28-0", fr: "Tous ceux", en: "All those", es: "Todos aquellos" },
        { wid: "28-1", fr: "qu’il veut aimer", en: "that he would cherish", es: "que él quiere" },
        { wid: "28-2", fr: "l’observent", en: "shrink from him", es: "lo observan" },
        { wid: "28-3", fr: "avec crainte", en: "with fear", es: "con temor" },
      ] },
    { id: 29, fr: "Ou bien, s’enhardissant de sa tranquillité,", en: "And some that waxen bold by his tranquility,", es: "O bien, enardeciéndose con su tranquilidad,",
      wordGroups: [
        { wid: "29-0", fr: "s’enhardissant", en: "waxen bold", es: "enardeciéndose" },
        { wid: "29-1", fr: "sa tranquillité", en: "his tranquility", es: "su tranquilidad" },
      ] },
    { id: 30, fr: "Cherchent à qui saura lui tirer une plainte,", en: "Endeavour hard some grievance from his heart to tear,", es: "Buscan al que sabrá arrancarle una queja,",
      wordGroups: [
        { wid: "30-0", fr: "Cherchent", en: "Endeavour hard", es: "Buscan" },
        { wid: "30-1", fr: "tirer", en: "to tear", es: "arrancarle" },
        { wid: "30-2", fr: "une plainte", en: "some grievance", es: "una queja" },
      ] },
    { id: 31, fr: "Et font sur lui l’essai de leur férocité.", en: "And make on him the trial of their ferocity.", es: "Y hacen sobre El el ensayo de su ferocidad.",
      wordGroups: [
        { wid: "31-0", fr: "Et font", en: "And make", es: "Y hacen" },
        { wid: "31-1", fr: "sur lui", en: "on him", es: "sobre El" },
        { wid: "31-2", fr: "l’essai", en: "the trial", es: "el ensayo" },
        { wid: "31-3", fr: "leur férocité", en: "their ferocity", es: "su ferocidad" },
      ] },
    { id: 32, fr: "Dans le pain et le vin destinés à sa bouche", en: "Within the bread and wine outspread for his repast", es: "En el pan y el vino destinados a su boca",
      wordGroups: [
        { wid: "32-0", fr: "Dans", en: "Within", es: "En" },
        { wid: "32-1", fr: "le pain", en: "the bread", es: "el pan" },
        { wid: "32-2", fr: "le vin", en: "wine", es: "el vino" },
        { wid: "32-3", fr: "destinés", en: "outspread", es: "destinados" },
        { wid: "32-4", fr: "à sa bouche", en: "for his repast", es: "a su boca" },
      ] },
    { id: 33, fr: "Ils mêlent de la cendre avec d’impurs crachats ;", en: "To mingle dust and dirty spittle they essay,", es: "Mezclan la ceniza con los impuros escupitajos;",
      wordGroups: [
        { wid: "33-0", fr: "mêlent", en: "To mingle", es: "Mezclan" },
        { wid: "33-1", fr: "de la cendre", en: "dust", es: "la ceniza" },
        { wid: "33-2", fr: "d’impurs", en: "dirty", es: "impuros" },
        { wid: "33-3", fr: "crachats", en: "spittle", es: "escupitajos" },
      ] },
    { id: 34, fr: "Avec hypocrisie ils jettent ce qu’il touche,", en: "And everything he touches, forth they slyly cast,", es: "Con hipocresía arrojan lo que él toca,",
      wordGroups: [
        { wid: "34-0", fr: "hypocrisie", en: "slyly", es: "hipocresía" },
        { wid: "34-1", fr: "jettent", en: "cast", es: "arrojan" },
        { wid: "34-2", fr: "ce qu’il touche", en: "everything he touches", es: "lo que él toca" },
      ] },
    { id: 35, fr: "Et s’accusent d’avoir mis leurs pieds dans ses pas.", en: "Or scourge themselves, if e'er their feet betrod his way.", es: "Y se acusan de haber puesto sus pies sobre sus pasos.",
      wordGroups: [
        { wid: "35-0", fr: "s’accusent", en: "scourge themselves", es: "se acusan" },
        { wid: "35-1", fr: "mis", en: "betrod", es: "puesto" },
        { wid: "35-2", fr: "leurs pieds", en: "their feet", es: "sus pies" },
        { wid: "35-3", fr: "ses pas", en: "his way", es: "sus pasos" },
      ] },
    { id: 36, fr: "Sa femme va criant sur les places publiques :", en: "His wife goes round proclaiming in the crowded quads--", es: "Su mujer va clamando en las plazas públicas:",
      wordGroups: [
        { wid: "36-0", fr: "Sa femme", en: "His wife", es: "Su mujer" },
        { wid: "36-1", fr: "va", en: "goes round", es: "va" },
        { wid: "36-2", fr: "criant", en: "proclaiming", es: "clamando" },
        { wid: "36-3", fr: "les places publiques", en: "the crowded quads", es: "las plazas públicas" },
      ] },
    { id: 37, fr: "« Puisqu’il me trouve assez belle pour m’adorer,", en: "\"Since he can find my body beauteous to behold,", es: "\"Puesto que él me encuentra bastante bella para adorarme,",
      wordGroups: [
        { wid: "37-0", fr: "Puisqu’il", en: "Since he", es: "Puesto que él" },
        { wid: "37-1", fr: "trouve", en: "can find", es: "encuentra" },
        { wid: "37-2", fr: "belle", en: "beauteous", es: "bella" },
        { wid: "37-3", fr: "m’adorer", en: "to behold", es: "adorarme" },
      ] },
    { id: 38, fr: "Je ferai le métier des idoles antiques,", en: "Why not perform the office of those ancient gods", es: "Yo desempeñaré el cometido de los ídolos antiguos,",
      wordGroups: [
        { wid: "38-0", fr: "Je ferai", en: "perform", es: "Yo desempeñaré" },
        { wid: "38-1", fr: "le métier", en: "the office", es: "el cometido" },
        { wid: "38-2", fr: "idoles", en: "gods", es: "ídolos" },
        { wid: "38-3", fr: "antiques", en: "ancient", es: "antiguos" },
      ] },
    { id: 39, fr: "Et comme elles je veux me faire redorer ;", en: "And like unto them, redeck myself with shining gold?\"", es: "Y como ellos yo quiero hacerme redorar;",
      wordGroups: [
        { wid: "39-0", fr: "Et comme", en: "And like", es: "Y como" },
        { wid: "39-1", fr: "elles", en: "them", es: "ellos" },
        { wid: "39-2", fr: "me faire redorer", en: "redeck myself with shining gold", es: "hacerme redorar" },
      ] },
    { id: 40, fr: "Et je me soûlerai de nard, d’encens, de myrrhe,", en: "\"I'll bathe myself with incense, spikenard and myrrh,", es: "¡Y me embriagaré de nardo, de incienso, de mirra,",
      wordGroups: [
        { wid: "40-0", fr: "je me soûlerai", en: "I'll bathe myself", es: "me embriagaré" },
        { wid: "40-1", fr: "nard", en: "spikenard", es: "nardo" },
        { wid: "40-2", fr: "d’encens", en: "incense", es: "incienso" },
        { wid: "40-3", fr: "myrrhe", en: "myrrh", es: "mirra" },
      ] },
    { id: 41, fr: "De génuflexions, de viandes et de vins,", en: "With genuflexions, delicate viandes and wine,", es: "De genuflexiones, de viandas y de vinos,",
      wordGroups: [
        { wid: "41-0", fr: "génuflexions", en: "genuflexions", es: "genuflexiones" },
        { wid: "41-1", fr: "viandes", en: "viandes", es: "viandas" },
        { wid: "41-2", fr: "vins", en: "wine", es: "vinos" },
      ] },
    { id: 42, fr: "Pour savoir si je puis dans un cœur qui m’admire", en: "To see, in jest, if from a heart, that loves me dear,", es: "Para saber si yo puedo de un corazón que me admira",
      wordGroups: [
        { wid: "42-0", fr: "Pour savoir", en: "To see", es: "Para saber" },
        { wid: "42-1", fr: "si", en: "if", es: "si" },
        { wid: "42-2", fr: "un cœur", en: "a heart", es: "un corazón" },
        { wid: "42-3", fr: "qui m’admire", en: "that loves me dear", es: "que me admira" },
      ] },
    { id: 43, fr: "Usurper en riant les hommages divins !", en: "I cannot filch away the hommages divine.\"", es: "Usurpar riendo los homenajes divinos!",
      wordGroups: [
        { wid: "43-0", fr: "Usurper", en: "filch away", es: "Usurpar" },
        { wid: "43-1", fr: "les hommages", en: "the hommages", es: "los homenajes" },
        { wid: "43-2", fr: "divins", en: "divine", es: "divinos" },
      ] },
    { id: 44, fr: "Et, quand je m’ennuierai de ces farces impies,", en: "\"And when of these impious jokes at length I tire,", es: "Y, cuando me hastíe de estas farsas impías,",
      wordGroups: [
        { wid: "44-0", fr: "quand", en: "when", es: "cuando" },
        { wid: "44-1", fr: "je m’ennuierai", en: "I tire", es: "me hastíe" },
        { wid: "44-2", fr: "farces", en: "jokes", es: "farsas" },
        { wid: "44-3", fr: "impies", en: "impious", es: "impías" },
      ] },
    { id: 45, fr: "Je poserai sur lui ma frêle et forte main ;", en: "My frail but mighty hands, around his breast entwined,", es: "Posaré sobre él mi frágil y fuerte mano;",
      wordGroups: [
        { wid: "45-0", fr: "ma frêle", en: "My frail", es: "mi frágil" },
        { wid: "45-1", fr: "forte", en: "mighty", es: "fuerte" },
        { wid: "45-2", fr: "main", en: "hands", es: "mano" },
      ] },
    { id: 46, fr: "Et mes ongles, pareils aux ongles des harpies,", en: "With nails, like harpies' nails, shall cunningly conspire", es: "Y mis uñas, parecidas a garras de arpías,",
      wordGroups: [
        { wid: "46-0", fr: "mes ongles", en: "With nails", es: "mis uñas" },
        { wid: "46-1", fr: "pareils", en: "like", es: "parecidas" },
        { wid: "46-2", fr: "harpies", en: "harpies'", es: "arpías" },
      ] },
    { id: 47, fr: "Sauront jusqu’à son cœur se frayer un chemin.", en: "The hidden path unto his feeble heart to find.\"", es: "Sabrán hasta su corazón abrirse un camino.",
      wordGroups: [
        { wid: "47-0", fr: "jusqu’à", en: "unto", es: "hasta" },
        { wid: "47-1", fr: "son cœur", en: "his feeble heart", es: "su corazón" },
        { wid: "47-2", fr: "se frayer", en: "to find", es: "abrirse" },
        { wid: "47-3", fr: "un chemin", en: "The hidden path", es: "un camino" },
      ] },
    { id: 48, fr: "Comme un tout jeune oiseau qui tremble et qui palpite,", en: "\"And like a youngling bird that trembles in its nest,", es: "Como un pájaro muy joven que tiembla y que palpita,",
      wordGroups: [
        { wid: "48-0", fr: "Comme", en: "like", es: "Como" },
        { wid: "48-1", fr: "tout jeune", en: "youngling", es: "muy joven" },
        { wid: "48-2", fr: "oiseau", en: "bird", es: "pájaro" },
        { wid: "48-3", fr: "qui tremble", en: "that trembles", es: "que tiembla" },
      ] },
    { id: 49, fr: "J’arracherai ce cœur tout rouge de son sein,", en: "I'll pluck his heart right out; within its own blood drowned,", es: "Yo arrancaré ese corazón enrojecido de su seno,",
      wordGroups: [
        { wid: "49-0", fr: "J’arracherai", en: "I'll pluck", es: "Yo arrancaré" },
        { wid: "49-1", fr: "ce cœur", en: "his heart", es: "ese corazón" },
      ] },
    { id: 50, fr: "Et, pour rassasier ma bête favorite,", en: "And finally to satiate my favourite beast,", es: "Y, para saciar mi bestia favorita,",
      wordGroups: [
        { wid: "50-0", fr: "Et", en: "And", es: "Y" },
        { wid: "50-1", fr: "pour rassasier", en: "to satiate", es: "para saciar" },
        { wid: "50-2", fr: "ma bête", en: "beast", es: "mi bestia" },
        { wid: "50-3", fr: "favorite", en: "favourite", es: "favorita" },
      ] },
    { id: 51, fr: "Je le lui jetterai par terre avec dédain ! »", en: "I'll throw it with intense disdain upon the ground!\"", es: "¡Yo se lo arrojaré al suelo con desdén!\"",
      wordGroups: [
        { wid: "51-0", fr: "Je", en: "I'll", es: "Yo" },
        { wid: "51-1", fr: "jetterai", en: "throw", es: "arrojaré" },
        { wid: "51-2", fr: "par terre", en: "upon the ground", es: "al suelo" },
        { wid: "51-3", fr: "avec dédain", en: "with intense disdain", es: "con desdén" },
      ] },
    { id: 52, fr: "Vers le Ciel, où son œil voit un trône splendide,", en: "Towards the Heavens where he sees the sacred grail", es: "Hacia el Cielo, donde su mirada alcanza un trono espléndido,",
      wordGroups: [
        { wid: "52-0", fr: "Vers", en: "Towards", es: "Hacia" },
        { wid: "52-1", fr: "le Ciel", en: "the Heavens", es: "el Cielo" },
        { wid: "52-2", fr: "où", en: "where", es: "donde" },
        { wid: "52-3", fr: "voit", en: "sees", es: "alcanza" },
        { wid: "52-4", fr: "un trône splendide", en: "the sacred grail", es: "un trono espléndido" },
      ] },
    { id: 53, fr: "Le Poëte serein lève ses bras pieux,", en: "The poet calmly stretches forth his pious arms,", es: "El Poeta sereno eleva sus brazos piadosos,",
      wordGroups: [
        { wid: "53-0", fr: "Le Poëte", en: "The poet", es: "El Poeta" },
        { wid: "53-1", fr: "serein", en: "calmly", es: "sereno" },
        { wid: "53-2", fr: "lève", en: "stretches forth", es: "eleva" },
        { wid: "53-3", fr: "ses bras", en: "arms", es: "sus brazos" },
        { wid: "53-4", fr: "pieux", en: "pious", es: "piadosos" },
      ] },
    { id: 54, fr: "Et les vastes éclairs de son esprit lucide", en: "Whereon the lightenings from his lucid spirit veil", es: "Y los amplios destellos de su espíritu lúcido",
      wordGroups: [
        { wid: "54-0", fr: "éclairs", en: "the lightenings", es: "destellos" },
        { wid: "54-1", fr: "son esprit", en: "spirit", es: "su espíritu" },
        { wid: "54-2", fr: "lucide", en: "lucid", es: "lúcido" },
      ] },
    { id: 55, fr: "Lui dérobent l’aspect des peuples furieux :", en: "The sight of the infuriated mob that swarms.", es: "Le ocultan el aspecto de los pueblos furiosos:",
      wordGroups: [
        { wid: "55-0", fr: "l’aspect", en: "The sight", es: "el aspecto" },
        { wid: "55-1", fr: "peuples", en: "mob", es: "pueblos" },
        { wid: "55-2", fr: "furieux", en: "infuriated", es: "furiosos" },
      ] },
    { id: 56, fr: "— « Soyez béni, mon Dieu, qui donnez la souffrance", en: "\"Oh blest be thou, Almighty who bestowest pain,", es: "—\"Bendito seas, mi Dios, que dais el sufrimiento",
      wordGroups: [
        { wid: "56-0", fr: "Soyez béni", en: "blest be thou", es: "Bendito seas" },
        { wid: "56-1", fr: "mon Dieu", en: "Almighty", es: "mi Dios" },
        { wid: "56-2", fr: "donnez", en: "bestowest", es: "dais" },
        { wid: "56-3", fr: "la souffrance", en: "pain", es: "el sufrimiento" },
      ] },
    { id: 57, fr: "Comme un divin remède à nos impuretés", en: "Like some divine redress for our infirmities,", es: "Como divino remedio a nuestras impurezas",
      wordGroups: [
        { wid: "57-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "57-1", fr: "divin", en: "divine", es: "divino" },
        { wid: "57-2", fr: "remède", en: "redress", es: "remedio" },
        { wid: "57-3", fr: "nos impuretés", en: "our infirmities", es: "nuestras impurezas" },
      ] },
    { id: 58, fr: "Et comme la meilleure et la plus pure essence", en: "And like the most refreshing and the purest rain,", es: "Y cual la mejor y la más pura esencia",
      wordGroups: [
        { wid: "58-0", fr: "Et comme", en: "And like", es: "Y cual" },
        { wid: "58-1", fr: "la meilleure", en: "the most refreshing", es: "la mejor" },
        { wid: "58-2", fr: "la plus pure", en: "the purest", es: "la más pura" },
        { wid: "58-3", fr: "essence", en: "rain", es: "esencia" },
      ] },
    { id: 59, fr: "Qui prépare les forts aux saintes voluptés !", en: "To sanctify the strong, for saintly ecstasies.\"", es: "¡Que prepara los fuertes para las santas voluptuosidades!",
      wordGroups: [
        { wid: "59-0", fr: "prépare", en: "To sanctify", es: "prepara" },
        { wid: "59-1", fr: "les forts", en: "the strong", es: "los fuertes" },
        { wid: "59-2", fr: "saintes", en: "saintly", es: "santas" },
        { wid: "59-3", fr: "voluptés", en: "ecstasies", es: "voluptuosidades" },
      ] },
    { id: 60, fr: "Je sais que vous gardez une place au Poëte", en: "\"I know that for the poet thou wilt grant a chair,", es: "Yo sé que reservarás un lugar para el Poeta",
      wordGroups: [
        { wid: "60-0", fr: "Je sais", en: "I know", es: "Yo sé" },
        { wid: "60-1", fr: "gardez", en: "wilt grant", es: "reservarás" },
        { wid: "60-2", fr: "une place", en: "a chair", es: "un lugar" },
        { wid: "60-3", fr: "au Poëte", en: "the poet", es: "el Poeta" },
      ] },
    { id: 61, fr: "Dans les rangs bienheureux des saintes Légions,", en: "Among the Sainted Legion and the Blissful ones,", es: "En las filas bienaventuradas de las Santas Legiones,",
      wordGroups: [
        { wid: "61-0", fr: "Dans", en: "Among", es: "En" },
        { wid: "61-1", fr: "bienheureux", en: "Blissful", es: "bienaventuradas" },
        { wid: "61-2", fr: "saintes", en: "Sainted", es: "Santas" },
        { wid: "61-3", fr: "Légions", en: "Legion", es: "Legiones" },
      ] },
    { id: 62, fr: "Et que vous l’invitez à l’éternelle fête", en: "That of the endless feast thou wilt accord his share", es: "Y que lo invitarás para la eterna fiesta",
      wordGroups: [
        { wid: "62-0", fr: "vous", en: "thou" },
        { wid: "62-1", fr: "l’invitez", en: "wilt accord his share", es: "lo invitarás" },
        { wid: "62-2", fr: "l’éternelle", en: "the endless", es: "la eterna" },
        { wid: "62-3", fr: "fête", en: "feast", es: "fiesta" },
      ] },
    { id: 63, fr: "Des Trônes, des Vertus, des Dominations.", en: "To him, of Virtues, Dominations and of Thrones.\"", es: "De los Tronos, de las Virtudes, de las Dominaciones.",
      wordGroups: [
        { wid: "63-0", fr: "Trônes", en: "Thrones", es: "Tronos" },
        { wid: "63-1", fr: "Vertus", en: "Virtues", es: "Virtudes" },
        { wid: "63-2", fr: "Dominations", en: "Dominations", es: "Dominaciones" },
      ] },
    { id: 64, fr: "Je sais que la douleur est la noblesse unique", en: "\"I know, that Sorrow is that nobleness alone,", es: "Yo sé que el dolor es la nobleza única",
      wordGroups: [
        { wid: "64-0", fr: "Je sais", en: "I know", es: "Yo sé" },
        { wid: "64-1", fr: "la douleur", en: "Sorrow", es: "el dolor" },
        { wid: "64-2", fr: "la noblesse", en: "that nobleness", es: "la nobleza" },
        { wid: "64-3", fr: "unique", en: "alone", es: "única" },
      ] },
    { id: 65, fr: "Où ne mordront jamais la terre et les enfers,", en: "Which never may corrupted be by hell nor curse,", es: "Donde no morderán jamás la tierra y los infiernos,",
      wordGroups: [
        { wid: "65-0", fr: "Où", en: "Which", es: "Donde" },
        { wid: "65-1", fr: "mordront", en: "corrupted", es: "morderán" },
        { wid: "65-2", fr: "jamais", en: "never", es: "jamás" },
        { wid: "65-3", fr: "les enfers", en: "hell", es: "los infiernos" },
      ] },
    { id: 66, fr: "Et qu’il faut pour tresser ma couronne mystique", en: "I know, in order to enwreathe my mystic crown", es: "Y que es menester para trenzar mi corona mística",
      wordGroups: [
        { wid: "66-0", fr: "pour", en: "in order to", es: "para" },
        { wid: "66-1", fr: "tresser", en: "enwreathe", es: "trenzar" },
        { wid: "66-2", fr: "couronne", en: "crown", es: "corona" },
        { wid: "66-3", fr: "mystique", en: "mystic", es: "mística" },
      ] },
    { id: 67, fr: "Imposer tous les temps et tous les univers.", en: "I must inspire the ages and the universe.\"", es: "Imponer todos los tiempos y todos los universos.",
      wordGroups: [
        { wid: "67-0", fr: "Imposer", en: "I must inspire", es: "Imponer" },
        { wid: "67-1", fr: "tous les temps", en: "the ages", es: "todos los tiempos" },
        { wid: "67-2", fr: "les univers", en: "the universe", es: "los universos" },
      ] },
    { id: 68, fr: "Mais les bijoux perdus de l’antique Palmyre,", en: "\"And yet the buried jewels of Palmyra old,", es: "Pero las joyas perdidas de la antigua Palmira,",
      wordGroups: [
        { wid: "68-0", fr: "Mais", en: "And yet", es: "Pero" },
        { wid: "68-1", fr: "bijoux", en: "jewels", es: "joyas" },
        { wid: "68-2", fr: "perdus", en: "buried", es: "perdidas" },
        { wid: "68-3", fr: "l’antique", en: "old", es: "la antigua" },
        { wid: "68-4", fr: "Palmyre", en: "Palmyra", es: "Palmira" },
      ] },
    { id: 69, fr: "Les métaux inconnus, les perles de la mer,", en: "The undiscovered metals and the pearly sea", es: "Los metales desconocidos, las perlas del mar,",
      wordGroups: [
        { wid: "69-0", fr: "métaux", en: "metals", es: "metales" },
        { wid: "69-1", fr: "inconnus", en: "The undiscovered", es: "desconocidos" },
        { wid: "69-2", fr: "les perles", en: "the pearly", es: "las perlas" },
        { wid: "69-3", fr: "de la mer", en: "sea", es: "del mar" },
      ] },
    { id: 70, fr: "Par votre main montés, ne pourraient pas suffire", en: "Of gems, that unto me you show could never hold", es: "Por vuestra mano engarsados, no serían suficientes",
      wordGroups: [
        { wid: "70-0", fr: "ne pourraient pas", en: "could never", es: "no serían" },
        { wid: "70-1", fr: "suffire", en: "hold", es: "suficientes" },
      ] },
    { id: 71, fr: "À ce beau diadème éblouissant et clair ;", en: "Beside this diadem of blinding brilliancy.\"", es: "Para esa hermosa Diadema resplandeciente y diáfana;",
      wordGroups: [
        { wid: "71-0", fr: "À", en: "Beside", es: "Para" },
        { wid: "71-1", fr: "diadème", en: "diadem", es: "Diadema" },
        { wid: "71-2", fr: "éblouissant", en: "blinding", es: "resplandeciente" },
        { wid: "71-3", fr: "clair", en: "brilliancy", es: "diáfana" },
      ] },
    { id: 72, fr: "Car il ne sera fait que de pure lumière,", en: "\"For it shall be engendered from the purest fire", es: "Porque no será hecho más que de pura luz,",
      wordGroups: [
        { wid: "72-0", fr: "Car", en: "For", es: "Porque" },
        { wid: "72-1", fr: "sera fait", en: "shall be engendered", es: "será hecho" },
        { wid: "72-2", fr: "pure", en: "purest", es: "pura" },
        { wid: "72-3", fr: "lumière", en: "fire", es: "luz" },
      ] },
    { id: 73, fr: "Puisée au foyer saint des rayons primitifs,", en: "Of rays primeval, from the holy hearth amassed,", es: "Tomada en el hogar santo de los rayos primitivos,",
      wordGroups: [
        { wid: "73-0", fr: "Puisée", en: "amassed", es: "Tomada" },
        { wid: "73-1", fr: "foyer", en: "hearth", es: "hogar" },
        { wid: "73-2", fr: "saint", en: "holy", es: "santo" },
        { wid: "73-3", fr: "rayons", en: "rays", es: "rayos" },
        { wid: "73-4", fr: "primitifs", en: "primeval", es: "primitivos" },
      ] },
    { id: 74, fr: "Et dont les yeux mortels, dans leur splendeur entière,", en: "Of which the eyes of Mortals, in their sheen entire,", es: "Y del que los ojos mortales, en su esplendor entero,",
      wordGroups: [
        { wid: "74-0", fr: "dont", en: "Of which", es: "del que" },
        { wid: "74-1", fr: "les yeux", en: "the eyes", es: "los ojos" },
        { wid: "74-2", fr: "mortels", en: "Mortals", es: "mortales" },
        { wid: "74-3", fr: "leur splendeur", en: "their sheen", es: "su esplendor" },
        { wid: "74-4", fr: "entière", en: "entire", es: "entero" },
      ] },
    { id: 75, fr: "Ne sont que des miroirs obscurcis et plaintifs ! »", en: "Are but the tarnished mirrors, sad and overcast!\"", es: "¡No son sino espejos oscurecidos y dolientes!\"",
      wordGroups: [
        { wid: "75-0", fr: "Ne sont que", en: "Are but", es: "No son sino" },
        { wid: "75-1", fr: "miroirs", en: "mirrors", es: "espejos" },
        { wid: "75-2", fr: "obscurcis", en: "tarnished", es: "oscurecidos" },
        { wid: "75-3", fr: "plaintifs", en: "sad", es: "dolientes" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};

/* --- Translations by Bravo ---------------------------------------------
   Machine-managed by localhost edit mode (tools/dev-server.mjs). Everything
   from this marker to the end of the file is rewritten wholesale on save.
   Do not hand-edit below this line, and do not append anything after it. */
window.POEMS["benediction"].bravo = {
  "es-bravo": {
    status: "complete",
    title: "Bendición",
    lines: [
      "Cuando, por un decreto de potencias supremas,",
      "El Poeta aparece en esta creación hastiada,",
      "Su madre, horrorizada y llena de blasfemias,",
      "Levanta sus puños contra Dios, quien de ella se apiada:",
      "-« \"¡Ah! ¡por qué no parí un nudo entero de serpientes,",
      "en vez de amamantar esta irrisión!",
      "¡Maldita sea la noche de efímeros placeres",
      "en la cual mi vientre concibió mi expiación!",
      "Puesto que me elegiste de entre todas las mujeres",
      "Por ser el asco de mi triste marido,",
      "Y como no puedo arrojar a las llamas,",
      "Tal carta de amor, este monstruo encogido,",
      "Haré recaer tu odio abrumador",
      "Sobre el vil instrumento de tu mal absoluto,",
      "Y así he de retorcer este árbol malhechor,",
      "¡Para que nunca dé su fétido fruto! »",
      "Ella traga así la espuma del odio que la llena,",
      "Y, sin entender los designios inmortales,",
      "Ella misma prepara en el fondo de la Gehena",
      "Hogueras consagradas a los crímenes maternales.",
      "Sin embargo, bajo la tutela de un Ángel invisible,",
      "El Niño desheredado se embriaga del sol,",
      "Y en todo lo que bebe y en todo lo comestible",
      "Encuentra ambrosía y néctar arrebol.",
      "Él juega con el viento, conversa con el celaje,",
      "Y se embriaga cantando del camino de la cruz;",
      "Y el Espíritu que le sigue en su peregrinaje",
      "Llora al verlo feliz como un pájaro en plena luz.",
      "Todos aquellos que él quiere amar lo observan con espanto,",
      "O bien, envalentonados por su tranquilidad,",
      "Buscan al que sabrá arrancarle un llanto,",
      "Y ensayan contra él su ferocidad.",
      "En el pan y el vino destinados a su boca",
      "Ellos mezclan ceniza con impuros escupitajos;",
      "Con hipocresía desechan lo que él toca,",
      "Y se acusan de haber puesto sus pies en sus pasos.",
      "Su mujer va gritando por las plazas públicas:",
      "«Puesto que halla en mí belleza suficiente para adorarme,",
      "Haré el trabajo de los ídolos antiguos,",
      "Y como ellos quiero que hacerme redorar.",
      "¡Y me embriagaré de nardo, de incienso, de mirra,",
      "De genuflexiones, de carne y de vinos,",
      "Para saber si puedo de un corazón que me admira",
      "Usurpar riendo los homenajes divinos!",
      "Y, cuando me hastíe de estas farsas impías,",
      "Posaré sobre él mi frágil, fuerte mano sin perdón;",
      "Y mis uñas, como garras de arpías,",
      "Sabrán abrirse paso hasta su corazón.",
      "Como un pájaro joven que tiembla y palpita,",
      "Arrancaré ese rojo corazón de su seno,",
      "Y, para saciar mi bestia favorita,",
      "¡Se lo arrojaré al suelo con desdén sereno!»",
      "Hacia el Cielo, donde su ojo ve un trono espléndido,",
      "El Poeta sereno eleva sus brazos piadosos,",
      "Y los vastos destellos de su espíritu lúcido",
      "Le ocultan el aspecto de pueblos furiosos:",
      "— «Bendito seas, mi Dios, que das en tu clemencia",
      "El dolor como santa cura de nuestras inmundicias",
      "Y como la más pura y la mejor esencia",
      "¡Que a los fuertes prepara para santas delicias!",
      "Yo sé que un lugar para el Poeta guardarás",
      "En las filas benditas de las santas Legiones,",
      "Y que a la fiesta eterna lo invitarás",
      "De los Tronos, de las Virtudes, de las Dominaciones.",
      "Sé que el dolor es la nobleza suprema",
      "Que jamás morderán la tierra y los infiernos,",
      "Y que, para tejer mi mística diadema,",
      "he de imponer los tiempos y universos eternos.",
      "Mas de Palmira antigua las joyas ya perdidas,",
      "Los metales incógnitos, las perlas del mar,",
      "Aunque hayan sido por tu mano trenzadas",
      "para esta clara diadema no podrían bastar;",
      "Porque no será hecho sino de la luz más pura,",
      "del santo hogar sacada de aquel primer fulgor,",
      "y los ojos mortales, en toda su hermosura,",
      "¡no son sino sus turbios espejos de dolor! »",
    ],
  },
};
