window.POEMS = window.POEMS || {};

window.POEMS["causerie"] = {
  title: "Causerie",
  titles: { fr: "Causerie", en: "\"Causerie\"", es: "Plática" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Vous êtes un beau ciel d’automne, clair et rose !", en: "You are a roseate autumn-sky, that glows!", es: "¡Eres un hermoso cielo de otoño, claro y rosado!",
      wordGroups: [
        { wid: "0-0", fr: "Vous êtes", en: "You are", es: "Eres" },
        { wid: "0-1", fr: "ciel d’automne", en: "autumn-sky", es: "cielo de otoño" },
        { wid: "0-2", fr: "clair", en: "glows", es: "claro" },
        { wid: "0-3", fr: "rose", en: "roseate", es: "rosado" },
      ] },
    { id: 1, fr: "Mais la tristesse en moi monte comme la mer,", en: "Yet sadness rises in me like the flood,", es: "Pero la tristeza en mí sube como el mar,",
      wordGroups: [
        { wid: "1-0", fr: "Mais", en: "Yet", es: "Pero" },
        { wid: "1-1", fr: "la tristesse", en: "sadness", es: "la tristeza" },
        { wid: "1-2", fr: "en moi", en: "in me", es: "en mí" },
        { wid: "1-3", fr: "monte", en: "rises", es: "sube" },
        { wid: "1-4", fr: "la mer", en: "the flood", es: "el mar" },
      ] },
    { id: 2, fr: "Et laisse, en refluant, sur ma lèvre morose", en: "And leaves in ebbing on my lips morose,", es: "Y deja, al refluir, sobre mi labio moroso",
      wordGroups: [
        { wid: "2-0", fr: "Et", en: "And", es: "Y" },
        { wid: "2-1", fr: "laisse", en: "leaves", es: "deja" },
        { wid: "2-2", fr: "en refluant", en: "in ebbing", es: "al refluir" },
        { wid: "2-3", fr: "ma lèvre", en: "my lips", es: "mi labio" },
        { wid: "2-4", fr: "morose", en: "morose", es: "moroso" },
      ] },
    { id: 3, fr: "Le souvenir cuisant de son limon amer.", en: "The poignant memory of its bitter mind.", es: "El recuerdo penetrante de su limo amargo.",
      wordGroups: [
        { wid: "3-0", fr: "souvenir", en: "memory", es: "recuerdo" },
        { wid: "3-1", fr: "cuisant", en: "poignant", es: "penetrante" },
        { wid: "3-2", fr: "limon", en: "mind", es: "limo" },
        { wid: "3-3", fr: "amer", en: "bitter", es: "amargo" },
      ] },
    { id: 4, fr: "— Ta main se glisse en vain sur mon sein qui se pâme ;", en: "In vain your hands my swooning breast embrace,", es: "—Tu mano se desliza en vano sobre mi pecho que se pasma;",
      wordGroups: [
        { wid: "4-0", fr: "Ta main", en: "your hands", es: "Tu mano" },
        { wid: "4-1", fr: "se glisse", en: "embrace", es: "se desliza" },
        { wid: "4-2", fr: "en vain", en: "In vain", es: "en vano" },
        { wid: "4-3", fr: "sein", en: "breast", es: "pecho" },
        { wid: "4-4", fr: "se pâme", en: "swooning", es: "se pasma" },
      ] },
    { id: 5, fr: "Ce qu’elle cherche, amie, est un lieu saccagé", en: "Oh, friend! alone remains the plundered spot,", es: "Lo que ella busca, amiga, es un lugar saqueado",
      wordGroups: [
        { wid: "5-0", fr: "amie", en: "friend", es: "amiga" },
        { wid: "5-1", fr: "est", en: "remains", es: "es" },
        { wid: "5-2", fr: "un lieu", en: "spot", es: "un lugar" },
        { wid: "5-3", fr: "saccagé", en: "plundered", es: "saqueado" },
      ] },
    { id: 6, fr: "Par la griffe et la dent féroce de la femme.", en: "Where woman's biting grip has left its trace:", es: "Por la garra y el diente feroz de la mujer.",
      wordGroups: [
        { wid: "6-0", fr: "la griffe", en: "grip", es: "la garra" },
        { wid: "6-1", fr: "la dent", en: "biting", es: "el diente" },
        { wid: "6-2", fr: "la femme", en: "woman's", es: "la mujer" },
      ] },
    { id: 7, fr: "Ne cherchez plus mon cœur ; les bêtes l’ont mangé.", en: "My heart, the beasts devoured--seek it not!", es: "No busques más mi corazón; las bestias lo han devorado.",
      wordGroups: [
        { wid: "7-0", fr: "Ne cherchez plus", en: "seek it not", es: "No busques más" },
        { wid: "7-1", fr: "mon cœur", en: "My heart", es: "mi corazón" },
        { wid: "7-2", fr: "les bêtes", en: "the beasts", es: "las bestias" },
        { wid: "7-3", fr: "l’ont mangé", en: "devoured", es: "lo han devorado" },
      ] },
    { id: 8, fr: "Mon cœur est un palais flétri par la cohue ;", en: "My heart is a palace pillaged by the herd;", es: "Mi corazón es un palacio mancillado por el tumulto;",
      wordGroups: [
        { wid: "8-0", fr: "Mon cœur", en: "My heart", es: "Mi corazón" },
        { wid: "8-1", fr: "est", en: "is", es: "es" },
        { wid: "8-2", fr: "un palais", en: "a palace", es: "un palacio" },
        { wid: "8-3", fr: "flétri", en: "pillaged", es: "mancillado" },
        { wid: "8-4", fr: "la cohue", en: "the herd", es: "el tumulto" },
      ] },
    { id: 9, fr: "On s’y soûle, on s’y tue, on s’y prend aux cheveux !", en: "They kill and take each other by the throat!", es: "¡En él se embriagan, se matan, se arrancan los cabellos!",
      wordGroups: [
        { wid: "9-0", fr: "On", en: "They" },
        { wid: "9-1", fr: "tue", en: "kill", es: "matan" },
        { wid: "9-2", fr: "prend", en: "take", es: "arrancan" },
        { wid: "9-3", fr: "aux cheveux", en: "by the throat", es: "los cabellos" },
      ] },
    { id: 10, fr: "— Un parfum nage autour de votre gorge nue !…", en: "A perfume glides around your bosom bared--", es: "—¡Un perfume flota alrededor de tu garganta desnuda!...",
      wordGroups: [
        { wid: "10-0", fr: "Un parfum", en: "A perfume", es: "Un perfume" },
        { wid: "10-1", fr: "nage", en: "glides", es: "flota" },
        { wid: "10-2", fr: "autour", en: "around", es: "alrededor" },
        { wid: "10-3", fr: "votre gorge", en: "your bosom", es: "tu garganta" },
        { wid: "10-4", fr: "nue", en: "bared", es: "desnuda" },
      ] },
    { id: 11, fr: "Ô Beauté, dur fléau des âmes, tu le veux !", en: "O loveliness, thou scourge of souls--devote", es: "¡Oh, Belleza, duro flagelo de las almas, tú lo quieres!",
      wordGroups: [
        { wid: "11-0", fr: "Ô Beauté", en: "O loveliness", es: "Oh, Belleza" },
        { wid: "11-1", fr: "fléau", en: "scourge", es: "flagelo" },
        { wid: "11-2", fr: "des âmes", en: "of souls", es: "de las almas" },
      ] },
    { id: 12, fr: "Avec tes yeux de feu, brillants comme des fêtes,", en: "Thine eyes of fire--luminous-like feasts,", es: "¡Con tus ojos de fuego, brillante como orgías!,",
      wordGroups: [
        { wid: "12-0", fr: "tes yeux", en: "Thine eyes", es: "tus ojos" },
        { wid: "12-1", fr: "de feu", en: "of fire", es: "de fuego" },
        { wid: "12-2", fr: "brillants", en: "luminous", es: "brillante" },
        { wid: "12-3", fr: "comme", en: "like", es: "como" },
        { wid: "12-4", fr: "des fêtes", en: "feasts", es: "orgías" },
      ] },
    { id: 13, fr: "Calcine ces lambeaux qu’ont épargnés les bêtes !", en: "To burn these rags--rejected by the beasts!", es: "¡Calcinas estos jirones que han desdeñado las bestias!",
      wordGroups: [
        { wid: "13-0", fr: "Calcine", en: "To burn", es: "Calcinas" },
        { wid: "13-1", fr: "ces lambeaux", en: "these rags", es: "estos jirones" },
        { wid: "13-2", fr: "épargnés", en: "rejected", es: "desdeñado" },
        { wid: "13-3", fr: "les bêtes", en: "the beasts", es: "las bestias" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
