window.POEMS = window.POEMS || {};

window.POEMS["correspondances"] = {
  title: "Correspondances",
  titles: { fr: "Correspondances", en: "Echoes", es: "Correspondencias" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "La Nature est un temple où de vivants piliers", en: "In Nature's temple, living columns rise,", es: "La Natura es un templo donde vividos pilares",
      wordGroups: [
        { wid: "0-0", fr: "La Nature", en: "Nature's", es: "La Natura" },
        { wid: "0-1", fr: "temple", en: "temple", es: "templo" },
        { wid: "0-2", fr: "vivants", en: "living", es: "vividos" },
        { wid: "0-3", fr: "piliers", en: "columns", es: "pilares" },
      ] },
    { id: 1, fr: "Laissent parfois sortir de confuses paroles ;", en: "Which oftentimes give tongue to words subdued,", es: "Dejan, a veces, brotar confusas palabras;",
      wordGroups: [
        { wid: "1-0", fr: "parfois", en: "oftentimes", es: "a veces" },
        { wid: "1-1", fr: "sortir", en: "give tongue", es: "brotar" },
        { wid: "1-2", fr: "confuses", en: "subdued", es: "confusas" },
        { wid: "1-3", fr: "paroles", en: "words", es: "palabras" },
      ] },
    { id: 2, fr: "L’homme y passe à travers des forêts de symboles", en: "And Man traverses this symbolic wood,", es: "El hombre pasa a través de bosques de símbolos",
      wordGroups: [
        { wid: "2-0", fr: "L’homme", en: "Man", es: "El hombre" },
        { wid: "2-1", fr: "passe à travers", en: "traverses", es: "pasa a través" },
        { wid: "2-2", fr: "forêts", en: "wood", es: "bosques" },
        { wid: "2-3", fr: "symboles", en: "symbolic", es: "símbolos" },
      ] },
    { id: 3, fr: "Qui l’observent avec des regards familiers.", en: "Which looks at him with half familiar eyes,", es: "que lo observan con miradas familiares.",
      wordGroups: [
        { wid: "3-0", fr: "Qui", en: "Which", es: "que" },
        { wid: "3-1", fr: "l’observent", en: "looks at him", es: "lo observan" },
        { wid: "3-2", fr: "regards", en: "eyes", es: "miradas" },
        { wid: "3-3", fr: "familiers", en: "familiar", es: "familiares" },
      ] },
    { id: 4, fr: "Comme de longs échos qui de loin se confondent", en: "Like lingering echoes, which afar confound", es: "Como prolongados ecos que de lejos se confunden",
      wordGroups: [
        { wid: "4-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "4-1", fr: "longs", en: "lingering", es: "prolongados" },
        { wid: "4-2", fr: "échos", en: "echoes", es: "ecos" },
        { wid: "4-3", fr: "de loin", en: "afar", es: "de lejos" },
        { wid: "4-4", fr: "se confondent", en: "confound", es: "se confunden" },
      ] },
    { id: 5, fr: "Dans une ténébreuse et profonde unité,", en: "Themselves in deep and sombre unity,", es: "En una tenebrosa y profunda unidad,",
      wordGroups: [
        { wid: "5-0", fr: "ténébreuse", en: "sombre", es: "tenebrosa" },
        { wid: "5-1", fr: "profonde", en: "deep", es: "profunda" },
        { wid: "5-2", fr: "unité", en: "unity", es: "unidad" },
      ] },
    { id: 6, fr: "Vaste comme la nuit et comme la clarté,", en: "As vast as Night, and like transplendency,", es: "Vasta como la noche y como la claridad,",
      wordGroups: [
        { wid: "6-0", fr: "Vaste", en: "vast", es: "Vasta" },
        { wid: "6-1", fr: "la nuit", en: "Night", es: "la noche" },
        { wid: "6-2", fr: "la clarté", en: "transplendency", es: "la claridad" },
      ] },
    { id: 7, fr: "Les parfums, les couleurs et les sons se répondent.", en: "The scents and colours to each other respond.", es: "Los perfumes, los colores y los sonidos se responden.",
      wordGroups: [
        { wid: "7-0", fr: "Les parfums", en: "The scents", es: "Los perfumes" },
        { wid: "7-1", fr: "les couleurs", en: "colours", es: "los colores" },
        { wid: "7-2", fr: "se répondent", en: "to each other respond", es: "se responden" },
      ] },
    { id: 8, fr: "Il est des parfums frais comme des chairs d’enfants,", en: "And scents there are, like infant's flesh as chaste,", es: "Hay perfumes frescos como carnes de niños,",
      wordGroups: [
        { wid: "8-0", fr: "des parfums", en: "scents", es: "perfumes" },
        { wid: "8-1", fr: "frais", en: "chaste", es: "frescos" },
        { wid: "8-2", fr: "chairs", en: "flesh", es: "carnes" },
        { wid: "8-3", fr: "d’enfants", en: "infant's", es: "de niños" },
      ] },
    { id: 9, fr: "Doux comme les hautbois, verts comme les prairies,", en: "As sweet as oboes, and as meadows fair,", es: "Suaves cual los oboes, verdes como las praderas,",
      wordGroups: [
        { wid: "9-0", fr: "Doux", en: "sweet", es: "Suaves" },
        { wid: "9-1", fr: "les hautbois", en: "oboes", es: "los oboes" },
        { wid: "9-2", fr: "les prairies", en: "meadows", es: "las praderas" },
      ] },
    { id: 10, fr: "— Et d’autres, corrompus, riches et triomphants,", en: "And others, proud, corrupted, rich and vast,", es: "Y otros, corrompidos, ricos y triunfantes,",
      wordGroups: [
        { wid: "10-0", fr: "d’autres", en: "others", es: "otros" },
        { wid: "10-1", fr: "corrompus", en: "corrupted", es: "corrompidos" },
        { wid: "10-2", fr: "riches", en: "rich", es: "ricos" },
        { wid: "10-3", fr: "triomphants", en: "proud", es: "triunfantes" },
      ] },
    { id: 11, fr: "Ayant l’expansion des choses infinies,", en: "Which have the expansion of infinity,", es: "Que tienen la expansión de cosas infinitas,",
      wordGroups: [
        { wid: "11-0", fr: "Ayant", en: "have", es: "tienen" },
        { wid: "11-1", fr: "l’expansion", en: "the expansion", es: "la expansión" },
        { wid: "11-2", fr: "choses infinies", en: "infinity", es: "cosas infinitas" },
      ] },
    { id: 12, fr: "Comme l’ambre, le musc, le benjoin et l’encens,", en: "Like amber, musk and frankincense and myrrh,", es: "Como el ámbar, el almizcle, el benjuí y el incienso,",
      wordGroups: [
        { wid: "12-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "12-1", fr: "l’ambre", en: "amber", es: "el ámbar" },
        { wid: "12-2", fr: "le musc", en: "musk", es: "el almizcle" },
        { wid: "12-3", fr: "l’encens", en: "frankincense", es: "el incienso" },
      ] },
    { id: 13, fr: "Qui chantent les transports de l’esprit et des sens.", en: "That sing the soul's and senses' ecstasy.", es: "Que cantan los transportes del espíritu y de los sentidos.",
      wordGroups: [
        { wid: "13-0", fr: "Qui", en: "That", es: "Que" },
        { wid: "13-1", fr: "chantent", en: "sing", es: "cantan" },
        { wid: "13-2", fr: "les transports", en: "ecstasy", es: "los transportes" },
        { wid: "13-3", fr: "l’esprit", en: "the soul's", es: "espíritu" },
        { wid: "13-4", fr: "des sens", en: "senses'", es: "los sentidos" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
