window.POEMS = window.POEMS || {};

window.POEMS["harmonie-du-soir"] = {
  title: "Harmonie du soir",
  titles: { fr: "Harmonie du soir", en: "Evening Harmony", es: "Armonía de la tarde" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Voici venir les temps où vibrant sur sa tige", en: "The hour approacheth, when, as their stems incline,", es: "He aquí que llega el tiempo en que vibrante en su tallo",
      wordGroups: [
        { wid: "0-0", fr: "Voici venir", en: "approacheth", es: "He aquí que llega" },
        { wid: "0-1", fr: "les temps", en: "The hour", es: "el tiempo" },
        { wid: "0-2", fr: "sur sa tige", en: "their stems", es: "en su tallo" },
      ] },
    { id: 1, fr: "Chaque fleur s’évapore ainsi qu’un encensoir ;", en: "The flowers evaporate like an incense urn,", es: "Cada flor se evapora cual un incensario;",
      wordGroups: [
        { wid: "1-0", fr: "Chaque fleur", en: "The flowers", es: "Cada flor" },
        { wid: "1-1", fr: "s’évapore", en: "evaporate", es: "se evapora" },
        { wid: "1-2", fr: "ainsi qu’un", en: "like an", es: "cual un" },
        { wid: "1-3", fr: "encensoir", en: "incense urn", es: "incensario" },
      ] },
    { id: 2, fr: "Les sons et les parfums tournent dans l’air du soir ;", en: "And sounds and scents in the vesper breezes turn;", es: "Los sonidos y los perfumes giran en el aire de la tarde,",
      wordGroups: [
        { wid: "2-0", fr: "Les sons", en: "sounds", es: "Los sonidos" },
        { wid: "2-1", fr: "les parfums", en: "scents", es: "los perfumes" },
        { wid: "2-2", fr: "tournent", en: "turn", es: "giran" },
        { wid: "2-3", fr: "l’air du soir", en: "the vesper breezes", es: "el aire de la tarde" },
      ] },
    { id: 3, fr: "Valse mélancolique et langoureux vertige !", en: "A melancholy waltz--and a drowsiness divine.", es: "¡Vals melancólico y lánguido vértigo!",
      wordGroups: [
        { wid: "3-0", fr: "Valse", en: "waltz", es: "Vals" },
        { wid: "3-1", fr: "mélancolique", en: "melancholy", es: "melancólico" },
        { wid: "3-2", fr: "langoureux vertige", en: "a drowsiness divine", es: "lánguido vértigo" },
      ] },
    { id: 4, fr: "Chaque fleur s’évapore ainsi qu’un encensoir ;", en: "The flowers evaporate like an incense urn,", es: "Cada flor se evapora cual un incensario;",
      wordGroups: [
        { wid: "4-0", fr: "Chaque fleur", en: "The flowers", es: "Cada flor" },
        { wid: "4-1", fr: "s’évapore", en: "evaporate", es: "se evapora" },
        { wid: "4-2", fr: "ainsi qu’un", en: "like an", es: "cual un" },
        { wid: "4-3", fr: "encensoir", en: "incense urn", es: "incensario" },
      ] },
    { id: 5, fr: "Le violon frémit comme un cœur qu’on afflige ;", en: "The viol vibrates like the wailing of souls that repine.", es: "El violín vibra como un corazón afligido;",
      wordGroups: [
        { wid: "5-0", fr: "Le violon", en: "The viol", es: "El violín" },
        { wid: "5-1", fr: "frémit", en: "vibrates", es: "vibra" },
        { wid: "5-2", fr: "comme", en: "like", es: "como" },
        { wid: "5-3", fr: "un cœur", en: "souls", es: "un corazón" },
        { wid: "5-4", fr: "qu’on afflige", en: "that repine", es: "afligido" },
      ] },
    { id: 6, fr: "Valse mélancolique et langoureux vertige !", en: "A melancholy waltz--and a drowsiness divine,", es: "¡Vals melancólico y lánguido vértigo!",
      wordGroups: [
        { wid: "6-0", fr: "Valse", en: "waltz", es: "Vals" },
        { wid: "6-1", fr: "mélancolique", en: "melancholy", es: "melancólico" },
        { wid: "6-2", fr: "langoureux vertige", en: "a drowsiness divine", es: "lánguido vértigo" },
      ] },
    { id: 7, fr: "Le ciel est triste et beau comme un grand reposoir.", en: "The skies like a mosque are beautiful and stern.", es: "El cielo está triste y bello como un gran altar.",
      wordGroups: [
        { wid: "7-0", fr: "Le ciel", en: "The skies", es: "El cielo" },
        { wid: "7-1", fr: "triste", en: "stern", es: "triste" },
        { wid: "7-2", fr: "beau", en: "beautiful", es: "bello" },
        { wid: "7-3", fr: "un grand reposoir", en: "a mosque", es: "un gran altar" },
      ] },
    { id: 8, fr: "Le violon frémit comme un cœur qu’on afflige,", en: "The viol vibrates like the wailing of souls that repine;", es: "El violín vibra como un corazón afligido,",
      wordGroups: [
        { wid: "8-0", fr: "Le violon", en: "The viol", es: "El violín" },
        { wid: "8-1", fr: "frémit", en: "vibrates", es: "vibra" },
        { wid: "8-2", fr: "comme", en: "like", es: "como" },
        { wid: "8-3", fr: "un cœur", en: "souls", es: "un corazón" },
        { wid: "8-4", fr: "qu’on afflige", en: "that repine", es: "afligido" },
      ] },
    { id: 9, fr: "Un cœur tendre, qui hait le néant vaste et noir !", en: "Sweet souls that shrink from chaos vast and etern,", es: "¡Un corazón tierno que odia la nada vasta y negra!",
      wordGroups: [
        { wid: "9-0", fr: "Un cœur tendre", en: "Sweet souls", es: "Un corazón tierno" },
        { wid: "9-1", fr: "qui hait", en: "that shrink from", es: "que odia" },
        { wid: "9-2", fr: "le néant", en: "chaos", es: "la nada" },
        { wid: "9-3", fr: "vaste", en: "vast", es: "vasta" },
      ] },
    { id: 10, fr: "Le ciel est triste et beau comme un grand reposoir ;", en: "The skies like a mosque are beautiful and stern,", es: "El cielo está triste y bello como un gran altar;",
      wordGroups: [
        { wid: "10-0", fr: "Le ciel", en: "The skies", es: "El cielo" },
        { wid: "10-1", fr: "triste", en: "stern", es: "triste" },
        { wid: "10-2", fr: "beau", en: "beautiful", es: "bello" },
        { wid: "10-3", fr: "un grand reposoir", en: "a mosque", es: "un gran altar" },
      ] },
    { id: 11, fr: "Le soleil s’est noyé dans son sang qui se fige.", en: "The sunset drowns within its blood-red brine.", es: "El sol se ha ahogado en su sangre coagulada.",
      wordGroups: [
        { wid: "11-0", fr: "Le soleil", en: "The sunset", es: "El sol" },
        { wid: "11-1", fr: "s’est noyé", en: "drowns", es: "se ha ahogado" },
        { wid: "11-2", fr: "son sang", en: "its blood-red brine", es: "su sangre" },
      ] },
    { id: 12, fr: "Un cœur tendre, qui hait le néant vaste et noir,", en: "Sweet souls that shrink from chaos vast and etern,", es: "Un corazón tierno, que odia la nada vasta y negra,",
      wordGroups: [
        { wid: "12-0", fr: "Un cœur tendre", en: "Sweet souls", es: "Un corazón tierno" },
        { wid: "12-1", fr: "qui hait", en: "that shrink from", es: "que odia" },
        { wid: "12-2", fr: "le néant", en: "chaos", es: "la nada" },
        { wid: "12-3", fr: "vaste", en: "vast", es: "vasta" },
      ] },
    { id: 13, fr: "Du passé lumineux recueille tout vestige !", en: "Essay the wreaths of their faded Past to entwine,", es: "¡Del pasado luminoso recobra todo vestigio!",
      wordGroups: [
        { wid: "13-0", fr: "Du passé", en: "their faded Past", es: "Del pasado" },
      ] },
    { id: 14, fr: "Le soleil s’est noyé dans son sang qui se fige……", en: "The sunset drowns within its blood-red brine,", es: "El sol se ha ahogado en su sangre coagulada...",
      wordGroups: [
        { wid: "14-0", fr: "Le soleil", en: "The sunset", es: "El sol" },
        { wid: "14-1", fr: "s’est noyé", en: "drowns", es: "se ha ahogado" },
        { wid: "14-2", fr: "son sang", en: "its blood-red brine", es: "su sangre" },
      ] },
    { id: 15, fr: "Ton souvenir en moi luit comme un ostensoir !", en: "Thy thought within me glows like an incense urn.", es: "¡Tu recuerdo en mí luce como una custodia!",
      wordGroups: [
        { wid: "15-0", fr: "Ton souvenir", en: "Thy thought", es: "Tu recuerdo" },
        { wid: "15-1", fr: "en moi", en: "within me", es: "en mí" },
        { wid: "15-2", fr: "luit", en: "glows", es: "luce" },
        { wid: "15-3", fr: "comme un", en: "like an", es: "como una" },
        { wid: "15-4", fr: "ostensoir", en: "incense urn", es: "custodia" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
