window.POEMS = window.POEMS || {};

window.POEMS["l-ennemi"] = {
  title: "L’Ennemi",
  titles: { fr: "L’Ennemi", en: "The Enemy", es: "El enemigo" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Ma jeunesse ne fut qu’un ténébreux orage,", en: "My childhood was nought but a ravaging storm,", es: "Mi juventud no fue sino una tenebrosa borrasca,",
      wordGroups: [
        { wid: "0-0", fr: "Ma", en: "My", es: "Mi" },
        { wid: "0-1", fr: "jeunesse", en: "childhood", es: "juventud" },
        { wid: "0-2", fr: "fut", en: "was", es: "fue" },
        { wid: "0-3", fr: "orage", en: "storm", es: "borrasca" },
      ] },
    { id: 1, fr: "Traversé çà et là par de brillants soleils ;", en: "Enlivened at times by a brilliant sun;", es: "Atravesada aquí y allá por brillantes soles;",
      wordGroups: [
        { wid: "1-0", fr: "Traversé", en: "Enlivened", es: "Atravesada" },
        { wid: "1-1", fr: "par", en: "by", es: "por" },
        { wid: "1-2", fr: "brillants", en: "brilliant", es: "brillantes" },
        { wid: "1-3", fr: "soleils", en: "sun", es: "soles" },
      ] },
    { id: 2, fr: "Le tonnerre et la pluie ont fait un tel ravage,", en: "The rain and the winds wrought such havoc and harm", es: "El trueno y la lluvia han hecho tal desastre,",
      wordGroups: [
        { wid: "2-0", fr: "la pluie", en: "The rain", es: "la lluvia" },
        { wid: "2-1", fr: "ont fait", en: "wrought", es: "han hecho" },
        { wid: "2-2", fr: "un tel", en: "such", es: "tal" },
        { wid: "2-3", fr: "ravage", en: "havoc", es: "desastre" },
      ] },
    { id: 3, fr: "Qu’il reste en mon jardin bien peu de fruits vermeils.", en: "That of buds on my plot there remains hardly one.", es: "Que restan en mi jardín muy pocos frutos bermejos.",
      wordGroups: [
        { wid: "3-0", fr: "reste", en: "remains", es: "restan" },
        { wid: "3-1", fr: "mon jardin", en: "my plot", es: "mi jardín" },
        { wid: "3-2", fr: "bien peu", en: "hardly one", es: "muy pocos" },
        { wid: "3-3", fr: "fruits", en: "buds", es: "frutos" },
      ] },
    { id: 4, fr: "Voilà que j’ai touché l’automne des idées,", en: "Behold now the Fall of ideas I have reached,", es: "He aquí que he llegado al otoño de las ideas,",
      wordGroups: [
        { wid: "4-0", fr: "Voilà", en: "Behold", es: "He aquí" },
        { wid: "4-1", fr: "j’ai touché", en: "I have reached", es: "he llegado" },
        { wid: "4-2", fr: "l’automne", en: "the Fall", es: "otoño" },
        { wid: "4-3", fr: "idées", en: "ideas", es: "ideas" },
      ] },
    { id: 5, fr: "Et qu’il faut employer la pelle et les râteaux", en: "And the shovel and rake one must therefore resume,", es: "Y que es preciso emplear la pala y los rastrillos",
      wordGroups: [
        { wid: "5-0", fr: "il faut", en: "one must", es: "es preciso" },
        { wid: "5-1", fr: "employer", en: "resume", es: "emplear" },
        { wid: "5-2", fr: "la pelle", en: "the shovel", es: "la pala" },
        { wid: "5-3", fr: "les râteaux", en: "rake", es: "los rastrillos" },
      ] },
    { id: 6, fr: "Pour rassembler à neuf les terres inondées,", en: "In collecting the turf, inundated and breached,", es: "Para acomodar de nuevo las tierras inundadas,",
      wordGroups: [
        { wid: "6-0", fr: "rassembler", en: "collecting", es: "acomodar" },
        { wid: "6-1", fr: "les terres", en: "the turf", es: "las tierras" },
        { wid: "6-2", fr: "inondées", en: "inundated", es: "inundadas" },
      ] },
    { id: 7, fr: "Où l’eau creuse des trous grands comme des tombeaux.", en: "Where the waters dug trenches as deep as a tomb.", es: "Donde el agua horada hoyos grandes como tumbas.",
      wordGroups: [
        { wid: "7-0", fr: "Où", en: "Where", es: "Donde" },
        { wid: "7-1", fr: "l’eau", en: "the waters", es: "el agua" },
        { wid: "7-2", fr: "creuse", en: "dug", es: "horada" },
        { wid: "7-3", fr: "trous", en: "trenches", es: "hoyos" },
        { wid: "7-4", fr: "tombeaux", en: "tomb", es: "tumbas" },
      ] },
    { id: 8, fr: "Et qui sait si les fleurs nouvelles que je rêve", en: "And yet these new blossoms, for which I craved,", es: "Y ¿quién sabe si las flores nuevas con que sueño",
      wordGroups: [
        { wid: "8-0", fr: "Et", en: "And", es: "Y" },
        { wid: "8-1", fr: "les fleurs", en: "blossoms", es: "las flores" },
        { wid: "8-2", fr: "nouvelles", en: "new", es: "nuevas" },
        { wid: "8-3", fr: "je rêve", en: "I craved", es: "sueño" },
      ] },
    { id: 9, fr: "Trouveront dans ce sol lavé comme une grève", en: "Will they find in this earth--like a shore that is laved--", es: "Encontrarán en este suelo lavado como una playa",
      wordGroups: [
        { wid: "9-0", fr: "Trouveront", en: "Will they find", es: "Encontrarán" },
        { wid: "9-1", fr: "dans ce sol", en: "in this earth", es: "en este suelo" },
        { wid: "9-2", fr: "lavé", en: "laved", es: "lavado" },
        { wid: "9-3", fr: "comme", en: "like", es: "como" },
        { wid: "9-4", fr: "grève", en: "a shore", es: "playa" },
      ] },
    { id: 10, fr: "Le mystique aliment qui ferait leur vigueur ?", en: "The mystical fuel which vigour imparts?", es: "El místico alimento que haría su vigor?",
      wordGroups: [
        { wid: "10-0", fr: "mystique", en: "mystical", es: "místico" },
        { wid: "10-1", fr: "aliment", en: "fuel", es: "alimento" },
        { wid: "10-2", fr: "qui", en: "which", es: "que" },
        { wid: "10-3", fr: "vigueur", en: "vigour", es: "vigor" },
      ] },
    { id: 11, fr: "— Ô douleur ! ô douleur ! Le Temps mange la vie,", en: "Oh misery!--Time devours our lives,", es: "— ¡Oh, dolor! ¡Oh, dolor! ¡El Tiempo devora la vida,",
      wordGroups: [
        { wid: "11-0", fr: "Ô douleur", en: "Oh misery", es: "¡Oh, dolor!" },
        { wid: "11-1", fr: "Le Temps", en: "Time", es: "El Tiempo" },
        { wid: "11-2", fr: "mange", en: "devours", es: "devora" },
        { wid: "11-3", fr: "la vie", en: "our lives", es: "la vida" },
      ] },
    { id: 12, fr: "Et l’obscur Ennemi qui nous ronge le cœur", en: "And the enemy black, which consumeth our hearts", es: "Y el oscuro Enemigo que nos roe el corazón",
      wordGroups: [
        { wid: "12-0", fr: "l’obscur", en: "black", es: "el oscuro" },
        { wid: "12-1", fr: "Ennemi", en: "enemy", es: "Enemigo" },
        { wid: "12-2", fr: "qui", en: "which", es: "que" },
        { wid: "12-3", fr: "ronge", en: "consumeth", es: "roe" },
        { wid: "12-4", fr: "cœur", en: "hearts", es: "corazón" },
      ] },
    { id: 13, fr: "Du sang que nous perdons croît et se fortifie !", en: "On the blood of our bodies, increases and thrives!", es: "Con la sangre que perdemos crece y se fortifica!",
      wordGroups: [
        { wid: "13-0", fr: "Du sang", en: "the blood", es: "la sangre" },
        { wid: "13-1", fr: "nous", en: "our" },
        { wid: "13-2", fr: "croît", en: "increases", es: "crece" },
        { wid: "13-3", fr: "se fortifie", en: "thrives", es: "se fortifica" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
