window.POEMS = window.POEMS || {};

window.POEMS["l-horloge"] = {
  title: "L’Horloge",
  titles: { fr: "L’Horloge" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/L%E2%80%99Horloge",
  },
  segments: [
    { id: 0, fr: "Horloge ! dieu sinistre, effrayant, impassible," },
    { id: 1, fr: "Dont le doigt nous menace et nous dit : « Souviens-toi !" },
    { id: 2, fr: "Les vibrantes Douleurs dans ton cœur plein d’effroi" },
    { id: 3, fr: "Se planteront bientôt comme dans une cible ;" },
    { id: 4, fr: "Le Plaisir vaporeux fuira vers l’horizon" },
    { id: 5, fr: "Ainsi qu’une sylphide au fond de la coulisse ;" },
    { id: 6, fr: "Chaque instant te dévore un morceau du délice" },
    { id: 7, fr: "À chaque homme accordé pour toute sa saison." },
    { id: 8, fr: "Trois mille six cents fois par heure, la Seconde" },
    { id: 9, fr: "Chuchote : Souviens-toi ! — Rapide, avec sa voix" },
    { id: 10, fr: "D’insecte, Maintenant dit : Je suis Autrefois," },
    { id: 11, fr: "Et j’ai pompé ta vie avec ma trompe immonde !" },
    { id: 12, fr: "Remember ! Souviens-toi, prodigue ! Esto memor !" },
    { id: 13, fr: "(Mon gosier de métal parle toutes les langues.)" },
    { id: 14, fr: "Les minutes, mortel folâtre, sont des gangues" },
    { id: 15, fr: "Qu’il ne faut pas lâcher sans en extraire l’or !" },
    { id: 16, fr: "Souviens-toi que le Temps est un joueur avide" },
    { id: 17, fr: "Qui gagne sans tricher, à tout coup ! c’est la loi." },
    { id: 18, fr: "Le jour décroît ; la nuit augmente ; souviens-toi !" },
    { id: 19, fr: "Le gouffre a toujours soif ; la clepsydre se vide." },
    { id: 20, fr: "Tantôt sonnera l’heure où le divin Hasard," },
    { id: 21, fr: "Où l’auguste Vertu, ton épouse encor vierge," },
    { id: 22, fr: "Où le Repentir même (oh ! la dernière auberge !)," },
    { id: 23, fr: "Où tout te dira : Meurs, vieux lâche ! il est trop tard ! »" },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
