window.POEMS = window.POEMS || {};

window.POEMS["l-ideal"] = {
  title: "L’Idéal",
  titles: { fr: "L’Idéal", en: "The Ideal", es: "El ideal" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Ce ne seront jamais ces beautés de vignettes,", en: "It could ne'er be those beauties of ivory vignettes;", es: "No serán jamás esas beldades de viñetas,",
      wordGroups: [
        { wid: "0-0", fr: "ne seront jamais", en: "could ne'er be", es: "No serán jamás" },
        { wid: "0-1", fr: "ces beautés", en: "those beauties", es: "esas beldades" },
        { wid: "0-2", fr: "de vignettes", en: "of ivory vignettes", es: "de viñetas" },
      ] },
    { id: 1, fr: "Produits avariés, nés d’un siècle vaurien,", en: "The varied display of a worthless age,", es: "Productos averiados, nacidos de un siglo bribón,",
      wordGroups: [
        { wid: "1-0", fr: "Produits avariés", en: "The varied display", es: "Productos averiados" },
        { wid: "1-1", fr: "siècle", en: "age", es: "siglo" },
        { wid: "1-2", fr: "vaurien", en: "worthless", es: "bribón" },
      ] },
    { id: 2, fr: "Ces pieds à brodequins, ces doigts à castagnettes,", en: "Nor puppet-like figures with castonets,", es: "Esos pies con borceguíes, esos dedos con castañuelas,",
      wordGroups: [
        { wid: "2-0", fr: "Ces pieds à brodequins", en: "puppet-like figures", es: "Esos pies con borceguíes" },
        { wid: "2-1", fr: "castagnettes", en: "castonets", es: "castañuelas" },
      ] },
    { id: 3, fr: "Qui sauront satisfaire un cœur comme le mien.", en: "That ever an heart like mine could engage.", es: "Los que logren satisfacer un corazón como el mío.",
      wordGroups: [
        { wid: "3-0", fr: "Qui", en: "That", es: "Los que" },
        { wid: "3-1", fr: "satisfaire", en: "engage", es: "satisfacer" },
        { wid: "3-2", fr: "un cœur", en: "an heart", es: "un corazón" },
        { wid: "3-3", fr: "comme le mien", en: "like mine", es: "como el mío" },
      ] },
    { id: 4, fr: "Je laisse à Gavarni, poëte des chloroses,", en: "I leave to Gavarni, that poet of chlorosis,", es: "Le dejo a Gavarni, poeta de clorosis,",
      wordGroups: [
        { wid: "4-0", fr: "Je laisse", en: "I leave", es: "Le dejo" },
        { wid: "4-1", fr: "à Gavarni", en: "to Gavarni", es: "a Gavarni" },
        { wid: "4-2", fr: "poëte", en: "poet", es: "poeta" },
        { wid: "4-3", fr: "des chloroses", en: "of chlorosis", es: "de clorosis" },
      ] },
    { id: 5, fr: "Son troupeau gazouillant de beautés d’hôpital,", en: "His hospital-beauties in troups that whirl,", es: "Su tropel gorjeante de beldades de hospital,",
      wordGroups: [
        { wid: "5-0", fr: "Son troupeau", en: "in troups", es: "Su tropel" },
        { wid: "5-1", fr: "de beautés d’hôpital", en: "His hospital-beauties", es: "de beldades de hospital" },
      ] },
    { id: 6, fr: "Car je ne puis trouver parmi ces pâles roses", en: "For I cannot discover amid his pale roses", es: "Porque no puedo hallar entre esas pálidas rosas",
      wordGroups: [
        { wid: "6-0", fr: "Car", en: "For", es: "Porque" },
        { wid: "6-1", fr: "je ne puis", en: "I cannot", es: "no puedo" },
        { wid: "6-2", fr: "trouver", en: "discover", es: "hallar" },
        { wid: "6-3", fr: "parmi", en: "amid", es: "entre" },
        { wid: "6-4", fr: "ces pâles roses", en: "his pale roses", es: "esas pálidas rosas" },
      ] },
    { id: 7, fr: "Une fleur qui ressemble à mon rouge idéal.", en: "A flower to resemble my scarlet ideal.", es: "Una flor que se parezca a mi rojo ideal.",
      wordGroups: [
        { wid: "7-0", fr: "Une fleur", en: "A flower", es: "Una flor" },
        { wid: "7-1", fr: "ressemble", en: "to resemble", es: "se parezca" },
        { wid: "7-2", fr: "rouge", en: "scarlet", es: "rojo" },
        { wid: "7-3", fr: "idéal", en: "ideal", es: "ideal" },
      ] },
    { id: 8, fr: "Ce qu’il faut à ce cœur profond comme un abîme,", en: "Since, what for this fathomless heart I require", es: "Lo que necesita este corazón profundo como un abismo,",
      wordGroups: [
        { wid: "8-0", fr: "Ce qu’il", en: "what", es: "Lo que" },
        { wid: "8-1", fr: "faut", en: "I require", es: "necesita" },
        { wid: "8-2", fr: "ce cœur", en: "heart", es: "este corazón" },
        { wid: "8-3", fr: "profond comme un abîme", en: "fathomless", es: "profundo como un abismo" },
      ] },
    { id: 9, fr: "C’est vous, Lady Macbeth, âme puissante au crime,", en: "Is--Lady Macbeth you! in crime so dire;", es: "Eres tú, Lady Macbeth, alma poderosa en el crimen,",
      wordGroups: [
        { wid: "9-0", fr: "C’est", en: "Is", es: "Eres" },
        { wid: "9-1", fr: "vous", en: "you", es: "tú" },
        { wid: "9-2", fr: "Lady Macbeth", en: "Lady Macbeth", es: "Lady Macbeth" },
        { wid: "9-3", fr: "au crime", en: "in crime", es: "en el crimen" },
      ] },
    { id: 10, fr: "Rêve d’Eschyle éclos au climat des autans ;", en: "--An Æschylus dream transposed from the South--", es: "Sueño de Esquilo abierto al clima de los austros;",
      wordGroups: [
        { wid: "10-0", fr: "Rêve", en: "dream", es: "Sueño" },
        { wid: "10-1", fr: "d’Eschyle", en: "Æschylus", es: "de Esquilo" },
        { wid: "10-2", fr: "au climat des autans", en: "from the South", es: "al clima de los austros" },
      ] },
    { id: 11, fr: "Ou bien toi, grande Nuit, fille de Michel-Ange,", en: "Or thee, oh great \"Night\" of Michael-Angelo born,", es: "¡Oh bien tú, Noche inmensa, hija de Miguel Ángel,",
      wordGroups: [
        { wid: "11-0", fr: "Ou bien", en: "Or", es: "Oh bien" },
        { wid: "11-1", fr: "toi", en: "thee", es: "tú" },
        { wid: "11-2", fr: "grande", en: "great", es: "inmensa" },
        { wid: "11-3", fr: "Nuit", en: "Night", es: "Noche" },
        { wid: "11-4", fr: "fille de Michel-Ange", en: "of Michael-Angelo born", es: "hija de Miguel Ángel" },
      ] },
    { id: 12, fr: "Qui tors paisiblement dans une pose étrange", en: "Who so calmly thy limbs in strange posture hath drawn,", es: "Que tuerces plácidamente en una pose extraña",
      wordGroups: [
        { wid: "12-0", fr: "Qui", en: "Who", es: "Que" },
        { wid: "12-1", fr: "tors", en: "hath drawn", es: "tuerces" },
        { wid: "12-2", fr: "paisiblement", en: "so calmly", es: "plácidamente" },
        { wid: "12-3", fr: "une pose étrange", en: "strange posture", es: "una pose extraña" },
      ] },
    { id: 13, fr: "Tes appas façonnés aux bouches des Titans !", en: "Whose allurements are framed for a Titan's mouth.", es: "Tus gracias concebidas para bocas de Titanes!",
      wordGroups: [
        { wid: "13-0", fr: "Tes appas", en: "Whose allurements", es: "Tus gracias" },
        { wid: "13-1", fr: "façonnés", en: "are framed", es: "concebidas" },
        { wid: "13-2", fr: "aux bouches", en: "mouth", es: "para bocas" },
        { wid: "13-3", fr: "des Titans", en: "a Titan's", es: "de Titanes" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
