window.POEMS = window.POEMS || {};

window.POEMS["la-beaute"] = {
  title: "La Beauté",
  titles: { fr: "La Beauté", en: "Beauty", es: "La belleza" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Je suis belle, ô mortels ! comme un rêve de pierre,", en: "I am lovely, O mortals, like a dream of stone,", es: "Soy hermosa, ¡oh, mortales! cual un sueño de piedra,",
      wordGroups: [
        { wid: "0-0", fr: "Je suis belle", en: "I am lovely", es: "Soy hermosa" },
        { wid: "0-1", fr: "ô mortels", en: "O mortals", es: "oh, mortales" },
        { wid: "0-2", fr: "comme", en: "like", es: "cual" },
        { wid: "0-3", fr: "un rêve", en: "a dream", es: "un sueño" },
        { wid: "0-4", fr: "de pierre", en: "of stone", es: "de piedra" },
      ] },
    { id: 1, fr: "Et mon sein, où chacun s’est meurtri tour à tour,", en: "And my bosom, where each one gets bruised in turn,", es: "Y mi pecho, en el que cada uno se ha magullado a su vez,",
      wordGroups: [
        { wid: "1-0", fr: "mon sein", en: "my bosom", es: "mi pecho" },
        { wid: "1-1", fr: "où", en: "where", es: "en el que" },
        { wid: "1-2", fr: "chacun", en: "each one", es: "cada uno" },
        { wid: "1-3", fr: "s’est meurtri", en: "gets bruised", es: "se ha magullado" },
        { wid: "1-4", fr: "tour à tour", en: "in turn", es: "a su vez" },
      ] },
    { id: 2, fr: "Est fait pour inspirer au poëte un amour", en: "To inspire the love of a poet is prone,", es: "Está hecho para inspirar al poeta un amor",
      wordGroups: [
        { wid: "2-0", fr: "Est fait pour", en: "is prone", es: "Está hecho para" },
        { wid: "2-1", fr: "inspirer", en: "To inspire", es: "inspirar" },
        { wid: "2-2", fr: "au poëte", en: "of a poet", es: "al poeta" },
        { wid: "2-3", fr: "un amour", en: "the love", es: "un amor" },
      ] },
    { id: 3, fr: "Éternel et muet ainsi que la matière.", en: "Like matter eternally silent and stern.", es: "Eterno y mudo así como la materia.",
      wordGroups: [
        { wid: "3-0", fr: "Éternel", en: "eternally", es: "Eterno" },
        { wid: "3-1", fr: "muet", en: "silent", es: "mudo" },
        { wid: "3-2", fr: "ainsi que", en: "Like", es: "así como" },
        { wid: "3-3", fr: "la matière", en: "matter", es: "la materia" },
      ] },
    { id: 4, fr: "Je trône dans l’azur comme un sphinx incompris ;", en: "As an unfathomed sphinx, enthroned by the Nile,", es: "Tengo mi trono en el azar cual una esfinge incomprendida;",
      wordGroups: [
        { wid: "4-0", fr: "Je trône", en: "enthroned", es: "Tengo mi trono" },
        { wid: "4-1", fr: "comme", en: "As", es: "cual" },
        { wid: "4-2", fr: "un sphinx", en: "sphinx", es: "una esfinge" },
        { wid: "4-3", fr: "incompris", en: "unfathomed", es: "incomprendida" },
      ] },
    { id: 5, fr: "J’unis un cœur de neige à la blancheur des cygnes ;", en: "My heart a swan's whiteness with granite combines,", es: "Uno un corazón de nieve a la blancura de los cisnes;",
      wordGroups: [
        { wid: "5-0", fr: "J’unis", en: "combines", es: "Uno" },
        { wid: "5-1", fr: "un cœur", en: "My heart", es: "un corazón" },
        { wid: "5-2", fr: "la blancheur", en: "whiteness", es: "la blancura" },
        { wid: "5-3", fr: "des cygnes", en: "a swan's", es: "de los cisnes" },
      ] },
    { id: 6, fr: "Je hais le mouvement qui déplace les lignes,", en: "And I hate every movement, displacing the lines,", es: "Aborrezco el movimiento que desplaza las líneas,",
      wordGroups: [
        { wid: "6-0", fr: "Je hais", en: "I hate", es: "Aborrezco" },
        { wid: "6-1", fr: "le mouvement", en: "every movement", es: "el movimiento" },
        { wid: "6-2", fr: "déplace", en: "displacing", es: "desplaza" },
        { wid: "6-3", fr: "les lignes", en: "the lines", es: "las líneas" },
      ] },
    { id: 7, fr: "Et jamais je ne pleure et jamais je ne ris.", en: "And never I weep and never I smile.", es: "Y jamás lloro y jamás río.",
      wordGroups: [
        { wid: "7-0", fr: "Et", en: "And", es: "Y" },
        { wid: "7-1", fr: "jamais je ne pleure", en: "never I weep", es: "jamás lloro" },
        { wid: "7-2", fr: "jamais je ne ris", en: "never I smile", es: "jamás río" },
      ] },
    { id: 8, fr: "Les poëtes, devant mes grandes attitudes,", en: "The poets in front of mine attitudes fine", es: "Los poetas, ante mis ampulosas actitudes,",
      wordGroups: [
        { wid: "8-0", fr: "Les poëtes", en: "The poets", es: "Los poetas" },
        { wid: "8-1", fr: "devant", en: "in front of", es: "ante" },
        { wid: "8-2", fr: "mes", en: "mine", es: "mis" },
        { wid: "8-3", fr: "grandes", en: "fine", es: "ampulosas" },
        { wid: "8-4", fr: "attitudes", en: "attitudes", es: "actitudes" },
      ] },
    { id: 9, fr: "Que j’ai l’air d’emprunter aux plus fiers monuments,", en: "(Which the proudest of monuments seem to implant),", es: "Que parezco copiar de los más altivos monumentos,",
      wordGroups: [
        { wid: "9-0", fr: "j’ai l’air d’emprunter", en: "seem to implant", es: "parezco copiar" },
        { wid: "9-1", fr: "plus fiers", en: "proudest", es: "más altivos" },
        { wid: "9-2", fr: "monuments", en: "monuments", es: "monumentos" },
      ] },
    { id: 10, fr: "Consumeront leurs jours en d’austères études ;", en: "To studies profound all their moments assign,", es: "consumirán sus días en austeros estudios;",
      wordGroups: [
        { wid: "10-0", fr: "Consumeront", en: "assign", es: "consumirán" },
        { wid: "10-1", fr: "leurs jours", en: "their moments", es: "sus días" },
        { wid: "10-2", fr: "d’austères", en: "profound", es: "austeros" },
        { wid: "10-3", fr: "études", en: "studies", es: "estudios" },
      ] },
    { id: 11, fr: "Car j’ai, pour fasciner ces dociles amants,", en: "For I have all these docile swains to enchant--", es: "Porque tengo, para fascinar a esos dóciles amantes,",
      wordGroups: [
        { wid: "11-0", fr: "Car", en: "For", es: "Porque" },
        { wid: "11-1", fr: "j’ai", en: "I have", es: "tengo" },
        { wid: "11-2", fr: "fasciner", en: "to enchant", es: "fascinar" },
        { wid: "11-3", fr: "ces dociles", en: "these docile", es: "esos dóciles" },
        { wid: "11-4", fr: "amants", en: "swains", es: "amantes" },
      ] },
    { id: 12, fr: "De purs miroirs qui font toutes choses plus belles :", en: "Two mirrors, which Beauty in all things ignite:", es: "Puros espejos que tornan todas las cosas más bellas:",
      wordGroups: [
        { wid: "12-0", fr: "purs miroirs", en: "Two mirrors", es: "Puros espejos" },
        { wid: "12-1", fr: "toutes choses", en: "all things", es: "todas las cosas" },
        { wid: "12-2", fr: "plus belles", en: "Beauty", es: "más bellas" },
      ] },
    { id: 13, fr: "Mes yeux, mes larges yeux aux clartés éternelles !", en: "Mine eyes, my large eyes, of eternal Light!", es: "¡Mis ojos, mis grandes ojos, los de los fulgores eternos!",
      wordGroups: [
        { wid: "13-0", fr: "Mes yeux", en: "Mine eyes", es: "Mis ojos" },
        { wid: "13-1", fr: "mes larges yeux", en: "my large eyes", es: "mis grandes ojos" },
        { wid: "13-2", fr: "clartés", en: "Light", es: "fulgores" },
        { wid: "13-3", fr: "éternelles", en: "eternal", es: "eternos" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
