window.POEMS = window.POEMS || {};

window.POEMS["la-geante"] = {
  title: "La Géante",
  titles: { fr: "La Géante", en: "The Giantess", es: "La giganta" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Du temps que la Nature en sa verve puissante", en: "I should have loved--erewhile when Heaven conceived", es: "Cuando Natura en su inspiración pujante",
      wordGroups: [
        { wid: "0-0", fr: "Du temps que", en: "erewhile when", es: "Cuando" },
        { wid: "0-1", fr: "la Nature", en: "Heaven", es: "Natura" },
      ] },
    { id: 1, fr: "Concevait chaque jour des enfants monstrueux,", en: "Each day, some child abnormal and obscene,", es: "Concebía cada día hijos monstruosos,",
      wordGroups: [
        { wid: "1-0", fr: "chaque jour", en: "Each day", es: "cada día" },
        { wid: "1-1", fr: "des enfants", en: "some child", es: "hijos" },
        { wid: "1-2", fr: "monstrueux", en: "abnormal", es: "monstruosos" },
      ] },
    { id: 2, fr: "J’eusse aimé vivre auprès d’une jeune géante,", en: "Beside a maiden giantess to have lived,", es: "Me hubiera placido vivir cerca de una joven giganta,",
      wordGroups: [
        { wid: "2-0", fr: "vivre", en: "to have lived", es: "vivir" },
        { wid: "2-1", fr: "auprès", en: "Beside", es: "cerca" },
        { wid: "2-2", fr: "jeune", en: "maiden", es: "joven" },
        { wid: "2-3", fr: "géante", en: "giantess", es: "giganta" },
      ] },
    { id: 3, fr: "Comme aux pieds d’une reine un chat voluptueux.", en: "Like a luxurious cat at the feet of a queen;", es: "Como a los pies de una reina un gato voluptuoso.",
      wordGroups: [
        { wid: "3-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "3-1", fr: "aux pieds", en: "at the feet", es: "a los pies" },
        { wid: "3-2", fr: "reine", en: "queen", es: "reina" },
        { wid: "3-3", fr: "chat", en: "cat", es: "gato" },
        { wid: "3-4", fr: "voluptueux", en: "luxurious", es: "voluptuoso" },
      ] },
    { id: 4, fr: "J’eusse aimé voir son corps fleurir avec son âme", en: "To see her body flowering with her soul,", es: "Me hubiera agradado ver su cuerpo florecer con su alma",
      wordGroups: [
        { wid: "4-0", fr: "voir", en: "To see", es: "ver" },
        { wid: "4-1", fr: "son corps", en: "her body", es: "su cuerpo" },
        { wid: "4-2", fr: "fleurir", en: "flowering", es: "florecer" },
        { wid: "4-3", fr: "son âme", en: "her soul", es: "su alma" },
      ] },
    { id: 5, fr: "Et grandir librement dans ses terribles jeux ;", en: "And grow, unchained, in awe-inspiring art,", es: "Y crecer libremente en sus terribles juegos;",
      wordGroups: [
        { wid: "5-0", fr: "Et grandir", en: "And grow", es: "Y crecer" },
        { wid: "5-1", fr: "librement", en: "unchained", es: "libremente" },
        { wid: "5-2", fr: "terribles", en: "awe-inspiring", es: "terribles" },
        { wid: "5-3", fr: "jeux", en: "art", es: "juegos" },
      ] },
    { id: 6, fr: "Deviner si son cœur couve une sombre flamme", en: "Within the mists across her eyes that stole", es: "Adivinar si su corazón cobija una sombría llama" },
    { id: 7, fr: "Aux humides brouillards qui nagent dans ses yeux ;", en: "To divine the fires entombed within her heart.", es: "En las húmedas brumas que flotan en sus ojos;" },
    { id: 8, fr: "Parcourir à loisir ses magnifiques formes ;", en: "And oft to scramble o'er her mighty limbs,", es: "Recorrer a mi gusto sus magníficas formas;",
      wordGroups: [
        { wid: "8-0", fr: "Parcourir", en: "to scramble o'er", es: "Recorrer" },
        { wid: "8-1", fr: "à loisir", en: "oft", es: "a mi gusto" },
        { wid: "8-2", fr: "magnifiques", en: "mighty", es: "magníficas" },
        { wid: "8-3", fr: "formes", en: "limbs", es: "formas" },
      ] },
    { id: 9, fr: "Ramper sur le versant de ses genoux énormes,", en: "And climb the slopes of her enormous knees,", es: "Arrastrarme en la pendiente de sus rodillas enormes,",
      wordGroups: [
        { wid: "9-0", fr: "Ramper", en: "climb", es: "Arrastrarme" },
        { wid: "9-1", fr: "le versant", en: "the slopes", es: "la pendiente" },
        { wid: "9-2", fr: "genoux", en: "knees", es: "rodillas" },
        { wid: "9-3", fr: "énormes", en: "enormous", es: "enormes" },
      ] },
    { id: 10, fr: "Et parfois en été, quand les soleils malsains,", en: "Or in summer when the scorching sunlight streams", es: "Y a veces, en estío, cuando los soles malsanos,",
      wordGroups: [
        { wid: "10-0", fr: "en été", en: "in summer", es: "en estío" },
        { wid: "10-1", fr: "quand", en: "when", es: "cuando" },
        { wid: "10-2", fr: "soleils", en: "sunlight", es: "soles" },
        { wid: "10-3", fr: "malsains", en: "scorching", es: "malsanos" },
      ] },
    { id: 11, fr: "Lasse, la font s’étendre à travers la campagne,", en: "Across the country, to recline at ease,", es: "Laxa, la hacen tenderse a través de la campiña,",
      wordGroups: [
        { wid: "11-0", fr: "s’étendre", en: "to recline", es: "tenderse" },
        { wid: "11-1", fr: "à travers", en: "Across", es: "a través" },
        { wid: "11-2", fr: "la campagne", en: "the country", es: "la campiña" },
      ] },
    { id: 12, fr: "Dormir nonchalamment à l’ombre de ses seins,", en: "And slumber in the shadow of her breast", es: "Dormir despreocupadamente a la sombra de sus senos,",
      wordGroups: [
        { wid: "12-0", fr: "Dormir", en: "slumber", es: "Dormir" },
        { wid: "12-1", fr: "à l’ombre", en: "in the shadow", es: "a la sombra" },
        { wid: "12-2", fr: "ses seins", en: "her breast", es: "sus senos" },
      ] },
    { id: 13, fr: "Comme un hameau paisible au pied d’une montagne.", en: "Like an hamlet 'neath the mountain-crest.", es: "Como una plácida aldea al pie de una montaña.",
      wordGroups: [
        { wid: "13-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "13-1", fr: "un hameau", en: "an hamlet", es: "aldea" },
        { wid: "13-2", fr: "au pied", en: "'neath", es: "al pie" },
        { wid: "13-3", fr: "montagne", en: "mountain-crest", es: "montaña" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
