window.POEMS = window.POEMS || {};

window.POEMS["le-balcon"] = {
  title: "Le Balcon",
  titles: { fr: "Le Balcon", en: "The Balcony", es: "El balcón" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Mère des souvenirs, maîtresse des maîtresses,", en: "Oh, Mother of Memories! Mistress of Mistresses!", es: "Madre de los recuerdos, amante de las amantes,",
      wordGroups: [
        { wid: "0-0", fr: "Mère", en: "Mother", es: "Madre" },
        { wid: "0-1", fr: "souvenirs", en: "Memories", es: "recuerdos" },
        { wid: "0-2", fr: "maîtresse des maîtresses", en: "Mistress of Mistresses", es: "amante de las amantes" },
      ] },
    { id: 1, fr: "Ô toi, tous mes plaisirs ! ô toi, tous mes devoirs !", en: "Oh, thou all my pleasures, oh, thou all my prayers!", es: "¡Oh, tú, todos mis placeres! ¡Oh tú, todos mis deberes!",
      wordGroups: [
        { wid: "1-0", fr: "Ô toi", en: "Oh, thou", es: "Oh, tú" },
        { wid: "1-1", fr: "tous mes plaisirs", en: "all my pleasures", es: "todos mis placeres" },
        { wid: "1-2", fr: "ô toi", en: "oh, thou", es: "Oh tú" },
        { wid: "1-3", fr: "tous mes devoirs", en: "all my prayers", es: "todos mis deberes" },
      ] },
    { id: 2, fr: "Tu te rappelleras la beauté des caresses,", en: "Can'st thou remember those luscious caresses,", es: "Tú me recordarás la belleza de las caricias,",
      wordGroups: [
        { wid: "2-0", fr: "Tu te rappelleras", en: "Can'st thou remember", es: "Tú me recordarás" },
        { wid: "2-1", fr: "caresses", en: "caresses", es: "caricias" },
      ] },
    { id: 3, fr: "La douceur du foyer et le charme des soirs,", en: "The charm of the hearth and the sweet evening airs?", es: "La dulzura del hogar y el encanto de las noches,",
      wordGroups: [
        { wid: "3-0", fr: "douceur", en: "sweet", es: "dulzura" },
        { wid: "3-1", fr: "foyer", en: "hearth", es: "hogar" },
        { wid: "3-2", fr: "charme", en: "charm", es: "encanto" },
        { wid: "3-3", fr: "soirs", en: "evening", es: "noches" },
      ] },
    { id: 4, fr: "Mère des souvenirs, maîtresse des maîtresses !", en: "Oh, Mother, of Memories, Mistress of Mistresses!", es: "¡Madre de los recuerdos, amante de las amantes!",
      wordGroups: [
        { wid: "4-0", fr: "Mère", en: "Mother", es: "Madre" },
        { wid: "4-1", fr: "souvenirs", en: "Memories", es: "recuerdos" },
        { wid: "4-2", fr: "maîtresse des maîtresses", en: "Mistress of Mistresses", es: "amante de las amantes" },
      ] },
    { id: 5, fr: "Les soirs illuminés par l’ardeur du charbon,", en: "Those evenings illumed by the glow of the coal,", es: "¡Las veladas iluminadas por el ardor del carbón,",
      wordGroups: [
        { wid: "5-0", fr: "Les soirs", en: "Those evenings", es: "Las veladas" },
        { wid: "5-1", fr: "illuminés", en: "illumed", es: "iluminadas" },
        { wid: "5-2", fr: "l’ardeur", en: "the glow", es: "el ardor" },
        { wid: "5-3", fr: "charbon", en: "coal", es: "carbón" },
      ] },
    { id: 6, fr: "Et les soirs au balcon, voilés de vapeurs roses.", en: "And those roseate nights with their vaporous wings,", es: "Y las tardes en el balcón, veladas de vapores rosados.",
      wordGroups: [
        { wid: "6-0", fr: "les soirs", en: "nights", es: "las tardes" },
        { wid: "6-1", fr: "vapeurs", en: "vaporous", es: "vapores" },
        { wid: "6-2", fr: "roses", en: "roseate", es: "rosados" },
      ] },
    { id: 7, fr: "Que ton sein m’était doux ! que ton cœur m’était bon !", en: "How calm was thy breast and how good was thy soul,", es: "¡Cuan dulce me era tu seno! y tu corazón ¡qué caro!",
      wordGroups: [
        { wid: "7-0", fr: "ton sein", en: "thy breast", es: "tu seno" },
        { wid: "7-1", fr: "doux", en: "calm", es: "dulce" },
        { wid: "7-2", fr: "ton cœur", en: "thy soul", es: "tu corazón" },
        { wid: "7-3", fr: "bon", en: "good", es: "caro" },
      ] },
    { id: 8, fr: "Nous avons dit souvent d’impérissables choses", en: "'Twas then we uttered imperishable things,", es: "Nos hemos dicho con frecuencia imperecederas cosas",
      wordGroups: [
        { wid: "8-0", fr: "Nous", en: "we", es: "Nos" },
        { wid: "8-1", fr: "dit", en: "uttered", es: "dicho" },
        { wid: "8-2", fr: "d’impérissables", en: "imperishable", es: "imperecederas" },
        { wid: "8-3", fr: "choses", en: "things", es: "cosas" },
      ] },
    { id: 9, fr: "Les soirs illuminés par l’ardeur du charbon.", en: "Those evenings illumed by the glow of the coal.", es: "En las veladas iluminadas por el ardor del carbón.",
      wordGroups: [
        { wid: "9-0", fr: "Les soirs", en: "Those evenings", es: "las veladas" },
        { wid: "9-1", fr: "illuminés", en: "illumed", es: "iluminadas" },
        { wid: "9-2", fr: "l’ardeur", en: "the glow", es: "el ardor" },
        { wid: "9-3", fr: "charbon", en: "coal", es: "carbón" },
      ] },
    { id: 10, fr: "Que les soleils sont beaux dans les chaudes soirées !", en: "How lovely the suns on those hot, autumn nights!", es: "¡Qué hermosos son los soles en las cálidas tardes!",
      wordGroups: [
        { wid: "10-0", fr: "Que", en: "How", es: "Qué" },
        { wid: "10-1", fr: "les soleils", en: "the suns", es: "los soles" },
        { wid: "10-2", fr: "beaux", en: "lovely", es: "hermosos" },
        { wid: "10-3", fr: "chaudes", en: "hot", es: "cálidas" },
        { wid: "10-4", fr: "soirées", en: "nights", es: "tardes" },
      ] },
    { id: 11, fr: "Que l’espace est profond ! que le cœur est puissant !", en: "How vast were the heavens! and the heart how hale!", es: "¡Qué profundo el espacio! ¡Qué potente el corazón!",
      wordGroups: [
        { wid: "11-0", fr: "l’espace", en: "the heavens", es: "el espacio" },
        { wid: "11-1", fr: "profond", en: "vast", es: "profundo" },
        { wid: "11-2", fr: "le cœur", en: "the heart", es: "el corazón" },
        { wid: "11-3", fr: "puissant", en: "hale", es: "potente" },
      ] },
    { id: 12, fr: "En me penchant vers toi, reine des adorées,", en: "As I leaned towards you--oh, my Queen of Delights,", es: "Inclinándome hacia ti, reina de las adoradas,",
      wordGroups: [
        { wid: "12-0", fr: "me penchant", en: "I leaned", es: "Inclinándome" },
        { wid: "12-1", fr: "vers toi", en: "towards you", es: "hacia ti" },
        { wid: "12-2", fr: "reine", en: "Queen", es: "reina" },
        { wid: "12-3", fr: "adorées", en: "Delights", es: "adoradas" },
      ] },
    { id: 13, fr: "Je croyais respirer le parfum de ton sang.", en: "The scent of thy blood I seemed to inhale.", es: "Yo creía respirar el perfume de tu sangre.",
      wordGroups: [
        { wid: "13-0", fr: "Je croyais", en: "I seemed", es: "Yo creía" },
        { wid: "13-1", fr: "respirer", en: "inhale", es: "respirar" },
        { wid: "13-2", fr: "le parfum", en: "The scent", es: "el perfume" },
        { wid: "13-3", fr: "ton sang", en: "thy blood", es: "tu sangre" },
      ] },
    { id: 14, fr: "Que les soleils sont beaux dans les chaudes soirées !", en: "How lovely the sun on those hot, autumn nights!", es: "¡Qué hermosos son los soles en cálidas tardes!",
      wordGroups: [
        { wid: "14-0", fr: "Que", en: "How", es: "Qué" },
        { wid: "14-1", fr: "les soleils", en: "the sun", es: "los soles" },
        { wid: "14-2", fr: "beaux", en: "lovely", es: "hermosos" },
        { wid: "14-3", fr: "chaudes", en: "hot", es: "cálidas" },
        { wid: "14-4", fr: "soirées", en: "nights", es: "tardes" },
      ] },
    { id: 15, fr: "La nuit s’épaississait ainsi qu’une cloison,", en: "The shadows of night-time grew dense like a pall,", es: "La noche se apaciguaba como en un claustro,",
      wordGroups: [
        { wid: "15-0", fr: "La nuit", en: "night-time", es: "La noche" },
        { wid: "15-1", fr: "s’épaississait", en: "grew dense", es: "se apaciguaba" },
        { wid: "15-2", fr: "ainsi qu’une", en: "like a", es: "como en un" },
        { wid: "15-3", fr: "cloison", en: "pall", es: "claustro" },
      ] },
    { id: 16, fr: "Et mes yeux dans le noir devinaient tes prunelles,", en: "And deep through the darkness thine eyes I divined,", es: "Y mis ojos en la oscuridad barruntaban tus pupilas,",
      wordGroups: [
        { wid: "16-0", fr: "dans le noir", en: "through the darkness", es: "en la oscuridad" },
        { wid: "16-1", fr: "devinaient", en: "divined", es: "barruntaban" },
        { wid: "16-2", fr: "tes prunelles", en: "thine eyes", es: "tus pupilas" },
      ] },
    { id: 17, fr: "Et je buvais ton souffle, ô douceur ! ô poison !", en: "And I drank of thy breath--oh sweetness, oh gall,", es: "Y yo bebía tu aliento, ¡oh dulzura! ¡oh veneno!",
      wordGroups: [
        { wid: "17-0", fr: "je buvais", en: "I drank", es: "yo bebía" },
        { wid: "17-1", fr: "ton souffle", en: "thy breath", es: "tu aliento" },
        { wid: "17-2", fr: "douceur", en: "sweetness", es: "dulzura" },
        { wid: "17-3", fr: "poison", en: "gall", es: "veneno" },
      ] },
    { id: 18, fr: "Et tes pieds s’endormaient dans mes mains fraternelles.", en: "And thy feet in my brotherly hands reclined,", es: "Y tus pies se adormecían en mis manos fraternales.",
      wordGroups: [
        { wid: "18-0", fr: "tes pieds", en: "thy feet", es: "tus pies" },
        { wid: "18-1", fr: "s’endormaient", en: "reclined", es: "se adormecían" },
        { wid: "18-2", fr: "mains", en: "hands", es: "manos" },
        { wid: "18-3", fr: "fraternelles", en: "brotherly", es: "fraternales" },
      ] },
    { id: 19, fr: "La nuit s’épaississait ainsi qu’une cloison.", en: "The shadows of Night-time grew dense like a pall.", es: "La noche se apaciguaba como en un claustro.",
      wordGroups: [
        { wid: "19-0", fr: "La nuit", en: "Night-time", es: "La noche" },
        { wid: "19-1", fr: "s’épaississait", en: "grew dense", es: "se apaciguaba" },
        { wid: "19-2", fr: "ainsi qu’une", en: "like a", es: "como en un" },
        { wid: "19-3", fr: "cloison", en: "pall", es: "claustro" },
      ] },
    { id: 20, fr: "Je sais l’art d’évoquer les minutes heureuses,", en: "I know how to call forth those moments so dear,", es: "Yo sé del arte de evocar los minutos dichosos,",
      wordGroups: [
        { wid: "20-0", fr: "Je sais", en: "I know", es: "Yo sé" },
        { wid: "20-1", fr: "d’évoquer", en: "to call forth", es: "de evocar" },
        { wid: "20-2", fr: "les minutes", en: "those moments", es: "los minutos" },
        { wid: "20-3", fr: "heureuses", en: "so dear", es: "dichosos" },
      ] },
    { id: 21, fr: "Et revis mon passé blotti dans tes genoux.", en: "And to live my Past--laid on thy knees--once more,", es: "Y volví a ver mi pasado agazapado en tus rodillas.",
      wordGroups: [
        { wid: "21-0", fr: "revis", en: "to live", es: "volví a ver" },
        { wid: "21-1", fr: "mon passé", en: "my Past", es: "mi pasado" },
        { wid: "21-2", fr: "blotti", en: "laid", es: "agazapado" },
        { wid: "21-3", fr: "tes genoux", en: "thy knees", es: "tus rodillas" },
      ] },
    { id: 22, fr: "Car à quoi bon chercher tes beautés langoureuses", en: "For where should I seek for thy beauties but here", es: "Porque ¿a qué buscar tus bellezas lánguidas",
      wordGroups: [
        { wid: "22-0", fr: "Car", en: "For", es: "Porque" },
        { wid: "22-1", fr: "chercher", en: "seek", es: "buscar" },
        { wid: "22-2", fr: "tes beautés", en: "thy beauties", es: "tus bellezas" },
      ] },
    { id: 23, fr: "Ailleurs qu’en ton cher corps et qu’en ton cœur si doux ?", en: "In thy langorous heart and thy body so pure?", es: "Fuera de tu querido cuerpo y de tu corazón tan dulce?",
      wordGroups: [
        { wid: "23-0", fr: "ton cher corps", en: "thy body", es: "tu querido cuerpo" },
        { wid: "23-1", fr: "cœur", en: "heart", es: "corazón" },
        { wid: "23-2", fr: "si doux", en: "so pure", es: "tan dulce" },
      ] },
    { id: 24, fr: "Je sais l’art d’évoquer les minutes heureuses !", en: "I know how to call forth those moments so dear.", es: "¡Yo sé del arte de evocar los minutos dichosos!",
      wordGroups: [
        { wid: "24-0", fr: "Je sais", en: "I know", es: "Yo sé" },
        { wid: "24-1", fr: "d’évoquer", en: "to call forth", es: "de evocar" },
        { wid: "24-2", fr: "les minutes", en: "those moments", es: "los minutos" },
        { wid: "24-3", fr: "heureuses", en: "so dear", es: "dichosos" },
      ] },
    { id: 25, fr: "Ces serments, ces parfums, ces baisers infinis,", en: "Those perfumes, those infinite kisses and sighs,", es: "Esos juramentos, esos perfumes, esos besos infinitos,",
      wordGroups: [
        { wid: "25-0", fr: "ces parfums", en: "Those perfumes", es: "esos perfumes" },
        { wid: "25-1", fr: "baisers", en: "kisses", es: "besos" },
        { wid: "25-2", fr: "infinis", en: "infinite", es: "infinitos" },
      ] },
    { id: 26, fr: "Renaîtront-ils d’un gouffre interdit à nos sondes,", en: "Are they born in some gulf to our plummets denied?", es: "¿Renacerán de un abismo vedado a nuestras sondas,",
      wordGroups: [
        { wid: "26-0", fr: "Renaîtront-ils", en: "Are they born", es: "Renacerán" },
        { wid: "26-1", fr: "d’un gouffre", en: "in some gulf", es: "de un abismo" },
        { wid: "26-2", fr: "interdit", en: "denied", es: "vedado" },
        { wid: "26-3", fr: "nos sondes", en: "our plummets", es: "nuestras sondas" },
      ] },
    { id: 27, fr: "Comme montent au ciel les soleils rajeunis", en: "Like rejuvenate suns that mount up to the skies,", es: "Como suben al cielo los soles rejuvenecidos",
      wordGroups: [
        { wid: "27-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "27-1", fr: "montent", en: "mount", es: "suben" },
        { wid: "27-2", fr: "au ciel", en: "to the skies", es: "al cielo" },
        { wid: "27-3", fr: "les soleils", en: "suns", es: "los soles" },
        { wid: "27-4", fr: "rajeunis", en: "rejuvenate", es: "rejuvenecidos" },
      ] },
    { id: 28, fr: "Après s’être lavés au fond des mers profondes ?", en: "That first have been cleansed in the depths of the tide;", es: "Luego de lavarse en el fondo de los mares profundos?",
      wordGroups: [
        { wid: "28-0", fr: "lavés", en: "cleansed", es: "lavarse" },
        { wid: "28-1", fr: "au fond", en: "the depths", es: "en el fondo" },
        { wid: "28-2", fr: "des mers", en: "the tide", es: "de los mares" },
      ] },
    { id: 29, fr: "— Ô serments ! ô parfums ! ô baisers infinis !", en: "Oh, perfumes! oh, infinite kisses and sighs!", es: "— ¡Oh, juramentos! ¡Oh, perfumes! ¡Oh, besos infinitos!",
      wordGroups: [
        { wid: "29-0", fr: "parfums", en: "perfumes", es: "perfumes" },
        { wid: "29-1", fr: "baisers", en: "kisses", es: "besos" },
        { wid: "29-2", fr: "infinis", en: "infinite", es: "infinitos" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
  ],
};
