window.POEMS = window.POEMS || {};

window.POEMS["le-chat-2"] = {
  title: "Le Chat",
  titles: { fr: "Le Chat" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Le_Chat_%28%C2%AB_Dans_ma_cervelle_se_prom%C3%A8ne_%C2%BB%29",
  },
  segments: [
    { id: 0, fr: "Dans ma cervelle se promène," },
    { id: 1, fr: "Ainsi qu’en son appartement," },
    { id: 2, fr: "Un beau chat, fort, doux et charmant." },
    { id: 3, fr: "Quand il miaule, on l’entend à peine," },
    { id: 4, fr: "Tant son timbre est tendre et discret ;" },
    { id: 5, fr: "Mais que sa voix s’apaise ou gronde," },
    { id: 6, fr: "Elle est toujours riche et profonde." },
    { id: 7, fr: "C’est là son charme et son secret." },
    { id: 8, fr: "Cette voix, qui perle et qui filtre" },
    { id: 9, fr: "Dans mon fonds le plus ténébreux," },
    { id: 10, fr: "Me remplit comme un vers nombreux" },
    { id: 11, fr: "Et me réjouit comme un philtre." },
    { id: 12, fr: "Elle endort les plus cruels maux" },
    { id: 13, fr: "Et contient toutes les extases ;" },
    { id: 14, fr: "Pour dire les plus longues phrases," },
    { id: 15, fr: "Elle n’a pas besoin de mots." },
    { id: 16, fr: "Non, il n’est pas d’archet qui morde" },
    { id: 17, fr: "Sur mon cœur, parfait instrument," },
    { id: 18, fr: "Et fasse plus royalement" },
    { id: 19, fr: "Chanter sa plus vibrante corde," },
    { id: 20, fr: "Que ta voix, chat mystérieux," },
    { id: 21, fr: "Chat séraphique, chat étrange," },
    { id: 22, fr: "En qui tout est, comme en un ange," },
    { id: 23, fr: "Aussi subtil qu’harmonieux !" },
    { id: 24, fr: "De sa fourrure blonde et brune" },
    { id: 25, fr: "Sort un parfum si doux, qu’un soir" },
    { id: 26, fr: "J’en fus embaumé, pour l’avoir" },
    { id: 27, fr: "Caressée une fois, rien qu’une." },
    { id: 28, fr: "C’est l’esprit familier du lieu ;" },
    { id: 29, fr: "Il juge, il préside, il inspire" },
    { id: 30, fr: "Toutes choses dans son empire ;" },
    { id: 31, fr: "Peut-être est-il fée, est-il dieu ?" },
    { id: 32, fr: "Quand mes yeux, vers ce chat que j’aime" },
    { id: 33, fr: "Tirés comme par un aimant," },
    { id: 34, fr: "Se retournent docilement" },
    { id: 35, fr: "Et que je regarde en moi-même," },
    { id: 36, fr: "Je vois avec étonnement" },
    { id: 37, fr: "Le feu de ses prunelles pâles," },
    { id: 38, fr: "Clairs fanaux, vivantes opales," },
    { id: 39, fr: "Qui me contemplent fixement." },
  ],
  blocks: [
    { type: 'part', label: "I" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'part', label: "II" },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
