window.POEMS = window.POEMS || {};

window.POEMS["le-flacon"] = {
  title: "Le Flacon",
  titles: { fr: "Le Flacon", es: "El frasco" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Le_Flacon",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/El_frasco",
  },
  segments: [
    { id: 0, fr: "Il est de forts parfums pour qui toute matière", es: "Hay fuertes perfumes para los que toda materia",
      wordGroups: [
        { wid: "0-0", fr: "parfums", es: "perfumes" },
        { wid: "0-1", fr: "matière", es: "materia" },
      ] },
    { id: 1, fr: "Est poreuse. On dirait qu’ils pénètrent le verre.", es: "Es porosa.  Se diría que penetran el vaso.",
      wordGroups: [
        { wid: "1-0", fr: "dirait", es: "diría" },
        { wid: "1-1", fr: "pénètrent", es: "penetran" },
        { wid: "1-2", fr: "verre", es: "vaso" },
      ] },
    { id: 2, fr: "En ouvrant un coffret venu de l’Orient", es: "Al abrir un cofrecillo llegado del Oriente" },
    { id: 3, fr: "Dont la serrure grince et rechigne en criant,", es: "Cuya cerradura rechina y se resiste chirriando," },
    { id: 4, fr: "Ou dans une maison déserte quelque armoire", es: "O bien en una casa desierta en algún armario",
      wordGroups: [
        { wid: "4-0", fr: "maison", es: "casa" },
        { wid: "4-1", fr: "déserte", es: "desierta" },
        { wid: "4-2", fr: "armoire", es: "armario" },
      ] },
    { id: 5, fr: "Pleine de l’âcre odeur des temps, poudreuse et noire,", es: "Lleno del acre olor del tiempo, polvoriento y negro,",
      wordGroups: [
        { wid: "5-0", fr: "Pleine", es: "Lleno" },
        { wid: "5-1", fr: "odeur", es: "olor" },
        { wid: "5-2", fr: "temps", es: "tiempo" },
        { wid: "5-3", fr: "noire", es: "negro" },
      ] },
    { id: 6, fr: "Parfois on trouve un vieux flacon qui se souvient,", es: "A veces encontramos un viejo frasco que se recuerda",
      wordGroups: [
        { wid: "6-0", fr: "Parfois", es: "veces" },
        { wid: "6-1", fr: "vieux", es: "viejo" },
        { wid: "6-2", fr: "flacon", es: "frasco" },
      ] },
    { id: 7, fr: "D’où jaillit toute vive une âme qui revient.", es: "Del que surge vivísima un alma que resucita.",
      wordGroups: [
        { wid: "7-0", fr: "âme", es: "alma" },
      ] },
    { id: 8, fr: "Mille pensers dormaient, chrysalides funèbres,", es: "Mil pensamientos dormían, crisálidas fúnebres,",
      wordGroups: [
        { wid: "8-0", fr: "Mille", es: "Mil" },
        { wid: "8-1", fr: "dormaient", es: "dormían" },
        { wid: "8-2", fr: "funèbres", es: "fúnebres" },
      ] },
    { id: 9, fr: "Frémissant doucement dans les lourdes ténèbres,", es: "Temblando dulcemente en las pesadas tinieblas,",
      wordGroups: [
        { wid: "9-0", fr: "doucement", es: "dulcemente" },
        { wid: "9-1", fr: "lourdes", es: "pesadas" },
        { wid: "9-2", fr: "ténèbres", es: "tinieblas" },
      ] },
    { id: 10, fr: "Qui dégagent leur aile et prennent leur essor,", es: "Que entreabren su ala y toman su impulso,",
      wordGroups: [
        { wid: "10-0", fr: "aile", es: "ala" },
        { wid: "10-1", fr: "essor", es: "impulso" },
      ] },
    { id: 11, fr: "Teintés d’azur, glacés de rose, lamés d’or.", es: "Teñidas de azur, salpicadas de rosa, laminadas de oro.",
      wordGroups: [
        { wid: "11-0", fr: "rose", es: "rosa" },
      ] },
    { id: 12, fr: "Voilà le souvenir enivrant qui voltige", es: "He aquí el recuerdo embriagador que revolotea",
      wordGroups: [
        { wid: "12-0", fr: "souvenir", es: "recuerdo" },
      ] },
    { id: 13, fr: "Dans l’air troublé ; les yeux se ferment ; le Vertige", es: "En el aire turbado; los ojos se cierran: el Vértigo",
      wordGroups: [
        { wid: "13-0", fr: "troublé", es: "turbado" },
        { wid: "13-1", fr: "yeux", es: "ojos" },
        { wid: "13-2", fr: "ferment", es: "cierran" },
        { wid: "13-3", fr: "Vertige", es: "Vértigo" },
      ] },
    { id: 14, fr: "Saisit l’âme vaincue et la pousse à deux mains", es: "Agarra el alma vencida y la arroja a dos manos",
      wordGroups: [
        { wid: "14-0", fr: "Saisit", es: "Agarra" },
        { wid: "14-1", fr: "deux", es: "dos" },
        { wid: "14-2", fr: "mains", es: "manos" },
      ] },
    { id: 15, fr: "Vers un gouffre obscurci de miasmes humains ;", es: "Hacia un abismo oscurecido de miasmas humanas;",
      wordGroups: [
        { wid: "15-0", fr: "gouffre", es: "abismo" },
        { wid: "15-1", fr: "miasmes", es: "miasmas" },
        { wid: "15-2", fr: "humains", es: "humanas" },
      ] },
    { id: 16, fr: "Il la terrasse au bord d’un gouffre séculaire,", es: "La derriba al borde de un abismo secular,",
      wordGroups: [
        { wid: "16-0", fr: "bord", es: "borde" },
        { wid: "16-1", fr: "gouffre", es: "abismo" },
        { wid: "16-2", fr: "séculaire", es: "secular" },
      ] },
    { id: 17, fr: "Où, Lazare odorant déchirant son suaire,", es: "Donde, Lázaro oloroso desgarrando un sudario,",
      wordGroups: [
        { wid: "17-0", fr: "Lazare", es: "Lázaro" },
        { wid: "17-1", fr: "suaire", es: "sudario" },
      ] },
    { id: 18, fr: "Se meut dans son réveil le cadavre spectral", es: "Se mueve en su despertar el cadáver espectral",
      wordGroups: [
        { wid: "18-0", fr: "réveil", es: "despertar" },
        { wid: "18-1", fr: "cadavre", es: "cadáver" },
        { wid: "18-2", fr: "spectral", es: "espectral" },
      ] },
    { id: 19, fr: "D’un vieil amour ranci, charmant et sépulcral.", es: "De un viejo amor rancio, encantador y sepulcral.",
      wordGroups: [
        { wid: "19-0", fr: "amour", es: "amor" },
        { wid: "19-1", fr: "ranci", es: "rancio" },
        { wid: "19-2", fr: "charmant", es: "encantador" },
        { wid: "19-3", fr: "sépulcral", es: "sepulcral" },
      ] },
    { id: 20, fr: "Ainsi, quand je serai perdu dans la mémoire", es: "Así, cuando yo esté perdido en la memoria",
      wordGroups: [
        { wid: "20-0", fr: "Ainsi", es: "Así" },
        { wid: "20-1", fr: "perdu", es: "perdido" },
        { wid: "20-2", fr: "mémoire", es: "memoria" },
      ] },
    { id: 21, fr: "Des hommes, dans le coin d’une sinistre armoire", es: "De los hombres, en el rincón de un siniestro armario",
      wordGroups: [
        { wid: "21-0", fr: "hommes", es: "hombres" },
        { wid: "21-1", fr: "coin", es: "rincón" },
        { wid: "21-2", fr: "sinistre", es: "siniestro" },
        { wid: "21-3", fr: "armoire", es: "armario" },
      ] },
    { id: 22, fr: "Quand on m’aura jeté, vieux flacon désolé,", es: "guando me hayan arrojado, viejo frasco desolado,",
      wordGroups: [
        { wid: "22-0", fr: "jeté", es: "arrojado" },
        { wid: "22-1", fr: "vieux", es: "viejo" },
        { wid: "22-2", fr: "flacon", es: "frasco" },
        { wid: "22-3", fr: "désolé", es: "desolado" },
      ] },
    { id: 23, fr: "Décrépit, poudreux, sale, abject, visqueux, fêlé,", es: "Decrépito, polvoriento, sucio, abyecto, viscoso, rajado,",
      wordGroups: [
        { wid: "23-0", fr: "Décrépit", es: "Decrépito" },
        { wid: "23-1", fr: "poudreux", es: "polvoriento" },
        { wid: "23-2", fr: "sale", es: "sucio" },
        { wid: "23-3", fr: "visqueux", es: "viscoso" },
      ] },
    { id: 24, fr: "Je serai ton cercueil, aimable pestilence !", es: "¡Yo seré tu ataúd, amable pestilencia!",
      wordGroups: [
        { wid: "24-0", fr: "serai", es: "seré" },
        { wid: "24-1", fr: "cercueil", es: "ataúd" },
        { wid: "24-2", fr: "aimable", es: "amable" },
        { wid: "24-3", fr: "pestilence", es: "pestilencia" },
      ] },
    { id: 25, fr: "Le témoin de ta force et de ta virulence,", es: "El testigo de tu fuerza y de tu virulencia,",
      wordGroups: [
        { wid: "25-0", fr: "force", es: "fuerza" },
        { wid: "25-1", fr: "virulence", es: "virulencia" },
      ] },
    { id: 26, fr: "Cher poison préparé par les anges ! liqueur", es: "¡Caro veneno preparado por los ángeles! licor",
      wordGroups: [
        { wid: "26-0", fr: "poison", es: "veneno" },
        { wid: "26-1", fr: "préparé", es: "preparado" },
        { wid: "26-2", fr: "anges", es: "ángeles" },
        { wid: "26-3", fr: "liqueur", es: "licor" },
      ] },
    { id: 27, fr: "Qui me ronge, ô la vie et la mort de mon cœur !", es: "Que me corroe, ¡Oh, la vida y la muerte de mi corazón!",
      wordGroups: [
        { wid: "27-0", fr: "vie", es: "vida" },
        { wid: "27-1", fr: "mort", es: "muerte" },
        { wid: "27-2", fr: "cœur", es: "corazón" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
