window.POEMS = window.POEMS || {};

window.POEMS["le-masque"] = {
  title: "Le Masque",
  titles: { fr: "Le Masque", es: "La máscara" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Le_Masque",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/La_m%C3%A1scara_%28Baudelaire%29",
  },
  segments: [
    { id: 0, fr: "Contemplons ce trésor de grâces florentines ;", es: "Contemplemos este tesoro de gracias florentinas;",
      wordGroups: [
        { wid: "0-0", fr: "Contemplons", es: "Contemplemos" },
        { wid: "0-1", fr: "trésor", es: "tesoro" },
        { wid: "0-2", fr: "grâces", es: "gracias" },
        { wid: "0-3", fr: "florentines", es: "florentinas" },
      ] },
    { id: 1, fr: "Dans l’ondulation de ce corps musculeux", es: "En la ondulación de este cuerpo musculoso",
      wordGroups: [
        { wid: "1-0", fr: "l’ondulation", es: "ondulación" },
        { wid: "1-1", fr: "corps", es: "cuerpo" },
        { wid: "1-2", fr: "musculeux", es: "musculoso" },
      ] },
    { id: 2, fr: "L’Élégance et la Force abondent, sœurs divines.", es: "La Elegancia y la Fuerza abundan, hermanas Divinas.",
      wordGroups: [
        { wid: "2-0", fr: "Force", es: "Fuerza" },
        { wid: "2-1", fr: "sœurs", es: "hermanas" },
        { wid: "2-2", fr: "divines", es: "Divinas" },
      ] },
    { id: 3, fr: "Cette femme, morceau vraiment miraculeux,", es: "Esta mujer, trozo verdaderamente milagroso,",
      wordGroups: [
        { wid: "3-0", fr: "femme", es: "mujer" },
        { wid: "3-1", fr: "morceau", es: "trozo" },
        { wid: "3-2", fr: "miraculeux", es: "milagroso" },
      ] },
    { id: 4, fr: "Divinement robuste, adorablement mince,", es: "Divinamente robusta, adorablemente delgada,",
      wordGroups: [
        { wid: "4-0", fr: "Divinement", es: "Divinamente" },
        { wid: "4-1", fr: "robuste", es: "robusta" },
        { wid: "4-2", fr: "adorablement", es: "adorablemente" },
      ] },
    { id: 5, fr: "Est faite pour trôner sur des lits somptueux,", es: "Está hecha para reinar sobre lechos suntuosos,",
      wordGroups: [
        { wid: "5-0", fr: "faite", es: "hecha" },
        { wid: "5-1", fr: "lits", es: "lechos" },
      ] },
    { id: 6, fr: "Et charmer les loisirs d’un pontife ou d’un prince.", es: "Y encantar los ocios de un pontífice o de un príncipe.",
      wordGroups: [
        { wid: "6-0", fr: "pontife", es: "pontífice" },
        { wid: "6-1", fr: "prince", es: "príncipe" },
      ] },
    { id: 7, fr: "— Aussi, vois ce souris fin et voluptueux", es: "—Por eso, contemplo esa sonrisa, fina y voluptuosa",
      wordGroups: [
        { wid: "7-0", fr: "souris", es: "sonrisa" },
        { wid: "7-1", fr: "fin", es: "fina" },
        { wid: "7-2", fr: "voluptueux", es: "voluptuosa" },
      ] },
    { id: 8, fr: "Où la Fatuité promène son extase ;", es: "En que la fatuidad pasea su éxtasis;",
      wordGroups: [
        { wid: "8-0", fr: "Fatuité", es: "fatuidad" },
        { wid: "8-1", fr: "promène", es: "pasea" },
        { wid: "8-2", fr: "extase", es: "éxtasis" },
      ] },
    { id: 9, fr: "Ce long regard sournois, langoureux et moqueur ;", es: "Esa prolongada mirada taimada, lánguida y burlona;",
      wordGroups: [
        { wid: "9-0", fr: "regard", es: "mirada" },
        { wid: "9-1", fr: "moqueur", es: "burlona" },
      ] },
    { id: 10, fr: "Ce visage mignard, tout encadré de gaze,", es: "Ese rostro delicado, realzado por la gasa,",
      wordGroups: [
        { wid: "10-0", fr: "visage", es: "rostro" },
      ] },
    { id: 11, fr: "Dont chaque trait nous dit avec un air vainqueur :", es: "Del que cada rasgo nos dice con aire vencedor:",
      wordGroups: [
        { wid: "11-0", fr: "trait", es: "rasgo" },
        { wid: "11-1", fr: "dit", es: "dice" },
        { wid: "11-2", fr: "air", es: "aire" },
        { wid: "11-3", fr: "vainqueur", es: "vencedor" },
      ] },
    { id: 12, fr: "« La Volupté m’appelle et l’amour me couronne ! »", es: "\"¡La Voluptuosidad me llama y el Amor me corona!\"",
      wordGroups: [
        { wid: "12-0", fr: "Volupté", es: "Voluptuosidad" },
        { wid: "12-1", fr: "couronne", es: "corona" },
      ] },
    { id: 13, fr: "À cet être doué de tant de majesté", es: "A este ser dotado de tanta majestad",
      wordGroups: [
        { wid: "13-0", fr: "être", es: "ser" },
        { wid: "13-1", fr: "tant", es: "tanta" },
        { wid: "13-2", fr: "majesté", es: "majestad" },
      ] },
    { id: 14, fr: "Vois quel charme excitant la gentillesse donne !", es: "—¡Ved que encanto excitante la gentileza le otorga!",
      wordGroups: [
        { wid: "14-0", fr: "charme", es: "encanto" },
        { wid: "14-1", fr: "excitant", es: "excitante" },
      ] },
    { id: 15, fr: "Approchons, et tournons autour de sa beauté.", es: "Aproximémonos, y giremos en torno a su belleza.",
      wordGroups: [
        { wid: "15-0", fr: "beauté", es: "belleza" },
      ] },
    { id: 16, fr: "Ô blasphème de l’art ! ô surprise fatale !", es: "¡Oh, blasfemia del arte! ¡Oh, sorpresa fatal!",
      wordGroups: [
        { wid: "16-0", fr: "blasphème", es: "blasfemia" },
        { wid: "16-1", fr: "l’art", es: "arte" },
        { wid: "16-2", fr: "surprise", es: "sorpresa" },
        { wid: "16-3", fr: "fatale", es: "fatal" },
      ] },
    { id: 17, fr: "La femme au corps divin, promettant le bonheur,", es: "¡La mujer de cuerpo divino, prometiendo la ventura,",
      wordGroups: [
        { wid: "17-0", fr: "femme", es: "mujer" },
        { wid: "17-1", fr: "corps", es: "cuerpo" },
        { wid: "17-2", fr: "divin", es: "divino" },
      ] },
    { id: 18, fr: "Par le haut se termine en monstre bicéphale !", es: "Por lo alto termina en un monstruo bicéfalo!",
      wordGroups: [
        { wid: "18-0", fr: "haut", es: "alto" },
        { wid: "18-1", fr: "termine", es: "termina" },
        { wid: "18-2", fr: "monstre", es: "monstruo" },
        { wid: "18-3", fr: "bicéphale", es: "bicéfalo" },
      ] },
    { id: 19, fr: "— Mais non ! ce n’est qu’un masque, un décor suborneur,", es: "—¡Pero, no!  Sólo es una máscara, un decorado engañoso,",
      wordGroups: [
        { wid: "19-0", fr: "masque", es: "máscara" },
      ] },
    { id: 20, fr: "Ce visage éclairé d’une exquise grimace,", es: "Este rostro iluminado por una exquisita mueca,",
      wordGroups: [
        { wid: "20-0", fr: "visage", es: "rostro" },
        { wid: "20-1", fr: "exquise", es: "exquisita" },
        { wid: "20-2", fr: "grimace", es: "mueca" },
      ] },
    { id: 21, fr: "Et, regarde, voici, crispée atrocement,", es: "Y, mira, aquí, crispada atrozmente,",
      wordGroups: [
        { wid: "21-0", fr: "regarde", es: "mira" },
        { wid: "21-1", fr: "voici", es: "aquí" },
      ] },
    { id: 22, fr: "La véritable tête, et la sincère face", es: "La verdadera cabeza, y el sincero rostro",
      wordGroups: [
        { wid: "22-0", fr: "tête", es: "cabeza" },
        { wid: "22-1", fr: "sincère", es: "sincero" },
        { wid: "22-2", fr: "face", es: "rostro" },
      ] },
    { id: 23, fr: "Renversée à l’abri de la face qui ment.", es: "Vuelto al abrigo de la cara que miente.",
      wordGroups: [
        { wid: "23-0", fr: "ment", es: "miente" },
      ] },
    { id: 24, fr: "Pauvre grande beauté ! le magnifique fleuve", es: "¡Pobre gran belleza!   ¡El magnífico río",
      wordGroups: [
        { wid: "24-0", fr: "Pauvre", es: "Pobre" },
        { wid: "24-1", fr: "beauté", es: "belleza" },
        { wid: "24-2", fr: "magnifique", es: "magnífico" },
        { wid: "24-3", fr: "fleuve", es: "río" },
      ] },
    { id: 25, fr: "De tes pleurs aboutit dans mon cœur soucieux ;", es: "De tus lágrimas vuélcase en mi corazón receloso;",
      wordGroups: [
        { wid: "25-0", fr: "pleurs", es: "lágrimas" },
        { wid: "25-1", fr: "cœur", es: "corazón" },
      ] },
    { id: 26, fr: "Ton mensonge m’enivre, et mon âme s’abreuve", es: "Tu mentira me embriaga, y mi alma se abreva",
      wordGroups: [
        { wid: "26-0", fr: "mensonge", es: "mentira" },
        { wid: "26-1", fr: "âme", es: "alma" },
      ] },
    { id: 27, fr: "Aux flots que la Douleur fait jaillir de tes yeux !", es: "En los raudales que el Dolor hace brotar de tus ojos!",
      wordGroups: [
        { wid: "27-0", fr: "Douleur", es: "Dolor" },
        { wid: "27-1", fr: "fait", es: "hace" },
        { wid: "27-2", fr: "yeux", es: "ojos" },
      ] },
    { id: 28, fr: "— Mais pourquoi pleure-t-elle ? Elle, beauté parfaite", es: "—Pero, ¿por qué llora ella?  Ella, beldad perfecta",
      wordGroups: [
        { wid: "28-0", fr: "pleure", es: "llora" },
        { wid: "28-1", fr: "beauté", es: "beldad" },
        { wid: "28-2", fr: "parfaite", es: "perfecta" },
      ] },
    { id: 29, fr: "Qui mettrait à ses pieds le genre humain vaincu,", es: "Que pondría a sus plantas al género humano vencido,",
      wordGroups: [
        { wid: "29-0", fr: "genre", es: "género" },
        { wid: "29-1", fr: "humain", es: "humano" },
        { wid: "29-2", fr: "vaincu", es: "vencido" },
      ] },
    { id: 30, fr: "Quel mal mystérieux ronge son flanc d’athlète ?", es: "¿Qué mal misterioso corroe su flanco de atleta?",
      wordGroups: [
        { wid: "30-0", fr: "mal", es: "mal" },
        { wid: "30-1", fr: "mystérieux", es: "misterioso" },
        { wid: "30-2", fr: "flanc", es: "flanco" },
      ] },
    { id: 31, fr: "— Elle pleure, insensé, parce qu’elle a vécu !", es: "— ¡Ella llora, insensata, porque ella ha vivido!",
      wordGroups: [
        { wid: "31-0", fr: "pleure", es: "llora" },
      ] },
    { id: 32, fr: "Et parce qu’elle vit ! Mais ce qu’elle déplore", es: "¡Y porque vive! Pero, lo que ella deplora",
      wordGroups: [
        { wid: "32-0", fr: "vit", es: "vive" },
        { wid: "32-1", fr: "déplore", es: "deplora" },
      ] },
    { id: 33, fr: "Surtout, ce qui la fait frémir jusqu’aux genoux,", es: "Sobre todo, lo que la hace temblar hasta las rodillas,",
      wordGroups: [
        { wid: "33-0", fr: "fait", es: "hace" },
        { wid: "33-1", fr: "genoux", es: "rodillas" },
      ] },
    { id: 34, fr: "C’est que demain, hélas ! il faudra vivre encore !", es: "Es que mañana, ¡ah! ¡tendrá que vivir todavía!",
      wordGroups: [
        { wid: "34-0", fr: "demain", es: "mañana" },
        { wid: "34-1", fr: "vivre", es: "vivir" },
        { wid: "34-2", fr: "encore", es: "todavía" },
      ] },
    { id: 35, fr: "Demain, après-demain et toujours ! — comme nous !", es: "¡Mañana, pasado mañana y siempre! — ¡Como nosotros!",
      wordGroups: [
        { wid: "35-0", fr: "Demain", es: "Mañana" },
        { wid: "35-1", fr: "demain", es: "mañana" },
        { wid: "35-2", fr: "toujours", es: "siempre" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 7 },
    { type: 'blank' },
    { type: 'stanza', lines: 9 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 9 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
  ],
};
