window.POEMS = window.POEMS || {};

window.POEMS["le-possede"] = {
  title: "Le Possédé",
  titles: { fr: "Le Possédé", en: "The Possessed One", es: "El poseso" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Le soleil s’est couvert d’un crêpe. Comme lui,", en: "The sun is enveloped in crape! like it,", es: "El sol se ha cubierto con un crespón. Como él,",
      wordGroups: [
        { wid: "0-0", fr: "Le soleil", en: "The sun", es: "El sol" },
        { wid: "0-1", fr: "s’est couvert", en: "is enveloped", es: "se ha cubierto" },
        { wid: "0-2", fr: "crêpe", en: "crape", es: "crespón" },
        { wid: "0-3", fr: "Comme lui", en: "like it", es: "Como él" },
      ] },
    { id: 1, fr: "Ô Lune de ma vie ! emmitoufle-toi d’ombre ;", en: "O Moon of my Life! wrap thyself up in shade;", es: "¡Oh, Luna de mi vida! arrópate de sombra;",
      wordGroups: [
        { wid: "1-0", fr: "Ô Lune", en: "O Moon", es: "¡Oh, Luna" },
        { wid: "1-1", fr: "ma vie", en: "my Life", es: "mi vida" },
        { wid: "1-2", fr: "emmitoufle-toi", en: "wrap thyself up", es: "arrópate" },
        { wid: "1-3", fr: "d’ombre", en: "in shade", es: "de sombra" },
      ] },
    { id: 2, fr: "Dors ou fume à ton gré ; sois muette, sois sombre,", en: "At will, smoke or slumber, be silent, be staid,", es: "Duerme o fuma a tu agrado; permanece muda, sombría,",
      wordGroups: [
        { wid: "2-0", fr: "Dors", en: "slumber", es: "Duerme" },
        { wid: "2-1", fr: "fume", en: "smoke", es: "fuma" },
        { wid: "2-2", fr: "à ton gré", en: "At will", es: "a tu agrado" },
        { wid: "2-3", fr: "sois muette", en: "be silent", es: "permanece muda" },
        { wid: "2-4", fr: "sois sombre", en: "be staid", es: "sombría" },
      ] },
    { id: 3, fr: "Et plonge tout entière au gouffre de l’Ennui ;", en: "And dive deep down in Dispassion's dark pit.", es: "Y húndete íntegra en el abismo del Hastío;",
      wordGroups: [
        { wid: "3-0", fr: "Et", en: "And", es: "Y" },
        { wid: "3-1", fr: "plonge", en: "dive", es: "húndete" },
        { wid: "3-2", fr: "gouffre", en: "dark pit", es: "abismo" },
        { wid: "3-3", fr: "l’Ennui", en: "Dispassion's", es: "Hastío" },
      ] },
    { id: 4, fr: "Je t’aime ainsi ! Pourtant, si tu veux aujourd’hui,", en: "I cherish thee thus! But if 'tis thy mood,", es: "¡Te amo así! Sin embargo, si hoy tú deseas,",
      wordGroups: [
        { wid: "4-0", fr: "Je", en: "I" },
        { wid: "4-1", fr: "t’aime", en: "cherish thee", es: "Te amo" },
        { wid: "4-2", fr: "ainsi", en: "thus", es: "así" },
        { wid: "4-3", fr: "Pourtant", en: "But", es: "Sin embargo" },
        { wid: "4-4", fr: "tu veux", en: "thy mood", es: "tú deseas" },
      ] },
    { id: 5, fr: "Comme un astre éclipsé qui sort de la pénombre,", en: "Like a star that from out its penumbra appears,", es: "Como un astro eclipsado que sale de la penumbra,",
      wordGroups: [
        { wid: "5-0", fr: "Comme", en: "Like", es: "Como" },
        { wid: "5-1", fr: "un astre", en: "a star", es: "un astro" },
        { wid: "5-2", fr: "sort", en: "appears", es: "sale" },
        { wid: "5-3", fr: "de la pénombre", en: "its penumbra", es: "de la penumbra" },
      ] },
    { id: 6, fr: "Te pavaner aux lieux que la Folie encombre,", en: "To float in the regions where madness careers,", es: "Pavonearte en los lugares que la Locura obstruye,",
      wordGroups: [
        { wid: "6-0", fr: "Te pavaner", en: "To float", es: "Pavonearte" },
        { wid: "6-1", fr: "aux lieux", en: "in the regions", es: "en los lugares" },
        { wid: "6-2", fr: "la Folie", en: "madness", es: "la Locura" },
        { wid: "6-3", fr: "encombre", en: "careers", es: "obstruye" },
      ] },
    { id: 7, fr: "C’est bien ! Charmant poignard, jaillis de ton étui !", en: "Fair dagger! burst forth from thy sheath! 'tis good.", es: "¡Está bien! Delicioso puñal, ¡surge de tu vaina!",
      wordGroups: [
        { wid: "7-0", fr: "C’est bien", en: "'tis good", es: "Está bien" },
        { wid: "7-1", fr: "Charmant", en: "Fair", es: "Delicioso" },
        { wid: "7-2", fr: "poignard", en: "dagger", es: "puñal" },
        { wid: "7-3", fr: "jaillis", en: "burst forth", es: "surge" },
        { wid: "7-4", fr: "de ton étui", en: "from thy sheath", es: "de tu vaina" },
      ] },
    { id: 8, fr: "Allume ta prunelle à la flamme des lustres !", en: "Yea, light up thine eyes at the Fire of Renown!", es: "¡Ilumina tu pupila a la llama de los candelabros!",
      wordGroups: [
        { wid: "8-0", fr: "Allume", en: "light up", es: "Ilumina" },
        { wid: "8-1", fr: "ta prunelle", en: "thine eyes", es: "tu pupila" },
        { wid: "8-2", fr: "la flamme", en: "the Fire", es: "la llama" },
        { wid: "8-3", fr: "des lustres", en: "of Renown", es: "de los candelabros" },
      ] },
    { id: 9, fr: "Allume le désir dans les regards des rustres !", en: "Or kindle desire by the looks of some clown!", es: "¡Ilumina el deseo en las miradas de los rústicos!",
      wordGroups: [
        { wid: "9-0", fr: "Allume", en: "kindle", es: "Ilumina" },
        { wid: "9-1", fr: "le désir", en: "desire", es: "el deseo" },
        { wid: "9-2", fr: "les regards", en: "the looks", es: "las miradas" },
        { wid: "9-3", fr: "des rustres", en: "some clown", es: "de los rústicos" },
      ] },
    { id: 10, fr: "Tout de toi m’est plaisir, morbide ou pétulant ;", en: "Thine All is my joy, whether dull or aflame!", es: "Todo lo tuyo para mí es placer, morboso o petulante;",
      wordGroups: [
        { wid: "10-0", fr: "Tout de toi", en: "Thine All", es: "Todo lo tuyo" },
        { wid: "10-1", fr: "m’est plaisir", en: "is my joy", es: "para mí es placer" },
        { wid: "10-2", fr: "morbide", en: "dull", es: "morboso" },
        { wid: "10-3", fr: "pétulant", en: "aflame", es: "petulante" },
      ] },
    { id: 11, fr: "Sois ce que tu voudras, nuit noire, rouge aurore ;", en: "Just be what thou wilt, black night, dawn divine,", es: "Sé lo que quieras, noche negra, roja aurora;",
      wordGroups: [
        { wid: "11-0", fr: "Sois", en: "be", es: "Sé" },
        { wid: "11-1", fr: "ce que", en: "what", es: "lo que" },
        { wid: "11-2", fr: "tu voudras", en: "thou wilt", es: "quieras" },
        { wid: "11-3", fr: "nuit noire", en: "black night", es: "noche negra" },
        { wid: "11-4", fr: "rouge aurore", en: "dawn divine", es: "roja aurora" },
      ] },
    { id: 12, fr: "Il n’est pas une fibre en tout mon corps tremblant", en: "There is not a nerve in my trembling frame", es: "No hay una fibra en todo mi cuerpo palpitante",
      wordGroups: [
        { wid: "12-0", fr: "n’est pas", en: "is not", es: "No hay" },
        { wid: "12-1", fr: "une fibre", en: "a nerve", es: "una fibra" },
        { wid: "12-2", fr: "corps", en: "frame", es: "cuerpo" },
        { wid: "12-3", fr: "tremblant", en: "trembling", es: "palpitante" },
      ] },
    { id: 13, fr: "Qui ne crie : Ô mon cher Belzébuth, je t’adore !", en: "But cries, \"I adore thee, Beelzebub mine!\"", es: "Que no exclame: ¡Oh mi querido Belcebú, te adoro!",
      wordGroups: [
        { wid: "13-0", fr: "crie", en: "cries", es: "exclame" },
        { wid: "13-1", fr: "mon", en: "mine", es: "mi" },
        { wid: "13-2", fr: "Belzébuth", en: "Beelzebub", es: "Belcebú" },
        { wid: "13-3", fr: "t’adore", en: "I adore thee", es: "te adoro" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
