window.POEMS = window.POEMS || {};

window.POEMS["le-vampire"] = {
  title: "Le Vampire",
  titles: { fr: "Le Vampire" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Le_Vampire",
  },
  segments: [
    { id: 0, fr: "Toi qui, comme un coup de couteau," },
    { id: 1, fr: "Dans mon cœur plaintif es entrée ;" },
    { id: 2, fr: "Toi qui, forte comme un troupeau" },
    { id: 3, fr: "De démons, vins, folle et parée," },
    { id: 4, fr: "De mon esprit humilié" },
    { id: 5, fr: "Faire ton lit et ton domaine ;" },
    { id: 6, fr: "— Infâme à qui je suis lié" },
    { id: 7, fr: "Comme le forçat à la chaîne," },
    { id: 8, fr: "Comme au jeu le joueur têtu," },
    { id: 9, fr: "Comme à la bouteille l’ivrogne," },
    { id: 10, fr: "Comme aux vermines la charogne," },
    { id: 11, fr: "— Maudite, maudite sois-tu !" },
    { id: 12, fr: "J’ai prié le glaive rapide" },
    { id: 13, fr: "De conquérir ma liberté," },
    { id: 14, fr: "Et j’ai dit au poison perfide" },
    { id: 15, fr: "De secourir ma lâcheté." },
    { id: 16, fr: "Hélas ! le poison et le glaive" },
    { id: 17, fr: "M’ont pris en dédain et m’ont dit :" },
    { id: 18, fr: "« Tu n’es pas digne qu’on t’enlève" },
    { id: 19, fr: "À ton esclavage maudit," },
    { id: 20, fr: "Imbécile ! — de son empire" },
    { id: 21, fr: "Si nos efforts te délivraient," },
    { id: 22, fr: "Tes baisers ressusciteraient" },
    { id: 23, fr: "Le cadavre de ton vampire ! »" },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
