window.POEMS = window.POEMS || {};

window.POEMS["les-phares"] = {
  title: "Les Phares",
  titles: { fr: "Les Phares" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Les_Phares",
  },
  segments: [
    { id: 0, fr: "Rubens, fleuve d’oubli, jardin de la paresse," },
    { id: 1, fr: "Oreiller de chair fraîche où l’on ne peut aimer," },
    { id: 2, fr: "Mais où la vie afflue et s’agite sans cesse," },
    { id: 3, fr: "Comme l’air dans le ciel et la mer dans la mer ;" },
    { id: 4, fr: "Léonard de Vinci, miroir profond et sombre," },
    { id: 5, fr: "Où des anges charmants, avec un doux souris" },
    { id: 6, fr: "Tout chargé de mystère, apparaissent à l’ombre" },
    { id: 7, fr: "Des glaciers et des pins qui ferment leur pays ;" },
    { id: 8, fr: "Rembrandt, triste hôpital tout rempli de murmures," },
    { id: 9, fr: "Et d’un grand crucifix décoré seulement," },
    { id: 10, fr: "Où la prière en pleurs s’exhale des ordures," },
    { id: 11, fr: "Et d’un rayon d’hiver traversé brusquement ;" },
    { id: 12, fr: "Michel-Ange, lieu vague où l’on voit des Hercules" },
    { id: 13, fr: "Se mêler à des Christs, et se lever tout droits" },
    { id: 14, fr: "Des fantômes puissants qui dans les crépuscules" },
    { id: 15, fr: "Déchirent leur suaire en étirant leurs doigts ;" },
    { id: 16, fr: "Colères de boxeur, impudences de faune," },
    { id: 17, fr: "Toi qui sus ramasser la beauté des goujats," },
    { id: 18, fr: "Grand cœur gonflé d’orgueil, homme débile et jaune," },
    { id: 19, fr: "Puget, mélancolique empereur des forçats ;" },
    { id: 20, fr: "Watteau, ce carnaval où bien des cœurs illustres," },
    { id: 21, fr: "Comme des papillons, errent en flamboyant," },
    { id: 22, fr: "Décors frais et léger éclairés par des lustres" },
    { id: 23, fr: "Qui versent la folie à ce bal tournoyant ;" },
    { id: 24, fr: "Goya, cauchemar plein de choses inconnues," },
    { id: 25, fr: "De fœtus qu’on fait cuire au milieu des sabbats," },
    { id: 26, fr: "De vieilles au miroir et d’enfants toutes nues," },
    { id: 27, fr: "Pour tenter les démons ajustant bien leurs bas ;" },
    { id: 28, fr: "Delacroix, lac de sang hanté des mauvais anges," },
    { id: 29, fr: "Ombragé par un bois de sapins toujours vert," },
    { id: 30, fr: "Où, sous un ciel chagrin, des fanfares étranges" },
    { id: 31, fr: "Passent, comme un soupir étouffé de Weber ;" },
    { id: 32, fr: "Ces malédictions, ces blasphèmes, ces plaintes," },
    { id: 33, fr: "Ces extases, ces cris, ces pleurs, ces Te Deum," },
    { id: 34, fr: "Sont un écho redit par mille labyrinthes ;" },
    { id: 35, fr: "C’est pour les cœurs mortels un divin opium !" },
    { id: 36, fr: "C’est un cri répété par mille sentinelles," },
    { id: 37, fr: "Un ordre renvoyé par mille porte-voix ;" },
    { id: 38, fr: "C’est un phare allumé sur mille citadelles," },
    { id: 39, fr: "Un appel de chasseurs perdus dans les grands bois !" },
    { id: 40, fr: "Car c’est vraiment, Seigneur, le meilleur témoignage" },
    { id: 41, fr: "Que nous puissions donner de notre dignité" },
    { id: 42, fr: "Que cet ardent sanglot qui roule d’âge en âge" },
    { id: 43, fr: "Et vient mourir au bord de votre éternité !" },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
