window.POEMS = window.POEMS || {};

window.POEMS["les-chats"] = {
  title: "Les Chats",
  titles: { fr: "Les Chats", en: "Cats", es: "Los gatos" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Les amoureux fervents et les savants austères", en: "All ardent lovers and all sages prize,", es: "Los amantes fervorosos y los sabios austeros",
      wordGroups: [
        { wid: "0-0", fr: "Les amoureux", en: "lovers", es: "Los amantes" },
        { wid: "0-1", fr: "fervents", en: "ardent", es: "fervorosos" },
        { wid: "0-2", fr: "les savants", en: "all sages", es: "los sabios" },
      ] },
    { id: 1, fr: "Aiment également, dans leur mûre saison,", en: "--As ripening years incline upon their brows--", es: "Gustan por igual, en su madurez,",
      wordGroups: [
        { wid: "1-0", fr: "mûre", en: "ripening", es: "madurez" },
        { wid: "1-1", fr: "saison", en: "years" },
      ] },
    { id: 2, fr: "Les chats puissants et doux, orgueil de la maison,", en: "The mild and mighty cats--pride of the house--", es: "De los gatos fuertes y dulces, orgullo de la casa,",
      wordGroups: [
        { wid: "2-0", fr: "Les chats", en: "cats", es: "los gatos" },
        { wid: "2-1", fr: "puissants", en: "mighty", es: "fuertes" },
        { wid: "2-2", fr: "doux", en: "mild", es: "dulces" },
        { wid: "2-3", fr: "orgueil", en: "pride", es: "orgullo" },
        { wid: "2-4", fr: "de la maison", en: "of the house", es: "de la casa" },
      ] },
    { id: 3, fr: "Qui comme eux sont frileux et comme eux sédentaires.", en: "That like unto them are indolent, stern and wise.", es: "Que como ellos son friolentos y como ellos sedentarios.",
      wordGroups: [
        { wid: "3-0", fr: "Qui", en: "That", es: "Que" },
        { wid: "3-1", fr: "comme eux", en: "like unto them", es: "como ellos" },
        { wid: "3-2", fr: "sont", en: "are", es: "son" },
        { wid: "3-3", fr: "sédentaires", en: "indolent", es: "sedentarios" },
      ] },
    { id: 4, fr: "Amis de la science et de la volupté,", en: "The friends of Learning and of Ecstasy,", es: "Amigos de la ciencia y de la voluptuosidad,",
      wordGroups: [
        { wid: "4-0", fr: "Amis", en: "friends", es: "Amigos" },
        { wid: "4-1", fr: "la science", en: "Learning", es: "la ciencia" },
        { wid: "4-2", fr: "la volupté", en: "Ecstasy", es: "la voluptuosidad" },
      ] },
    { id: 5, fr: "Ils cherchent le silence et l’horreur des ténèbres ;", en: "They search for silence and the horrors of gloom;", es: "Buscan él silencio y el horror de las tinieblas;",
      wordGroups: [
        { wid: "5-0", fr: "Ils", en: "They" },
        { wid: "5-1", fr: "cherchent", en: "search for", es: "Buscan" },
        { wid: "5-2", fr: "le silence", en: "silence", es: "él silencio" },
        { wid: "5-3", fr: "l’horreur", en: "the horrors", es: "el horror" },
        { wid: "5-4", fr: "des ténèbres", en: "of gloom", es: "de las tinieblas" },
      ] },
    { id: 6, fr: "L’Érèbe les eût pris pour ses coursiers funèbres,", en: "The devil had used them for his steeds of Doom,", es: "El Erebo se hubiera apoderado de ellos para sus correrías fúnebres,",
      wordGroups: [
        { wid: "6-0", fr: "L’Érèbe", en: "The devil", es: "El Erebo" },
        { wid: "6-1", fr: "les", en: "them", es: "de ellos" },
        { wid: "6-2", fr: "eût pris", en: "had used", es: "hubiera apoderado" },
        { wid: "6-3", fr: "ses coursiers", en: "his steeds", es: "sus correrías" },
        { wid: "6-4", fr: "funèbres", en: "of Doom", es: "fúnebres" },
      ] },
    { id: 7, fr: "S’ils pouvaient au servage incliner leur fierté.", en: "Could he alone have bent their pride to slavery.", es: "Si hubieran podido ante la esclavitud inclinar su arrogancia.",
      wordGroups: [
        { wid: "7-0", fr: "pouvaient", en: "Could", es: "hubieran podido" },
        { wid: "7-1", fr: "au servage", en: "to slavery", es: "la esclavitud" },
        { wid: "7-2", fr: "incliner", en: "have bent", es: "inclinar" },
        { wid: "7-3", fr: "leur fierté", en: "their pride", es: "su arrogancia" },
      ] },
    { id: 8, fr: "Ils prennent en songeant les nobles attitudes", en: "When musing, they display those outlines chaste,", es: "Adoptan al soñar las nobles actitudes",
      wordGroups: [
        { wid: "8-0", fr: "Ils", en: "they" },
        { wid: "8-1", fr: "prennent", en: "display", es: "Adoptan" },
        { wid: "8-2", fr: "en songeant", en: "When musing", es: "al soñar" },
        { wid: "8-3", fr: "les nobles attitudes", en: "those outlines chaste", es: "las nobles actitudes" },
      ] },
    { id: 9, fr: "Des grands sphinx allongés au fond des solitudes,", en: "Of the great sphinxes--stretched o'er the sandy waste,", es: "De las grandes esfinges tendidas en el fondo de las soledades,",
      wordGroups: [
        { wid: "9-0", fr: "Des", en: "Of the", es: "De las" },
        { wid: "9-1", fr: "grands", en: "great", es: "grandes" },
        { wid: "9-2", fr: "sphinx", en: "sphinxes", es: "esfinges" },
        { wid: "9-3", fr: "allongés", en: "stretched", es: "tendidas" },
        { wid: "9-4", fr: "des solitudes", en: "the sandy waste", es: "de las soledades" },
      ] },
    { id: 10, fr: "Qui semblent s’endormir dans un rêve sans fin ;", en: "That seem to slumber deep in a dream without end:", es: "Que parecen dormirse en un sueño sin fin;",
      wordGroups: [
        { wid: "10-0", fr: "Qui", en: "That", es: "Que" },
        { wid: "10-1", fr: "semblent", en: "seem", es: "parecen" },
        { wid: "10-2", fr: "s’endormir", en: "to slumber", es: "dormirse" },
        { wid: "10-3", fr: "un rêve", en: "a dream", es: "un sueño" },
        { wid: "10-4", fr: "sans fin", en: "without end", es: "sin fin" },
      ] },
    { id: 11, fr: "Leurs reins féconds sont pleins d’étincelles magiques,", en: "From out their loins a fountainous furnace flies,", es: "Sus grupas fecundas están llenas de chispas mágicas,",
      wordGroups: [
        { wid: "11-0", fr: "Leurs reins", en: "their loins", es: "Sus grupas" },
      ] },
    { id: 12, fr: "Et des parcelles d’or, ainsi qu’un sable fin,", en: "And grains of sparkling gold, as fine as sand,", es: "Y fragmentos de oro, cual arenas finas,",
      wordGroups: [
        { wid: "12-0", fr: "Et", en: "And", es: "Y" },
        { wid: "12-1", fr: "des parcelles", en: "grains", es: "fragmentos" },
        { wid: "12-2", fr: "d’or", en: "of sparkling gold", es: "de oro" },
        { wid: "12-3", fr: "sable", en: "sand", es: "arenas" },
        { wid: "12-4", fr: "fin", en: "fine", es: "finas" },
      ] },
    { id: 13, fr: "Étoilent vaguement leurs prunelles mystiques.", en: "Bestar the mystic pupils of their eyes.", es: "Chispean vagamente en sus místicas pupilas.",
      wordGroups: [
        { wid: "13-0", fr: "Étoilent", en: "Bestar", es: "Chispean" },
        { wid: "13-1", fr: "leurs", en: "their eyes", es: "sus" },
        { wid: "13-2", fr: "prunelles", en: "pupils", es: "pupilas" },
        { wid: "13-3", fr: "mystiques", en: "the mystic", es: "místicas" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
