window.POEMS = window.POEMS || {};

window.POEMS["obsession"] = {
  title: "Obsession",
  titles: { fr: "Obsession", en: "Obsession", es: "Obsesión" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Grands bois, vous m’effrayez comme des cathédrales ;", en: "Great forests, you alarm me like a mighty fane;", es: "Grandes bosques, me espantáis como catedrales;",
      wordGroups: [
        { wid: "0-0", fr: "Grands bois", en: "Great forests", es: "Grandes bosques" },
        { wid: "0-1", fr: "vous", en: "you" },
        { wid: "0-2", fr: "m’effrayez", en: "alarm me", es: "me espantáis" },
        { wid: "0-3", fr: "comme", en: "like", es: "como" },
        { wid: "0-4", fr: "des cathédrales", en: "a mighty fane", es: "catedrales" },
      ] },
    { id: 1, fr: "Vous hurlez comme l’orgue ; et dans nos cœurs maudits,", en: "Like organ-tones you roar, and in our hearts of stone,", es: "Aulláis como el órgano; y en nuestros corazones malditos,",
      wordGroups: [
        { wid: "1-0", fr: "Vous hurlez", en: "you roar", es: "Aulláis" },
        { wid: "1-1", fr: "comme", en: "Like", es: "como" },
        { wid: "1-2", fr: "l’orgue", en: "organ-tones", es: "el órgano" },
        { wid: "1-3", fr: "nos cœurs", en: "our hearts", es: "nuestros corazones" },
        { wid: "1-4", fr: "maudits", en: "of stone", es: "malditos" },
      ] },
    { id: 2, fr: "Chambres d’éternel deuil où vibrent de vieux râles,", en: "Where ancient sobs vibrate, O halls of endless pain!", es: "Estancias de eterno duelo donde vibran viejos estertores,",
      wordGroups: [
        { wid: "2-0", fr: "Chambres", en: "halls", es: "Estancias" },
        { wid: "2-1", fr: "d’éternel", en: "endless", es: "de eterno" },
        { wid: "2-2", fr: "deuil", en: "pain", es: "duelo" },
        { wid: "2-3", fr: "vibrent", en: "vibrate", es: "vibran" },
        { wid: "2-4", fr: "de vieux râles", en: "ancient sobs", es: "viejos estertores" },
      ] },
    { id: 3, fr: "Répondent les échos de vos De profundis.", en: "The answering echoes of your \"De Profundis\" moan.", es: "Responden a los ecos de vuestros De profundis.",
      wordGroups: [
        { wid: "3-0", fr: "Répondent", en: "The answering", es: "Responden" },
        { wid: "3-1", fr: "les échos", en: "echoes", es: "los ecos" },
        { wid: "3-2", fr: "de vos", en: "of your", es: "de vuestros" },
        { wid: "3-3", fr: "De profundis", en: "De Profundis", es: "De profundis" },
      ] },
    { id: 4, fr: "Je te hais, Océan ! tes bonds et tes tumultes,", en: "I hate thee, Ocean! hate thy tumults and thy throbs,", es: "¡Yo te odio, Océano! tus saltos y tus tumultos,",
      wordGroups: [
        { wid: "4-0", fr: "te", en: "thee", es: "te" },
        { wid: "4-1", fr: "hais", en: "hate", es: "odio" },
        { wid: "4-2", fr: "Océan", en: "Ocean", es: "Océano" },
        { wid: "4-3", fr: "tes bonds", en: "thy throbs", es: "tus saltos" },
        { wid: "4-4", fr: "tes tumultes", en: "thy tumults", es: "tus tumultos" },
      ] },
    { id: 5, fr: "Mon esprit les retrouve en lui ; ce rire amer", en: "My spirit finds them in himself. This bitter glee", es: "Mi espíritu en él los recobra. Esta risa amarga",
      wordGroups: [
        { wid: "5-0", fr: "Mon esprit", en: "My spirit", es: "Mi espíritu" },
        { wid: "5-1", fr: "les", en: "them", es: "los" },
        { wid: "5-2", fr: "retrouve", en: "finds", es: "recobra" },
        { wid: "5-3", fr: "en lui", en: "in himself", es: "en él" },
        { wid: "5-4", fr: "ce rire amer", en: "This bitter glee", es: "Esta risa amarga" },
      ] },
    { id: 6, fr: "De l’homme vaincu, plein de sanglots et d’insultes,", en: "Of vanquished mortals, full of insults and of sobs,", es: "Del hombre vencido, lleno de sollozos y de insultos,",
      wordGroups: [
        { wid: "6-0", fr: "l’homme", en: "mortals", es: "hombre" },
        { wid: "6-1", fr: "vaincu", en: "vanquished", es: "vencido" },
        { wid: "6-2", fr: "plein", en: "full", es: "lleno" },
        { wid: "6-3", fr: "sanglots", en: "sobs", es: "sollozos" },
        { wid: "6-4", fr: "d’insultes", en: "of insults", es: "de insultos" },
      ] },
    { id: 7, fr: "Je l’entends dans le rire énorme de la mer.", en: "I hear it in the mighteous laughter of the sea.", es: "Yo la escucho en la risa enorme del mar.",
      wordGroups: [
        { wid: "7-0", fr: "Je", en: "I", es: "Yo" },
        { wid: "7-1", fr: "l’entends", en: "hear it", es: "la escucho" },
        { wid: "7-2", fr: "le rire", en: "laughter", es: "la risa" },
        { wid: "7-3", fr: "énorme", en: "mighteous", es: "enorme" },
        { wid: "7-4", fr: "de la mer", en: "of the sea", es: "del mar" },
      ] },
    { id: 8, fr: "Comme tu me plairais, ô nuit ! sans ces étoiles", en: "O starless night! thy loveliness my soul inhales,", es: "¡Cómo me agradarías, oh noche! ¡Sin estas estrellas",
      wordGroups: [
        { wid: "8-0", fr: "tu me plairais", en: "thy loveliness", es: "me agradarías" },
        { wid: "8-1", fr: "nuit", en: "night", es: "noche" },
        { wid: "8-2", fr: "sans ces étoiles", en: "starless", es: "Sin estas estrellas" },
      ] },
    { id: 9, fr: "Dont la lumière parle un langage connu !", en: "Without those starry rays which speak a language known,", es: "Cuya luz habla un lenguaje conocido!",
      wordGroups: [
        { wid: "9-0", fr: "la lumière", en: "those starry rays", es: "luz" },
        { wid: "9-1", fr: "parle", en: "speak", es: "habla" },
        { wid: "9-2", fr: "un langage", en: "a language", es: "un lenguaje" },
        { wid: "9-3", fr: "connu", en: "known", es: "conocido" },
      ] },
    { id: 10, fr: "Car je cherche le vide, et le noir, et le nu !", en: "For I desire the dark, the naked and the lone.", es: "¡Porque yo busco el vacío, y el negro, y el desnudo!",
      wordGroups: [
        { wid: "10-0", fr: "Car", en: "For", es: "Porque" },
        { wid: "10-1", fr: "je cherche", en: "I desire", es: "yo busco" },
        { wid: "10-2", fr: "le vide", en: "the lone", es: "el vacío" },
        { wid: "10-3", fr: "le noir", en: "the dark", es: "el negro" },
        { wid: "10-4", fr: "le nu", en: "the naked", es: "el desnudo" },
      ] },
    { id: 11, fr: "Mais les ténèbres sont elles-mêmes des toiles", en: "But e'en those darknesses themselves to me are veils,", es: "Pero, las tinieblas son ellas mismas las telas",
      wordGroups: [
        { wid: "11-0", fr: "Mais", en: "But", es: "Pero" },
        { wid: "11-1", fr: "les ténèbres", en: "those darknesses", es: "las tinieblas" },
        { wid: "11-2", fr: "elles-mêmes", en: "themselves", es: "ellas mismas" },
        { wid: "11-3", fr: "des toiles", en: "veils", es: "las telas" },
      ] },
    { id: 12, fr: "Où vivent, jaillissant de mon œil par milliers,", en: "Where live--and, by the millions 'neath my eyelids prance,", es: "donde viven, brotando de mis ojos por millares,",
      wordGroups: [
        { wid: "12-0", fr: "Où", en: "Where", es: "donde" },
        { wid: "12-1", fr: "vivent", en: "live", es: "viven" },
        { wid: "12-2", fr: "jaillissant", en: "prance", es: "brotando" },
        { wid: "12-3", fr: "de mon œil", en: "my eyelids", es: "de mis ojos" },
        { wid: "12-4", fr: "par milliers", en: "by the millions", es: "por millares" },
      ] },
    { id: 13, fr: "Des êtres disparus aux regards familiers.", en: "Long, long departed Beings with familiar glance.", es: "Los seres desaparecidos de las miradas familiares.",
      wordGroups: [
        { wid: "13-0", fr: "Des êtres", en: "Beings", es: "Los seres" },
        { wid: "13-1", fr: "disparus", en: "departed", es: "desaparecidos" },
        { wid: "13-2", fr: "aux regards", en: "glance", es: "de las miradas" },
        { wid: "13-3", fr: "familiers", en: "familiar", es: "familiares" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
