window.POEMS = window.POEMS || {};

window.POEMS["reversibilite"] = {
  title: "Réversibilité",
  titles: { fr: "Réversibilité", es: "Reversibilidad" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/R%C3%A9versibilit%C3%A9",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Reversibilidad",
  },
  segments: [
    { id: 0, fr: "Ange plein de gaieté, connaissez-vous l’angoisse,", es: "Ángel lleno de alegría, ¿conoces la angustia,",
      wordGroups: [
        { wid: "0-0", fr: "Ange", es: "Ángel" },
        { wid: "0-1", fr: "plein", es: "lleno" },
        { wid: "0-2", fr: "gaieté", es: "alegría" },
      ] },
    { id: 1, fr: "La honte, les remords, les sanglots, les ennuis,", es: "La vergüenza, los remordimientos, los sollozos, las molestias,",
      wordGroups: [
        { wid: "1-0", fr: "honte", es: "vergüenza" },
        { wid: "1-1", fr: "remords", es: "remordimientos" },
        { wid: "1-2", fr: "sanglots", es: "sollozos" },
      ] },
    { id: 2, fr: "Et les vagues terreurs de ces affreuses nuits", es: "Y los vagos terrores de esas horribles noches",
      wordGroups: [
        { wid: "2-0", fr: "nuits", es: "noches" },
      ] },
    { id: 3, fr: "Qui compriment le cœur comme un papier qu’on froisse ?", es: "Que oprimen el corazón como un papel estrujado?",
      wordGroups: [
        { wid: "3-0", fr: "cœur", es: "corazón" },
      ] },
    { id: 4, fr: "Ange plein de gaieté, connaissez-vous l’angoisse ?", es: "Ángel lleno de alegría, ¿conoces la angustia?",
      wordGroups: [
        { wid: "4-0", fr: "Ange", es: "Ángel" },
        { wid: "4-1", fr: "plein", es: "lleno" },
        { wid: "4-2", fr: "gaieté", es: "alegría" },
      ] },
    { id: 5, fr: "Ange plein de bonté, connaissez-vous la haine,", es: "Ángel lleno de bondad, ¿conoces el odio,",
      wordGroups: [
        { wid: "5-0", fr: "Ange", es: "Ángel" },
        { wid: "5-1", fr: "plein", es: "lleno" },
        { wid: "5-2", fr: "bonté", es: "bondad" },
        { wid: "5-3", fr: "haine", es: "odio" },
      ] },
    { id: 6, fr: "Les poings crispés dans l’ombre et les larmes de fiel,", es: "Los puños crispados, en la sombra y las lágrimas de hiel,",
      wordGroups: [
        { wid: "6-0", fr: "poings", es: "puños" },
        { wid: "6-1", fr: "larmes", es: "lágrimas" },
        { wid: "6-2", fr: "fiel", es: "hiel" },
      ] },
    { id: 7, fr: "Quand la Vengeance bat son infernal rappel,", es: "Cuando la venganza bate su infernal llamado,",
      wordGroups: [
        { wid: "7-0", fr: "Vengeance", es: "venganza" },
        { wid: "7-1", fr: "bat", es: "bate" },
        { wid: "7-2", fr: "infernal", es: "infernal" },
      ] },
    { id: 8, fr: "Et de nos facultés se fait le capitaine ?", es: "Y de nuestras facultades se hace la capitana?",
      wordGroups: [
        { wid: "8-0", fr: "facultés", es: "facultades" },
        { wid: "8-1", fr: "fait", es: "hace" },
        { wid: "8-2", fr: "capitaine", es: "capitana" },
      ] },
    { id: 9, fr: "Ange plein de bonté, connaissez-vous la haine ?", es: "Ángel lleno de bondad, ¿conoces el odio?",
      wordGroups: [
        { wid: "9-0", fr: "Ange", es: "Ángel" },
        { wid: "9-1", fr: "plein", es: "lleno" },
        { wid: "9-2", fr: "bonté", es: "bondad" },
        { wid: "9-3", fr: "haine", es: "odio" },
      ] },
    { id: 10, fr: "Ange plein de santé, connaissez-vous les Fièvres,", es: "Ángel lleno de salud, ¿conoces las fiebres,",
      wordGroups: [
        { wid: "10-0", fr: "Ange", es: "Ángel" },
        { wid: "10-1", fr: "plein", es: "lleno" },
        { wid: "10-2", fr: "santé", es: "salud" },
        { wid: "10-3", fr: "Fièvres", es: "fiebres" },
      ] },
    { id: 11, fr: "Qui, le long des grands murs de l’hospice blafard,", es: "Que a lo largo de los murallones pálidos del hospicio,",
      wordGroups: [
        { wid: "11-0", fr: "long", es: "largo" },
      ] },
    { id: 12, fr: "Comme des exilés, s’en vont d’un pied traînard,", es: "Como exiliados, se marchan arrastrando los pasos,",
      wordGroups: [
        { wid: "12-0", fr: "exilés", es: "exiliados" },
      ] },
    { id: 13, fr: "Cherchant le soleil rare et remuant les lèvres ?", es: "Buscando el raro sol y moviendo los labios?",
      wordGroups: [
        { wid: "13-0", fr: "Cherchant", es: "Buscando" },
        { wid: "13-1", fr: "soleil", es: "sol" },
        { wid: "13-2", fr: "rare", es: "raro" },
        { wid: "13-3", fr: "lèvres", es: "labios" },
      ] },
    { id: 14, fr: "Ange plein de santé, connaissez-vous les Fièvres ?", es: "Ángel pleno de salud, ¿conoces las fiebres?",
      wordGroups: [
        { wid: "14-0", fr: "Ange", es: "Ángel" },
        { wid: "14-1", fr: "santé", es: "salud" },
        { wid: "14-2", fr: "Fièvres", es: "fiebres" },
      ] },
    { id: 15, fr: "Ange plein de beauté, connaissez-vous les rides,", es: "Ángel lleno de belleza, ¿conoces las arrugas,",
      wordGroups: [
        { wid: "15-0", fr: "Ange", es: "Ángel" },
        { wid: "15-1", fr: "plein", es: "lleno" },
        { wid: "15-2", fr: "beauté", es: "belleza" },
        { wid: "15-3", fr: "rides", es: "arrugas" },
      ] },
    { id: 16, fr: "Et la peur de vieillir, et ce hideux tourment", es: "Y el miedo de envejecer, y este horrendo tormento",
      wordGroups: [
        { wid: "16-0", fr: "peur", es: "miedo" },
        { wid: "16-1", fr: "hideux", es: "horrendo" },
        { wid: "16-2", fr: "tourment", es: "tormento" },
      ] },
    { id: 17, fr: "De lire la secrète horreur du dévouement", es: "De leer el secreto horror de la abnegación",
      wordGroups: [
        { wid: "17-0", fr: "lire", es: "leer" },
        { wid: "17-1", fr: "secrète", es: "secreto" },
        { wid: "17-2", fr: "horreur", es: "horror" },
        { wid: "17-3", fr: "dévouement", es: "abnegación" },
      ] },
    { id: 18, fr: "Dans des yeux où longtemps burent nos yeux avides ?", es: "En los ojos donde largo tiempo bebieron nuestros ojos ávidos?",
      wordGroups: [
        { wid: "18-0", fr: "yeux", es: "ojos" },
        { wid: "18-1", fr: "yeux", es: "ojos" },
        { wid: "18-2", fr: "avides", es: "ávidos" },
      ] },
    { id: 19, fr: "Ange plein de beauté, connaissez-vous les rides ?", es: "Ángel lleno de belleza, ¿conoces las arrugas?",
      wordGroups: [
        { wid: "19-0", fr: "Ange", es: "Ángel" },
        { wid: "19-1", fr: "plein", es: "lleno" },
        { wid: "19-2", fr: "beauté", es: "belleza" },
        { wid: "19-3", fr: "rides", es: "arrugas" },
      ] },
    { id: 20, fr: "Ange plein de bonheur, de joie et de lumières,", es: "Ángel lleno de ventura, de alegría y de luces,",
      wordGroups: [
        { wid: "20-0", fr: "Ange", es: "Ángel" },
        { wid: "20-1", fr: "plein", es: "lleno" },
        { wid: "20-2", fr: "joie", es: "alegría" },
        { wid: "20-3", fr: "lumières", es: "luces" },
      ] },
    { id: 21, fr: "David mourant aurait demandé la santé", es: "David moribundo habría pedido la salvación",
      wordGroups: [
        { wid: "21-0", fr: "David", es: "David" },
        { wid: "21-1", fr: "mourant", es: "moribundo" },
        { wid: "21-2", fr: "aurait", es: "habría" },
      ] },
    { id: 22, fr: "Aux émanations de ton corps enchanté ;", es: "A las emanaciones de tu cuerpo encantado;",
      wordGroups: [
        { wid: "22-0", fr: "émanations", es: "emanaciones" },
        { wid: "22-1", fr: "corps", es: "cuerpo" },
      ] },
    { id: 23, fr: "Mais de toi je n’implore, ange, que tes prières,", es: "Pero, de ti yo no imploro, ángel, más que tus plegarias,",
      wordGroups: [
        { wid: "23-0", fr: "n’implore", es: "imploro" },
        { wid: "23-1", fr: "ange", es: "ángel" },
      ] },
    { id: 24, fr: "Ange plein de bonheur, de joie et de lumières !", es: "¡Ángel lleno de ventura, de alegría y de luces!",
      wordGroups: [
        { wid: "24-0", fr: "Ange", es: "Ángel" },
        { wid: "24-1", fr: "plein", es: "lleno" },
        { wid: "24-2", fr: "joie", es: "alegría" },
        { wid: "24-3", fr: "lumières", es: "luces" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
    { type: 'blank' },
    { type: 'stanza', lines: 5 },
  ],
};
