window.POEMS = window.POEMS || {};

window.POEMS["semper-eadem"] = {
  title: "Semper eadem",
  titles: { fr: "Semper eadem", en: "Semper Eadem", es: "Semper eadem" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "« D’où vous vient, disiez-vous, cette tristesse étrange,", en: "\"From whence it comes, you ask, this gloom acute,", es: "\"¿De dónde os viene, decís, esta tristeza extraña,",
      wordGroups: [
        { wid: "0-0", fr: "D’où vous vient", en: "From whence it comes", es: "De dónde os viene" },
        { wid: "0-1", fr: "disiez-vous", en: "you ask", es: "decís" },
        { wid: "0-2", fr: "cette tristesse étrange", en: "this gloom acute", es: "esta tristeza extraña" },
      ] },
    { id: 1, fr: "Montant comme la mer sur le roc noir et nu ? »", en: "Like waves that o'er the rocky headland fall?\"", es: "Trepando como el mar sobre el peñón negro y desnudo?\"",
      wordGroups: [
        { wid: "1-0", fr: "comme", en: "Like", es: "como" },
        { wid: "1-1", fr: "la mer", en: "waves", es: "el mar" },
        { wid: "1-2", fr: "le roc", en: "the rocky headland", es: "el peñón" },
      ] },
    { id: 2, fr: "— Quand notre cœur a fait une fois sa vendange,", en: "--When once our hearts have gathered in their fruit,", es: "—Cuando nuestro corazón ha hecho una vez su vendimia,",
      wordGroups: [
        { wid: "2-0", fr: "Quand", en: "When", es: "Cuando" },
        { wid: "2-1", fr: "notre cœur", en: "our hearts", es: "nuestro corazón" },
        { wid: "2-2", fr: "a fait", en: "have gathered in", es: "ha hecho" },
        { wid: "2-3", fr: "une fois", en: "once", es: "una vez" },
        { wid: "2-4", fr: "sa vendange", en: "their fruit", es: "su vendimia" },
      ] },
    { id: 3, fr: "Vivre est un mal. C’est un secret de tous connu,", en: "To live is a curse! a secret known to all,", es: "¡Vivir es un mal! Es un secreto de todos conocido,",
      wordGroups: [
        { wid: "3-0", fr: "Vivre", en: "To live", es: "Vivir" },
        { wid: "3-1", fr: "est un mal", en: "is a curse", es: "es un mal" },
        { wid: "3-2", fr: "un secret", en: "a secret", es: "un secreto" },
        { wid: "3-3", fr: "de tous connu", en: "known to all", es: "de todos conocido" },
      ] },
    { id: 4, fr: "Une douleur très-simple et non mystérieuse,", en: "A grief, quite simple, nought mysterious,", es: "Un dolor muy simple y nada misterioso,",
      wordGroups: [
        { wid: "4-0", fr: "Une douleur", en: "A grief", es: "Un dolor" },
        { wid: "4-1", fr: "très-simple", en: "quite simple", es: "muy simple" },
        { wid: "4-2", fr: "non", en: "nought", es: "nada" },
        { wid: "4-3", fr: "mystérieuse", en: "mysterious", es: "misterioso" },
      ] },
    { id: 5, fr: "Et, comme votre joie, éclatante pour tous.", en: "And like your joy--for all, both loud and shrill,", es: "Y, como vuestra alegría, brillante para todos.",
      wordGroups: [
        { wid: "5-0", fr: "comme", en: "like", es: "como" },
        { wid: "5-1", fr: "votre joie", en: "your joy", es: "vuestra alegría" },
        { wid: "5-2", fr: "éclatante", en: "both loud and shrill", es: "brillante" },
        { wid: "5-3", fr: "pour tous", en: "for all", es: "para todos" },
      ] },
    { id: 6, fr: "Cessez donc de chercher, ô belle curieuse !", en: "Nay cease to clamour, be not e'er so curious!", es: "Deja de buscar, entonces, ¡Oh, bella curiosa!",
      wordGroups: [
        { wid: "6-0", fr: "Cessez", en: "cease", es: "Deja" },
        { wid: "6-1", fr: "chercher", en: "to clamour", es: "buscar" },
        { wid: "6-2", fr: "curieuse", en: "curious", es: "curiosa" },
      ] },
    { id: 7, fr: "Et, bien que votre voix soit douce, taisez-vous !", en: "And yet although your voice is sweet, be still!", es: "Y, por más que vuestra voz sea dulce, ¡callad! ¡callaos!",
      wordGroups: [
        { wid: "7-0", fr: "Et", en: "And", es: "Y" },
        { wid: "7-1", fr: "bien que", en: "although", es: "por más que" },
        { wid: "7-2", fr: "votre voix", en: "your voice", es: "vuestra voz" },
        { wid: "7-3", fr: "soit douce", en: "is sweet", es: "sea dulce" },
        { wid: "7-4", fr: "taisez-vous", en: "be still", es: "callad" },
      ] },
    { id: 8, fr: "Taisez-vous, ignorante ! âme toujours ravie !", en: "Be still, O soul, with rapture ever rife!", es: "¡Callad, ignorante! ¡Alma siempre arrebatada!",
      wordGroups: [
        { wid: "8-0", fr: "Taisez-vous", en: "Be still", es: "Callad" },
        { wid: "8-1", fr: "âme", en: "soul", es: "Alma" },
        { wid: "8-2", fr: "toujours", en: "ever", es: "siempre" },
        { wid: "8-3", fr: "ravie", en: "with rapture", es: "arrebatada" },
      ] },
    { id: 9, fr: "Bouche au rire enfantin ! Plus encor que la Vie,", en: "O mouth, with the childish smile! Far more than Life,", es: "¡Boca de risa infantil! Más aún que la Vida,",
      wordGroups: [
        { wid: "9-0", fr: "Bouche", en: "mouth", es: "Boca" },
        { wid: "9-1", fr: "rire", en: "smile", es: "risa" },
        { wid: "9-2", fr: "enfantin", en: "childish", es: "infantil" },
        { wid: "9-3", fr: "Plus encor", en: "Far more", es: "Más aún" },
        { wid: "9-4", fr: "la Vie", en: "Life", es: "la Vida" },
      ] },
    { id: 10, fr: "La Mort nous tient souvent par des liens subtils.", en: "The subtle bonds of Death around us twine.", es: "La Muerte nos retiene casi siempre con lazos sutiles.",
      wordGroups: [
        { wid: "10-0", fr: "La Mort", en: "Death", es: "La Muerte" },
        { wid: "10-1", fr: "tient", en: "twine", es: "retiene" },
        { wid: "10-2", fr: "des liens", en: "bonds", es: "lazos" },
        { wid: "10-3", fr: "subtils", en: "subtle", es: "sutiles" },
      ] },
    { id: 11, fr: "Laissez, laissez mon cœur s’enivrer d’un mensonge,", en: "Let--let my heart, the wine of falsehood drink,", es: "¡Dejad, dejad mi corazón embriagarse de una mentira,",
      wordGroups: [
        { wid: "11-0", fr: "Laissez, laissez", en: "Let--let", es: "Dejad, dejad" },
        { wid: "11-1", fr: "mon cœur", en: "my heart", es: "mi corazón" },
        { wid: "11-2", fr: "s’enivrer", en: "drink", es: "embriagarse" },
        { wid: "11-3", fr: "d’un mensonge", en: "of falsehood", es: "de una mentira" },
      ] },
    { id: 12, fr: "Plonger dans vos beaux yeux comme dans un beau songe,", en: "And dream-like, deep within your fair eyes sink,", es: "Sumergirse en vuestros bellos ojos como en un hermoso sueño,",
      wordGroups: [
        { wid: "12-0", fr: "Plonger", en: "sink", es: "Sumergirse" },
        { wid: "12-1", fr: "dans", en: "within", es: "en" },
        { wid: "12-2", fr: "vos beaux yeux", en: "your fair eyes", es: "vuestros bellos ojos" },
        { wid: "12-3", fr: "comme dans un beau songe", en: "dream-like", es: "como en un hermoso sueño" },
      ] },
    { id: 13, fr: "Et sommeiller longtemps à l’ombre de vos cils !", en: "And in the shade of thy lashes long recline!", es: "Y dormitar mucho tiempo a la sombra de vuestras pestañas!",
      wordGroups: [
        { wid: "13-0", fr: "Et", en: "And", es: "Y" },
        { wid: "13-1", fr: "sommeiller", en: "recline", es: "dormitar" },
        { wid: "13-2", fr: "longtemps", en: "long", es: "mucho tiempo" },
        { wid: "13-3", fr: "à l’ombre", en: "in the shade", es: "a la sombra" },
        { wid: "13-4", fr: "de vos cils", en: "of thy lashes", es: "de vuestras pestañas" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
