window.POEMS = window.POEMS || {};

window.POEMS["sisina"] = {
  title: "Sisina",
  titles: { fr: "Sisina", en: "Sisina", es: "Sisina" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Imaginez Diane en galant équipage,", en: "Imagine Diana in gorgeous array,", es: "¡Imaginaos a Diana en galante cabalgata,",
      wordGroups: [
        { wid: "0-0", fr: "Imaginez", en: "Imagine", es: "Imaginaos" },
        { wid: "0-1", fr: "Diane", en: "Diana", es: "Diana" },
        { wid: "0-2", fr: "galant équipage", en: "gorgeous array", es: "galante cabalgata" },
      ] },
    { id: 1, fr: "Parcourant les forêts ou battant les halliers,", en: "How into the forests and thickets she flies,", es: "Recorriendo los bosques o batiendo los zarzales,",
      wordGroups: [
        { wid: "1-0", fr: "Parcourant", en: "she flies", es: "Recorriendo" },
        { wid: "1-1", fr: "les forêts", en: "the forests", es: "los bosques" },
        { wid: "1-2", fr: "les halliers", en: "thickets", es: "los zarzales" },
      ] },
    { id: 2, fr: "Cheveux et gorge au vent, s’enivrant de tapage,", en: "With her hair in the breezes, and flushed for the fray,", es: "Cabellos y pecho al viento, embriagándose de ruido,",
      wordGroups: [
        { wid: "2-0", fr: "Cheveux", en: "her hair", es: "Cabellos" },
        { wid: "2-1", fr: "au vent", en: "in the breezes", es: "al viento" },
        { wid: "2-2", fr: "s’enivrant", en: "flushed", es: "embriagándose" },
        { wid: "2-3", fr: "de tapage", en: "for the fray", es: "de ruido" },
      ] },
    { id: 3, fr: "Superbe et défiant les meilleurs cavaliers !", en: "How the very best riders she proudly defies.", es: "Soberbia y desafiando a los mejores jinetes!",
      wordGroups: [
        { wid: "3-0", fr: "Superbe", en: "proudly", es: "Soberbia" },
        { wid: "3-1", fr: "défiant", en: "defies", es: "desafiando" },
        { wid: "3-2", fr: "les meilleurs", en: "the very best", es: "los mejores" },
        { wid: "3-3", fr: "cavaliers", en: "riders", es: "jinetes" },
      ] },
    { id: 4, fr: "Avez-vous vu Théroigne, amante du carnage,", en: "Have you seen Théroigne, of the blood-thirsty heart,", es: "¿Has visto a Turingia, amante de la carnicería,",
      wordGroups: [
        { wid: "4-0", fr: "Avez-vous vu", en: "Have you seen", es: "Has visto" },
        { wid: "4-1", fr: "Théroigne", en: "Théroigne", es: "Turingia" },
        { wid: "4-2", fr: "du carnage", en: "blood-thirsty", es: "de la carnicería" },
      ] },
    { id: 5, fr: "Excitant à l’assaut un peuple sans souliers,", en: "As an unshod herd to attack he bestirs,", es: "Incitando al asalto a un pueblo descalzo,",
      wordGroups: [
        { wid: "5-0", fr: "Excitant", en: "bestirs", es: "Incitando" },
        { wid: "5-1", fr: "à l’assaut", en: "to attack", es: "al asalto" },
        { wid: "5-2", fr: "un peuple", en: "herd", es: "un pueblo" },
        { wid: "5-3", fr: "sans souliers", en: "unshod", es: "descalzo" },
      ] },
    { id: 6, fr: "La joue et l’œil en feu, jouant son personnage,", en: "With cheeks all inflamed, playing up to his part,", es: "Las mejillas y la mirada ardientes, encarnando su personaje,",
      wordGroups: [
        { wid: "6-0", fr: "La joue", en: "cheeks", es: "Las mejillas" },
        { wid: "6-1", fr: "en feu", en: "inflamed", es: "ardientes" },
        { wid: "6-2", fr: "jouant", en: "playing", es: "encarnando" },
        { wid: "6-3", fr: "son personnage", en: "his part", es: "su personaje" },
      ] },
    { id: 7, fr: "Et montant, sabre au poing, les royaux escaliers ?", en: "As he goes, sword in hand, up the royal stairs?", es: "Y trepando, sable en mano, las reales escaleras?",
      wordGroups: [
        { wid: "7-0", fr: "montant", en: "up", es: "trepando" },
        { wid: "7-1", fr: "sabre au poing", en: "sword in hand", es: "sable en mano" },
        { wid: "7-2", fr: "les royaux escaliers", en: "the royal stairs", es: "las reales escaleras" },
      ] },
    { id: 8, fr: "Telle la Sisina ! Mais la douce guerrière", en: "And so is Sisina--yet this warrior sweet,", es: "¡Tal la Sisina! Pero, la dulce guerrera",
      wordGroups: [
        { wid: "8-0", fr: "Sisina", en: "Sisina", es: "Sisina" },
        { wid: "8-1", fr: "Mais", en: "yet", es: "Pero" },
        { wid: "8-2", fr: "douce", en: "sweet", es: "dulce" },
        { wid: "8-3", fr: "guerrière", en: "warrior", es: "guerrera" },
      ] },
    { id: 9, fr: "A l’âme charitable autant que meurtrière ;", en: "Has a soul with compassion and kindness replete,", es: "Tiene el alma tan caritativa como asesina;",
      wordGroups: [
        { wid: "9-0", fr: "A l’âme", en: "Has a soul", es: "Tiene el alma" },
        { wid: "9-1", fr: "charitable", en: "compassion and kindness", es: "caritativa" },
      ] },
    { id: 10, fr: "Son courage, affolé de poudre et de tambours,", en: "Inspired by drums and by powder, her sway", es: "Su coraje, enloquecido de pólvora y de tambores,",
      wordGroups: [
        { wid: "10-0", fr: "Son courage", en: "her sway", es: "Su coraje" },
        { wid: "10-1", fr: "affolé", en: "Inspired", es: "enloquecido" },
        { wid: "10-2", fr: "de poudre", en: "by powder", es: "de pólvora" },
        { wid: "10-3", fr: "de tambours", en: "by drums", es: "de tambores" },
      ] },
    { id: 11, fr: "Devant les suppliants sait mettre bas les armes,", en: "Knows how to concede to the supplicants' prayers,", es: "Ante los suplicantes sabe abatir las armas,",
      wordGroups: [
        { wid: "11-0", fr: "Devant les suppliants", en: "the supplicants'", es: "Ante los suplicantes" },
        { wid: "11-1", fr: "sait", en: "Knows how", es: "sabe" },
        { wid: "11-2", fr: "mettre bas les armes", en: "to concede", es: "abatir las armas" },
      ] },
    { id: 12, fr: "Et son cœur, ravagé par la flamme, a toujours,", en: "And her bosom, laid waste by the flames, has alway,", es: "Y su corazón, azotado por la llama, tiene siempre,",
      wordGroups: [
        { wid: "12-0", fr: "son cœur", en: "her bosom", es: "su corazón" },
        { wid: "12-1", fr: "ravagé", en: "laid waste", es: "azotado" },
        { wid: "12-2", fr: "par la flamme", en: "by the flames", es: "por la llama" },
        { wid: "12-3", fr: "a toujours", en: "has alway", es: "tiene siempre" },
      ] },
    { id: 13, fr: "Pour qui s’en montre digne, un réservoir de larmes.", en: "For those that are worthy, a fountain of tears.", es: "Para el que se muestra digno, un receptáculo de lágrimas.",
      wordGroups: [
        { wid: "13-0", fr: "Pour qui", en: "For those", es: "Para el que" },
        { wid: "13-1", fr: "digne", en: "worthy", es: "digno" },
        { wid: "13-2", fr: "un réservoir", en: "a fountain", es: "un receptáculo" },
        { wid: "13-3", fr: "de larmes", en: "of tears", es: "de lágrimas" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
