window.POEMS = window.POEMS || {};

window.POEMS["spleen-1"] = {
  title: "Spleen",
  titles: { fr: "Spleen", en: "Spleen", es: "Spleen" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Pluviôse, irrité contre la ville entière,", en: "The rainy moon of all the world is weary,", es: "Pluvioso, irritado contra la ciudad entera,",
      wordGroups: [
        { wid: "0-0", fr: "Pluviôse", en: "The rainy moon", es: "Pluvioso" },
        { wid: "0-1", fr: "irrité", en: "is weary", es: "irritado" },
        { wid: "0-2", fr: "la ville entière", en: "all the world", es: "la ciudad entera" },
      ] },
    { id: 1, fr: "De son urne à grands flots verse un froid ténébreux", en: "And from its urn a gloomy cold pours down,", es: "De su urna, en grandes oleadas vierte un frío tenebroso",
      wordGroups: [
        { wid: "1-0", fr: "son urne", en: "its urn", es: "su urna" },
        { wid: "1-1", fr: "verse", en: "pours down", es: "vierte" },
        { wid: "1-2", fr: "un froid", en: "cold", es: "un frío" },
        { wid: "1-3", fr: "ténébreux", en: "gloomy", es: "tenebroso" },
      ] },
    { id: 2, fr: "Aux pâles habitants du voisin cimetière", en: "Upon the pallid inmates of the mortuary,", es: "Sobre los pálidos habitantes del vecino cementerio",
      wordGroups: [
        { wid: "2-0", fr: "Aux", en: "Upon", es: "Sobre los" },
        { wid: "2-1", fr: "pâles", en: "pallid", es: "pálidos" },
        { wid: "2-2", fr: "habitants", en: "inmates", es: "habitantes" },
        { wid: "2-3", fr: "cimetière", en: "mortuary", es: "cementerio" },
      ] },
    { id: 3, fr: "Et la mortalité sur les faubourgs brumeux.", en: "And on the neighbouring outskirts of the town.", es: "Y la mortandad sobre los arrabales brumosos.",
      wordGroups: [
        { wid: "3-0", fr: "Et", en: "And", es: "Y" },
        { wid: "3-1", fr: "sur", en: "on", es: "sobre" },
        { wid: "3-2", fr: "les faubourgs", en: "outskirts", es: "los arrabales" },
      ] },
    { id: 4, fr: "Mon chat sur le carreau cherchant une litière", en: "My wasted cat, in searching for a litter,", es: "Mi gato sobre el ladrillo buscando una litera",
      wordGroups: [
        { wid: "4-0", fr: "Mon chat", en: "My wasted cat", es: "Mi gato" },
        { wid: "4-1", fr: "cherchant", en: "in searching", es: "buscando" },
        { wid: "4-2", fr: "une litière", en: "a litter", es: "una litera" },
      ] },
    { id: 5, fr: "Agite sans repos son corps maigre et galeux ;", en: "Bestirs its mangy paws from post to post;", es: "Agita sin reposo su cuerpo flaco y sarnoso;",
      wordGroups: [
        { wid: "5-0", fr: "Agite", en: "Bestirs", es: "Agita" },
        { wid: "5-1", fr: "sans repos", en: "from post to post", es: "sin reposo" },
        { wid: "5-2", fr: "corps", en: "paws", es: "cuerpo" },
        { wid: "5-3", fr: "galeux", en: "mangy", es: "sarnoso" },
      ] },
    { id: 6, fr: "L’âme d’un vieux poëte erre dans la gouttière", en: "(A poet's soul that wanders in the gutter,", es: "El alma de un viejo poeta vaga en la gotera",
      wordGroups: [
        { wid: "6-0", fr: "L’âme", en: "soul", es: "El alma" },
        { wid: "6-1", fr: "d’un vieux poëte", en: "A poet's", es: "de un viejo poeta" },
        { wid: "6-2", fr: "erre", en: "wanders", es: "vaga" },
        { wid: "6-3", fr: "la gouttière", en: "the gutter", es: "la gotera" },
      ] },
    { id: 7, fr: "Avec la triste voix d’un fantôme frileux.", en: "With the jaded voice of a shiv'ring ghost).", es: "Con la triste voz de un fantasma friolento.",
      wordGroups: [
        { wid: "7-0", fr: "Avec", en: "With", es: "Con" },
        { wid: "7-1", fr: "la triste voix", en: "the jaded voice", es: "la triste voz" },
        { wid: "7-2", fr: "fantôme", en: "ghost", es: "fantasma" },
        { wid: "7-3", fr: "frileux", en: "shiv'ring", es: "friolento" },
      ] },
    { id: 8, fr: "Le bourdon se lamente, et la bûche enfumée", en: "The smoking pine-log, while the drone laments,", es: "El bordón se lamenta, y el leño ahumado",
      wordGroups: [
        { wid: "8-0", fr: "Le bourdon", en: "the drone", es: "El bordón" },
        { wid: "8-1", fr: "se lamente", en: "laments", es: "se lamenta" },
        { wid: "8-2", fr: "la bûche", en: "pine-log", es: "el leño" },
        { wid: "8-3", fr: "enfumée", en: "smoking", es: "ahumado" },
      ] },
    { id: 9, fr: "Accompagne en fausset la pendule enrhumée,", en: "Accompanies the wheezy pendulum,", es: "Acompaña en falsete al péndulo acatarrado,",
      wordGroups: [
        { wid: "9-0", fr: "Accompagne", en: "Accompanies", es: "Acompaña" },
        { wid: "9-1", fr: "pendule", en: "pendulum", es: "péndulo" },
        { wid: "9-2", fr: "enrhumée", en: "wheezy", es: "acatarrado" },
      ] },
    { id: 10, fr: "Cependant qu’en un jeu plein de sales parfums,", en: "The while amidst a haze of dirty scents,", es: "Mientras que en un mazo de naipes lleno de sucios olores,",
      wordGroups: [
        { wid: "10-0", fr: "Cependant", en: "The while", es: "Mientras que" },
        { wid: "10-1", fr: "plein", en: "amidst a haze", es: "lleno" },
        { wid: "10-2", fr: "sales", en: "dirty", es: "sucios" },
        { wid: "10-3", fr: "parfums", en: "scents", es: "olores" },
      ] },
    { id: 11, fr: "Héritage fatal d’une vieille hydropique,", en: "--Those fatal remnants of a sick man's room--", es: "Herencia fatal de una vieja hidrópica,",
      wordGroups: [
        { wid: "11-0", fr: "Héritage", en: "remnants", es: "Herencia" },
        { wid: "11-1", fr: "fatal", en: "fatal", es: "fatal" },
        { wid: "11-2", fr: "vieille hydropique", en: "a sick man's room", es: "vieja hidrópica" },
      ] },
    { id: 12, fr: "Le beau valet de cœur et la dame de pique", en: "The gallant knave of hearts and queen of spades", es: "El hermoso valet de coeur y la dama de pique",
      wordGroups: [
        { wid: "12-0", fr: "Le beau", en: "The gallant", es: "El hermoso" },
        { wid: "12-1", fr: "valet de cœur", en: "knave of hearts", es: "valet de coeur" },
        { wid: "12-2", fr: "la dame de pique", en: "queen of spades", es: "la dama de pique" },
      ] },
    { id: 13, fr: "Causent sinistrement de leurs amours défunts.", en: "Relate their ancient amorous escapades.", es: "Charlan siniestramente de sus amores difuntos.",
      wordGroups: [
        { wid: "13-0", fr: "Causent", en: "Relate", es: "Charlan" },
        { wid: "13-1", fr: "leurs", en: "their", es: "sus" },
        { wid: "13-2", fr: "amours", en: "amorous escapades", es: "amores" },
        { wid: "13-3", fr: "défunts", en: "ancient", es: "difuntos" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
