window.POEMS = window.POEMS || {};

window.POEMS["tout-entiere"] = {
  title: "Tout entière",
  titles: { fr: "Tout entière", en: "All Entire", es: "Todo integra" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_(1861)",
    en: "Translated by Cyril Scott, “The Flowers of Evil” (Elkin Mathews, London, 1909)",
    enUrl: "https://www.gutenberg.org/ebooks/36098",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Las_flores_del_mal",
  },
  segments: [
    { id: 0, fr: "Le Démon, dans ma chambre haute,", en: "The Demon, in my lofty vault,", es: "El Demonio, en mi altillo,",
      wordGroups: [
        { wid: "0-0", fr: "Le Démon", en: "The Demon", es: "El Demonio" },
        { wid: "0-1", fr: "chambre", en: "vault", es: "altillo" },
        { wid: "0-2", fr: "haute", en: "lofty" },
      ] },
    { id: 1, fr: "Ce matin est venu me voir,", en: "This morning came to visit me,", es: "Esta mañana vino a verme,",
      wordGroups: [
        { wid: "1-0", fr: "Ce matin", en: "This morning", es: "Esta mañana" },
        { wid: "1-1", fr: "est venu", en: "came", es: "vino" },
        { wid: "1-2", fr: "me voir", en: "visit me", es: "verme" },
      ] },
    { id: 2, fr: "Et, tâchant à me prendre en faute,", en: "And striving me to find at fault,", es: "Y, tratando de cogerme en falta,",
      wordGroups: [
        { wid: "2-0", fr: "tâchant", en: "striving", es: "tratando" },
        { wid: "2-1", fr: "me", en: "me" },
        { wid: "2-2", fr: "prendre", en: "find", es: "cogerme" },
        { wid: "2-3", fr: "en faute", en: "at fault", es: "en falta" },
      ] },
    { id: 3, fr: "Me dit : « Je voudrais bien savoir,", en: "He said, \"Fain would I know of thee;", es: "Me ha dicho: \"Yo quisiera saber,",
      wordGroups: [
        { wid: "3-0", fr: "dit", en: "said", es: "ha dicho" },
        { wid: "3-1", fr: "voudrais", en: "would", es: "quisiera" },
        { wid: "3-2", fr: "bien", en: "Fain" },
        { wid: "3-3", fr: "savoir", en: "know", es: "saber" },
      ] },
    { id: 4, fr: "Parmi toutes les belles choses", en: "\"Among the many beauteous things,", es: "Entre todas las hermosas cosas",
      wordGroups: [
        { wid: "4-0", fr: "Parmi", en: "Among", es: "Entre" },
        { wid: "4-1", fr: "toutes", en: "many", es: "todas" },
        { wid: "4-2", fr: "belles", en: "beauteous", es: "hermosas" },
        { wid: "4-3", fr: "choses", en: "things", es: "cosas" },
      ] },
    { id: 5, fr: "Dont est fait son enchantement,", en: "--All which _her_ subtle grace proclaim--", es: "De que está hecho su encanto,",
      wordGroups: [
        { wid: "5-0", fr: "son", en: "_her_", es: "su" },
        { wid: "5-1", fr: "enchantement", en: "subtle grace", es: "encanto" },
      ] },
    { id: 6, fr: "Parmi les objets noirs ou roses", en: "Among the dark and rosy things,", es: "Entre los objetos negros o rosados",
      wordGroups: [
        { wid: "6-0", fr: "Parmi", en: "Among", es: "Entre" },
        { wid: "6-1", fr: "objets", en: "things", es: "objetos" },
        { wid: "6-2", fr: "noirs", en: "dark", es: "negros" },
        { wid: "6-3", fr: "roses", en: "rosy", es: "rosados" },
      ] },
    { id: 7, fr: "Qui composent son corps charmant,", en: "Which go to make her charming frame,", es: "Que componen su cuerpo encantador,",
      wordGroups: [
        { wid: "7-0", fr: "composent", en: "go to make", es: "componen" },
        { wid: "7-1", fr: "son", en: "her", es: "su" },
        { wid: "7-2", fr: "corps", en: "frame", es: "cuerpo" },
        { wid: "7-3", fr: "charmant", en: "charming", es: "encantador" },
      ] },
    { id: 8, fr: "Quel est le plus doux. » — Ô mon âme !", en: "\"Which is the sweetest unto thee\"?", es: "Cuál es el más dulce.\" —¡Oh, mi alma!",
      wordGroups: [
        { wid: "8-0", fr: "Quel", en: "Which", es: "Cuál" },
        { wid: "8-1", fr: "est", en: "is", es: "es" },
        { wid: "8-2", fr: "le plus doux", en: "the sweetest", es: "el más dulce" },
      ] },
    { id: 9, fr: "Tu répondis à l’Abhorré :", en: "My soul! to Him thou didst retort--", es: "Tú respondiste al Aborrecido:",
      wordGroups: [
        { wid: "9-0", fr: "Tu", en: "thou", es: "Tú" },
        { wid: "9-1", fr: "répondis", en: "didst retort", es: "respondiste" },
        { wid: "9-2", fr: "à l’Abhorré", en: "to Him", es: "al Aborrecido" },
      ] },
    { id: 10, fr: "« Puisqu’en Elle tout est dictame,", en: "\"Since all with her is destiny,", es: "Puesto que en Ella todo está dictaminado,",
      wordGroups: [
        { wid: "10-0", fr: "Puisqu’en", en: "Since", es: "Puesto que en" },
        { wid: "10-1", fr: "Elle", en: "her", es: "Ella" },
        { wid: "10-2", fr: "tout", en: "all", es: "todo" },
        { wid: "10-3", fr: "dictame", en: "destiny", es: "dictaminado" },
      ] },
    { id: 11, fr: "Rien ne peut être préféré.", en: "Of preference there can be nought.", es: "Nada puede ser preferido.",
      wordGroups: [
        { wid: "11-0", fr: "Rien", en: "nought", es: "Nada" },
        { wid: "11-1", fr: "peut", en: "can", es: "puede" },
        { wid: "11-2", fr: "être", en: "be", es: "ser" },
        { wid: "11-3", fr: "préféré", en: "preference", es: "preferido" },
      ] },
    { id: 12, fr: "Lorsque tout me ravit, j’ignore", en: "When all transports me with delight,", es: "Cuando todo me encanta, yo ignoro",
      wordGroups: [
        { wid: "12-0", fr: "Lorsque", en: "When", es: "Cuando" },
        { wid: "12-1", fr: "tout", en: "all", es: "todo" },
        { wid: "12-2", fr: "me", en: "me", es: "me" },
        { wid: "12-3", fr: "ravit", en: "transports", es: "encanta" },
      ] },
    { id: 13, fr: "Si quelque chose me séduit.", en: "If aught deludes I can not know,", es: "Si alguna cosa me seduce,",
      wordGroups: [
        { wid: "13-0", fr: "Si", en: "If", es: "Si" },
        { wid: "13-1", fr: "quelque chose", en: "aught", es: "alguna cosa" },
        { wid: "13-2", fr: "séduit", en: "deludes", es: "seduce" },
      ] },
    { id: 14, fr: "Elle éblouit comme l’Aurore", en: "She either lulls one like the Night,", es: "Ella deslumbra como la Aurora",
      wordGroups: [
        { wid: "14-0", fr: "Elle", en: "She", es: "Ella" },
        { wid: "14-1", fr: "comme", en: "like", es: "como" },
      ] },
    { id: 15, fr: "Et console comme la Nuit ;", en: "Or dazzles like the Morning-glow.", es: "Y consuela como la Noche;",
      wordGroups: [
        { wid: "15-0", fr: "comme", en: "like", es: "como" },
      ] },
    { id: 16, fr: "Et l’harmonie est trop exquise,", en: "That harmony is too divine,", es: "Y la armonía es harto exquisita,",
      wordGroups: [
        { wid: "16-0", fr: "l’harmonie", en: "harmony", es: "la armonía" },
        { wid: "16-1", fr: "est", en: "is", es: "es" },
        { wid: "16-2", fr: "trop", en: "too", es: "harto" },
        { wid: "16-3", fr: "exquise", en: "divine", es: "exquisita" },
      ] },
    { id: 17, fr: "Qui gouverne tout son beau corps,", en: "Which governs all her body fair,", es: "Que gobierna todo su bello cuerpo,",
      wordGroups: [
        { wid: "17-0", fr: "gouverne", en: "governs", es: "gobierna" },
        { wid: "17-1", fr: "tout", en: "all", es: "todo" },
        { wid: "17-2", fr: "son", en: "her", es: "su" },
        { wid: "17-3", fr: "beau", en: "fair", es: "bello" },
        { wid: "17-4", fr: "corps", en: "body", es: "cuerpo" },
      ] },
    { id: 18, fr: "Pour que l’impuissante analyse", en: "For powerless mortals to define", es: "Para que la impotencia analice",
      wordGroups: [
        { wid: "18-0", fr: "Pour", en: "For", es: "Para" },
        { wid: "18-1", fr: "l’impuissante", en: "powerless", es: "la impotencia" },
        { wid: "18-2", fr: "analyse", en: "define", es: "analice" },
      ] },
    { id: 19, fr: "En note les nombreux accords.", en: "In notes the many concords there.", es: "Anotando los numerosos acordes.",
      wordGroups: [
        { wid: "19-0", fr: "En", en: "In" },
        { wid: "19-1", fr: "note", en: "notes", es: "Anotando" },
        { wid: "19-2", fr: "nombreux", en: "many", es: "numerosos" },
        { wid: "19-3", fr: "accords", en: "concords", es: "acordes" },
      ] },
    { id: 20, fr: "Ô métamorphose mystique", en: "O mystic metamorphosis", es: "¡Oh, metamorfosis mística",
      wordGroups: [
        { wid: "20-0", fr: "métamorphose", en: "metamorphosis", es: "metamorfosis" },
        { wid: "20-1", fr: "mystique", en: "mystic", es: "mística" },
      ] },
    { id: 21, fr: "De tous mes sens fondus en un !", en: "Of all my senses blent in one!", es: "De todos mis sentidos fundidos en uno!",
      wordGroups: [
        { wid: "21-0", fr: "tous", en: "all", es: "todos" },
        { wid: "21-1", fr: "mes", en: "my", es: "mis" },
        { wid: "21-2", fr: "sens", en: "senses", es: "sentidos" },
        { wid: "21-3", fr: "fondus", en: "blent", es: "fundidos" },
        { wid: "21-4", fr: "en un", en: "in one", es: "en uno" },
      ] },
    { id: 22, fr: "Son haleine fait la musique,", en: "Her voice a beauteous perfume is,", es: "¡Su aliento produce la música,",
      wordGroups: [
        { wid: "22-0", fr: "Son", en: "Her", es: "Su" },
      ] },
    { id: 23, fr: "Comme sa voix fait le parfum ! »", en: "Her breath makes music, chaste and wan.", es: "Así como su voz hace el perfume!",
      wordGroups: [
        { wid: "23-0", fr: "fait", en: "makes", es: "hace" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
  ],
};
