window.POEMS = window.POEMS || {};

window.POEMS["un-fantome"] = {
  title: "Un Fantôme",
  titles: { fr: "Un Fantôme", es: "Un fantasma" },
  sources: {
    fr: "Les Fleurs du mal (1861) — French Wikisource",
    frUrl: "https://fr.wikisource.org/wiki/Les_Fleurs_du_mal_%281861%29/Un_Fant%C3%B4me",
    es: "Traducido por Eduardo Marquina, «Las flores del mal» (1905)",
    esUrl: "https://es.wikisource.org/wiki/Un_fantasma",
  },
  segments: [
    { id: 0, fr: "Dans les caveaux d’insondable tristesse", es: "En las cavernas de insondable tristeza",
      wordGroups: [
        { wid: "0-0", fr: "d’insondable", es: "insondable" },
        { wid: "0-1", fr: "tristesse", es: "tristeza" },
      ] },
    { id: 1, fr: "Où le Destin m’a déjà relégué ;", es: "Donde el Destino ya me ha relegado;",
      wordGroups: [
        { wid: "1-0", fr: "Destin", es: "Destino" },
        { wid: "1-1", fr: "relégué", es: "relegado" },
      ] },
    { id: 2, fr: "Où jamais n’entre un rayon rose et gai ;", es: "Donde jamás penetra un rayo rosado y alegre;",
      wordGroups: [
        { wid: "2-0", fr: "jamais", es: "jamás" },
        { wid: "2-1", fr: "rayon", es: "rayo" },
        { wid: "2-2", fr: "rose", es: "rosado" },
        { wid: "2-3", fr: "gai", es: "alegre" },
      ] },
    { id: 3, fr: "Où, seul avec la Nuit, maussade hôtesse,", es: "Donde, sólo, con la Noche, áspera huéspeda,",
      wordGroups: [
        { wid: "3-0", fr: "seul", es: "sólo" },
        { wid: "3-1", fr: "Nuit", es: "Noche" },
      ] },
    { id: 4, fr: "Je suis comme un peintre qu’un Dieu moqueur", es: "Yo soy como un pintor que un Dios burlón",
      wordGroups: [
        { wid: "4-0", fr: "suis", es: "soy" },
        { wid: "4-1", fr: "peintre", es: "pintor" },
        { wid: "4-2", fr: "Dieu", es: "Dios" },
        { wid: "4-3", fr: "moqueur", es: "burlón" },
      ] },
    { id: 5, fr: "Condamne à peindre, hélas ! sur les ténèbres ;", es: "Condena a pintar, ¡ah! sobre las tinieblas;",
      wordGroups: [
        { wid: "5-0", fr: "peindre", es: "pintar" },
        { wid: "5-1", fr: "ténèbres", es: "tinieblas" },
      ] },
    { id: 6, fr: "Où, cuisinier aux appétits funèbres,", es: "Oh, cocinero de apetitos fúnebres,",
      wordGroups: [
        { wid: "6-0", fr: "appétits", es: "apetitos" },
        { wid: "6-1", fr: "funèbres", es: "fúnebres" },
      ] },
    { id: 7, fr: "Je fais bouillir et je mange mon cœur,", es: "Yo hago hervir y como mi corazón,",
      wordGroups: [
        { wid: "7-0", fr: "fais", es: "hago" },
        { wid: "7-1", fr: "cœur", es: "corazón" },
      ] },
    { id: 8, fr: "Par instants brille, et s’allonge, et s’étale", es: "Por instantes brilla, se extiende, y se exhibe",
      wordGroups: [
        { wid: "8-0", fr: "instants", es: "instantes" },
        { wid: "8-1", fr: "brille", es: "brilla" },
      ] },
    { id: 9, fr: "Un spectre fait de grâce et de splendeur.", es: "Un espectro hecho de gracia y de esplendor.",
      wordGroups: [
        { wid: "9-0", fr: "spectre", es: "espectro" },
        { wid: "9-1", fr: "fait", es: "hecho" },
        { wid: "9-2", fr: "grâce", es: "gracia" },
        { wid: "9-3", fr: "splendeur", es: "esplendor" },
      ] },
    { id: 10, fr: "À sa rêveuse allure orientale,", es: "En un soñador paso oriental,",
      wordGroups: [
        { wid: "10-0", fr: "orientale", es: "oriental" },
      ] },
    { id: 11, fr: "Quand il atteint sa totale grandeur,", es: "Cuando alcanza su total grandeza,",
      wordGroups: [
        { wid: "11-0", fr: "totale", es: "total" },
        { wid: "11-1", fr: "grandeur", es: "grandeza" },
      ] },
    { id: 12, fr: "Je reconnais ma belle visiteuse :", es: "Yo reconozco a mi bella visita:",
      wordGroups: [
        { wid: "12-0", fr: "belle", es: "bella" },
      ] },
    { id: 13, fr: "C’est Elle ! noire et pourtant lumineuse.", es: "¡Es Ella! Negra y, no obstante, luminosa.",
      wordGroups: [
        { wid: "13-0", fr: "noire", es: "Negra" },
        { wid: "13-1", fr: "lumineuse", es: "luminosa" },
      ] },
    { id: 14, fr: "Lecteur, as-tu quelquefois respiré", es: "Lector, ¿alguna vez has respirado",
      wordGroups: [
        { wid: "14-0", fr: "Lecteur", es: "Lector" },
        { wid: "14-1", fr: "respiré", es: "respirado" },
      ] },
    { id: 15, fr: "Avec ivresse et lente gourmandise", es: "Con embriaguez y lenta golosina",
      wordGroups: [
        { wid: "15-0", fr: "ivresse", es: "embriaguez" },
        { wid: "15-1", fr: "lente", es: "lenta" },
      ] },
    { id: 16, fr: "Ce grain d’encens qui remplit une église,", es: "El grano de incienso que satura una iglesia,",
      wordGroups: [
        { wid: "16-0", fr: "grain", es: "grano" },
        { wid: "16-1", fr: "d’encens", es: "incienso" },
        { wid: "16-2", fr: "église", es: "iglesia" },
      ] },
    { id: 17, fr: "Ou d’un sachet le musc invétéré ?", es: "O de un \"sachet\" el almizcle inveterado?",
      wordGroups: [
        { wid: "17-0", fr: "sachet", es: "sachet" },
        { wid: "17-1", fr: "musc", es: "almizcle" },
        { wid: "17-2", fr: "invétéré", es: "inveterado" },
      ] },
    { id: 18, fr: "Charme profond, magique, dont nous grise", es: "¡Encanto profundo, mágico, con que nos embriaga",
      wordGroups: [
        { wid: "18-0", fr: "Charme", es: "Encanto" },
        { wid: "18-1", fr: "profond", es: "profundo" },
      ] },
    { id: 19, fr: "Dans le présent le passé restauré !", es: "En el presente el pasado revivido!",
      wordGroups: [
        { wid: "19-0", fr: "présent", es: "presente" },
        { wid: "19-1", fr: "passé", es: "pasado" },
      ] },
    { id: 20, fr: "Ainsi l’amant sur un corps adoré", es: "Así el amante sobre un cuerpo adorado",
      wordGroups: [
        { wid: "20-0", fr: "Ainsi", es: "Así" },
        { wid: "20-1", fr: "corps", es: "cuerpo" },
      ] },
    { id: 21, fr: "Du souvenir cueille la fleur exquise.", es: "Del recuerdo recoge la flor exquisita.",
      wordGroups: [
        { wid: "21-0", fr: "souvenir", es: "recuerdo" },
        { wid: "21-1", fr: "fleur", es: "flor" },
        { wid: "21-2", fr: "exquise", es: "exquisita" },
      ] },
    { id: 22, fr: "De ses cheveux élastiques et lourds,", es: "De sus cabellos elásticos y pesados,",
      wordGroups: [
        { wid: "22-0", fr: "cheveux", es: "cabellos" },
        { wid: "22-1", fr: "lourds", es: "pesados" },
      ] },
    { id: 23, fr: "Vivant sachet, encensoir de l’alcôve,", es: "Viviente \"sachet\", incensario de la alcoba,",
      wordGroups: [
        { wid: "23-0", fr: "Vivant", es: "Viviente" },
        { wid: "23-1", fr: "sachet", es: "sachet" },
        { wid: "23-2", fr: "encensoir", es: "incensario" },
      ] },
    { id: 24, fr: "Une senteur montait, sauvage et fauve,", es: "Un aroma subía, salvaje y fiero,",
      wordGroups: [
        { wid: "24-0", fr: "senteur", es: "aroma" },
        { wid: "24-1", fr: "montait", es: "subía" },
        { wid: "24-2", fr: "sauvage", es: "salvaje" },
      ] },
    { id: 25, fr: "Et des habits, mousseline ou velours,", es: "Y de sus ropas, muselina o terciopelo,",
      wordGroups: [
        { wid: "25-0", fr: "velours", es: "terciopelo" },
      ] },
    { id: 26, fr: "Tout imprégnés de sa jeunesse pure,", es: "Todas impregnadas de su juventud pura,",
      wordGroups: [
        { wid: "26-0", fr: "jeunesse", es: "juventud" },
        { wid: "26-1", fr: "pure", es: "pura" },
      ] },
    { id: 27, fr: "Se dégageait un parfum de fourrure.", es: "Se desprendía un perfume de piel.",
      wordGroups: [
        { wid: "27-0", fr: "parfum", es: "perfume" },
      ] },
    { id: 28, fr: "Comme un beau cadre ajoute à la peinture,", es: "Así como un bello marco agrega a la pintura,",
      wordGroups: [
        { wid: "28-0", fr: "beau", es: "bello" },
        { wid: "28-1", fr: "cadre", es: "marco" },
        { wid: "28-2", fr: "peinture", es: "pintura" },
      ] },
    { id: 29, fr: "Bien qu’elle soit d’un pinceau très-vanté,", es: "Bien que ella sea de un pincel muy alabado,",
      wordGroups: [
        { wid: "29-0", fr: "soit", es: "sea" },
        { wid: "29-1", fr: "vanté", es: "alabado" },
      ] },
    { id: 30, fr: "Je ne sais quoi d’étrange et d’enchanté", es: "Yo no sé qué de extraño y de encantado" },
    { id: 31, fr: "En l’isolant de l’immense nature,", es: "Al distanciarla de la inmensa natura,",
      wordGroups: [
        { wid: "31-0", fr: "nature", es: "natura" },
      ] },
    { id: 32, fr: "Ainsi bijoux, meubles, métaux, dorure,", es: "Así, joyas, muebles, metales, dorados,",
      wordGroups: [
        { wid: "32-0", fr: "Ainsi", es: "Así" },
        { wid: "32-1", fr: "bijoux", es: "joyas" },
        { wid: "32-2", fr: "meubles", es: "muebles" },
        { wid: "32-3", fr: "métaux", es: "metales" },
      ] },
    { id: 33, fr: "S’adaptaient juste à sa rare beauté ;", es: "Se adaptaban precisos a su rara belleza;",
      wordGroups: [
        { wid: "33-0", fr: "rare", es: "rara" },
        { wid: "33-1", fr: "beauté", es: "belleza" },
      ] },
    { id: 34, fr: "Rien n’offusquait sa parfaite clarté,", es: "Nada ofuscaba su perfecta claridad,",
      wordGroups: [
        { wid: "34-0", fr: "parfaite", es: "perfecta" },
        { wid: "34-1", fr: "clarté", es: "claridad" },
      ] },
    { id: 35, fr: "Et tout semblait lui servir de bordure.", es: "Y todo parecía servirle de marco.",
      wordGroups: [
        { wid: "35-0", fr: "semblait", es: "parecía" },
        { wid: "35-1", fr: "servir", es: "servirle" },
      ] },
    { id: 36, fr: "Même on eût dit parfois qu’elle croyait", es: "Hasta se hubiera dicho a veces que ella creía",
      wordGroups: [
        { wid: "36-0", fr: "dit", es: "dicho" },
        { wid: "36-1", fr: "parfois", es: "veces" },
      ] },
    { id: 37, fr: "Que tout voulait l’aimer ; elle noyait", es: "Que todo quería amarla; pues ahogaba",
      wordGroups: [
        { wid: "37-0", fr: "voulait", es: "quería" },
      ] },
    { id: 38, fr: "Sa nudité voluptueusement", es: "Su desnudez voluptuosamente",
      wordGroups: [
        { wid: "38-0", fr: "nudité", es: "desnudez" },
      ] },
    { id: 39, fr: "Dans les baisers du satin et du linge,", es: "En los besos de la seda y de la lencería,",
      wordGroups: [
        { wid: "39-0", fr: "baisers", es: "besos" },
      ] },
    { id: 40, fr: "Et, lente ou brusque, à chaque mouvement", es: "Y, lenta o brusca, en cada movimiento",
      wordGroups: [
        { wid: "40-0", fr: "lente", es: "lenta" },
        { wid: "40-1", fr: "chaque", es: "cada" },
        { wid: "40-2", fr: "mouvement", es: "movimiento" },
      ] },
    { id: 41, fr: "Montrait la grâce enfantine du singe.", es: "Mostraba la gracia infantil de un simio.",
      wordGroups: [
        { wid: "41-0", fr: "Montrait", es: "Mostraba" },
        { wid: "41-1", fr: "grâce", es: "gracia" },
      ] },
    { id: 42, fr: "La Maladie et la Mort font des cendres", es: "La Enfermedad y la Muerte producen cenizas",
      wordGroups: [
        { wid: "42-0", fr: "Mort", es: "Muerte" },
        { wid: "42-1", fr: "cendres", es: "cenizas" },
      ] },
    { id: 43, fr: "De tout le feu qui pour nous flamboya.", es: "De todo el fuego que por nosotros arde.",
      wordGroups: [
        { wid: "43-0", fr: "feu", es: "fuego" },
      ] },
    { id: 44, fr: "De ces grands yeux si fervents et si tendres,", es: "De aquellos grandes ojos tan fervientes y tan tiernos,",
      wordGroups: [
        { wid: "44-0", fr: "grands", es: "grandes" },
        { wid: "44-1", fr: "yeux", es: "ojos" },
        { wid: "44-2", fr: "fervents", es: "fervientes" },
      ] },
    { id: 45, fr: "De cette bouche où mon cœur se noya,", es: "De aquella boca en la que mi corazón se ahogó,",
      wordGroups: [
        { wid: "45-0", fr: "bouche", es: "boca" },
        { wid: "45-1", fr: "cœur", es: "corazón" },
      ] },
    { id: 46, fr: "De ces baisers puissants comme un dictame,", es: "De aquellos besos pujantes cual un dictamen,",
      wordGroups: [
        { wid: "46-0", fr: "baisers", es: "besos" },
        { wid: "46-1", fr: "dictame", es: "dictamen" },
      ] },
    { id: 47, fr: "De ces transports plus vifs que des rayons,", es: "De aquellos transportes más vivos que los rayos,",
      wordGroups: [
        { wid: "47-0", fr: "transports", es: "transportes" },
        { wid: "47-1", fr: "rayons", es: "rayos" },
      ] },
    { id: 48, fr: "Que reste-t-il ? C’est affreux, ô mon âme !", es: "¿Qué resta? ¡Es horrendo! ¡oh, mi alma mía!",
      wordGroups: [
        { wid: "48-0", fr: "reste", es: "resta" },
        { wid: "48-1", fr: "âme", es: "alma" },
      ] },
    { id: 49, fr: "Rien qu’un dessin fort pâle, aux trois crayons,", es: "Nada más que un diseño muy pálido, con tres trazos,",
      wordGroups: [
        { wid: "49-0", fr: "pâle", es: "pálido" },
        { wid: "49-1", fr: "trois", es: "tres" },
      ] },
    { id: 50, fr: "Qui, comme moi, meurt dans la solitude,", es: "Que, como yo, muere en la soledad,",
      wordGroups: [
        { wid: "50-0", fr: "meurt", es: "muere" },
        { wid: "50-1", fr: "solitude", es: "soledad" },
      ] },
    { id: 51, fr: "Et que le Temps, injurieux vieillard,", es: "Y que el Tiempo, injurioso anciano,",
      wordGroups: [
        { wid: "51-0", fr: "Temps", es: "Tiempo" },
        { wid: "51-1", fr: "injurieux", es: "injurioso" },
        { wid: "51-2", fr: "vieillard", es: "anciano" },
      ] },
    { id: 52, fr: "Chaque jour frotte avec son aile rude…", es: "Cada día frota con su ala ruda...",
      wordGroups: [
        { wid: "52-0", fr: "Chaque", es: "Cada" },
        { wid: "52-1", fr: "jour", es: "día" },
        { wid: "52-2", fr: "frotte", es: "frota" },
        { wid: "52-3", fr: "aile", es: "ala" },
        { wid: "52-4", fr: "rude", es: "ruda" },
      ] },
    { id: 53, fr: "Noir assassin de la Vie et de l’Art,", es: "Negro asesino de la Vida y del Arte,",
      wordGroups: [
        { wid: "53-0", fr: "Noir", es: "Negro" },
        { wid: "53-1", fr: "Vie", es: "Vida" },
        { wid: "53-2", fr: "l’Art", es: "Arte" },
      ] },
    { id: 54, fr: "Tu ne tueras jamais dans ma mémoire", es: "¡Tú no matarás jamás en mi memoria",
      wordGroups: [
        { wid: "54-0", fr: "jamais", es: "jamás" },
        { wid: "54-1", fr: "mémoire", es: "memoria" },
      ] },
    { id: 55, fr: "Celle qui fut mon plaisir et ma gloire !", es: "Aquella que fue mi placer y mi gloria!",
      wordGroups: [
        { wid: "55-0", fr: "plaisir", es: "placer" },
        { wid: "55-1", fr: "gloire", es: "gloria" },
      ] },
  ],
  blocks: [
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 4 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
    { type: 'blank' },
    { type: 'stanza', lines: 3 },
  ],
};
